### ISSUE TITLE
client does not detect connection failure

### ISSUE THREAD

**Issue by jpwsutton** [eclipse/paho.mqtt.python#10]
migrated from Bugzilla [#475579](https://bugs.eclipse.org/bugs/show_bug.cgi?id=475579)
status UNCONFIRMED severity *normal* in component *MQTT-Python* for *1.2*
Reported in version *1.1* on platform *PC*
Assigned to: Roger Light

On 2015-08-21 07:50:17 -0400, Gideon Farrell wrote:

> If Client has connected, and then connection is lost (for my tests I kill the MQTT broker):
> 
> a) the Client does not seem to detect that the connection has been terminated (or at least I see no way to be notified of such)
> b) nor does it report any sort of message send failure, so messages are permanently lost (I have confirmed that they are)

**Comment by ralight** [comment]
You are notified of failure in the on_disconnect callback.

**Comment by ralight** [comment]
If you think this is still a bug, please provide more details.
