### ISSUE TITLE
Paho does not support the SNI extension of TLS

### ISSUE THREAD

**Issue by jpwsutton** [eclipse/paho.mqtt.python#11]
migrated from Bugzilla [#471037](https://bugs.eclipse.org/bugs/show_bug.cgi?id=471037)
status UNCONFIRMED severity _enhancement_ in component _MQTT-Python_ for _1.2_
Reported in version _1.2_ on platform _All_
Assigned to: Roger Light

On 2015-06-25 14:04:34 -0400, Juan Carlos Jimenez wrote:

> The current implementation of Paho Python does not support the Server Name Indication extension of TLS.
> 
> This means that if a server has 2 VPS's trying to use TLS in the same port the connection will fail.
> 
> SNI support was added to the ssl module in the python version 2.7.9.
> 
> I have submitted a patch that will try to use SNI by default (pretty much every single SSL library out there supports it nowadays). If the ssl module does not support SNI, it will fall back to the non-SNI implementation.
> 
> You can find it here: https://git.eclipse.org/r/#/c/50658/
> 
> I'm currently using that patch and it is working fine for me.
> 
> Just opening the bug report for reference.

On 2015-06-25 17:50:34 -0400, Roger Light wrote:

> Thanks for the report and the gerrit push, I had spotted it I've just been quite busy recently. I'll try to have a look soon.

**Comment by Lokesh-K-Haralakatta** [comment]
Why can't we merge the changes from this commit - https://github.com/exosite/paho.mqtt.python/commit/9acc14285b2c06b14816d017912c25ec9ff1f0da to master repo? This commit has the changes to support to SNI for paho.mqtt.python. I used the code changes for one of our connectivity to IoT Platform for Client Side Certificate support, the changes worked fine. Can we have this changes merged ASAP?

**Comment by PierreF** [comment]
SNI support is already added on develop branch by PR #92 but not yet released.

**Comment by Lokesh-K-Haralakatta** [comment]
Any idea, when can we have the SNI support released and available as part of paython pkg?

**Comment by PierreF** [comment]
Closing the issue, since fix is already committed.
Release with SNI support is expected by end of June
