### ISSUE TITLE
Client.subscribe() fails for unicode topic in tuple/list

### ISSUE THREAD

**Issue by by2coffee** [eclipse/paho.mqtt.python#111]
Using v1.2 on Python 2.x

As an extension of #16, subscribe should accept unicode topic names when part of tuple and list of tuples too

`subscribe("my/topic", 2)` and `subscribe(u"my/topic", 2)` works
But, 
`subscribe((u"my/topic", 1))` and `subscribe([(u"my/topic", 0), (u"another/topic", 2)])` raises `ValueError('Invalid topic.')`

**Comment by PierreF** [comment]
Hi,

Indeed, currently with Python 2, the code don't handle unicode very well.
It's fixed on the devel branch by #81, but before this get released, you will need to avoid unicode and only use ascii topic or use Python 3.

**Comment by by2coffee** [comment]
It seemed like an incomplete fix to #16 was causing this. 

Currently I am converting all my topics to ascii. Thanks!

**Comment by PierreF** [comment]
Closing since this is fixed in develop branch.
