### ISSUE TITLE
Propose to remove SSL support for Python versions that don't have SSLContext

### ISSUE THREAD

**Issue by Nzbuu** [eclipse/paho.mqtt.python#115]
SSLContext was introduced in Python 2.7.9 and Python 3.2 and is the most flexible and robust way to establish an SSL connection. We already don't support SSL in Python 2.6 and we don't support Python 3.0 or 3.1 at all, so this would only affect clients running on Python 2.7.x with x < 9. I don't know how common this is, but I suspect it's increasingly unlikely.

The purpose of this change is to simplify the creation of SSL connections and to rely more on the standard library code. This should make it easier to make future enhancements and eliminated code branches that are not exercised in the unit tests.

https://github.com/eclipse/paho.mqtt.python/pull/92 adds support for SSLContext, but does not remove support for versions that do not have SSLContext. However, since Python 3.4+, with SSLContext, there is support to automatically perform the hostname check that is currently implemented separately in the Paho client. Addressing this with full backwards-compatibility adds yet another branch to the `reconnect` logic, which I'd like to trade against removing another branch elsewhere.

**Comment by Nzbuu** [comment]
The main problem with taking this forwards appears to be that some Linux distributions have Python 2.7 versions that are <2.7.9. For example, Ubuntu 14.04 LTS uses Python 2.7.6. Is this a real problem?

**Comment by ralight** [comment]
It does make me more reluctant. 14.04 also has Python 3.4 so I suppose it wouldn't be completely dropping support for 14.04.

**Comment by Nzbuu** [comment]
@ralight , that's pretty much exactly what I thought.

**Comment by PierreF** [comment]
This has been agreed for develop branch. Related to #163.
