### ISSUE TITLE
Unable to publish a message to Emqttd

### ISSUE THREAD

**Issue by DataEngg** [eclipse/paho.mqtt.python#117]
I am publishing a message to a topic in MQTT via paho MQTT python client.
When I send a message via Django server by hitting an api of message it get stuck in paho.publish method of python client in publishing a message.

However Api get stuck for a long time and it does not get return with an error either it gets time out or connection get lost.

Around 150K  user are simultaneously connected to MQTT while publishing message.

**Comment by PierreF** [comment]
Hi,

Could you provide more information so we could try reproduce this issue ? The version of paho-mqtt and eMQTT could be useful.
Also if possible the call to paho to publish the message.

Thanks

**Comment by PierreF** [comment]
Can't reproduce. Feel free to provide more information before reopening if the issue persist.
