### ISSUE TITLE
Calling message_callback_add within a callback causes deadlock

### ISSUE THREAD

**Issue by jpwsutton** [eclipse/paho.mqtt.python#12]
migrated from Bugzilla [#459012](https://bugs.eclipse.org/bugs/show_bug.cgi?id=459012)
status UNCONFIRMED severity *normal* in component *MQTT-Python* for *1.1*
Reported in version *1.1* on platform *Other*
Assigned to: Roger Light

On 2015-02-03 06:09:31 -0500, Ed Morris wrote:

> The following code locks up when a message is published to the topic 'bar'.
> 
> #!/usr/bin/python
> 
> import paho.mqtt.client as paho
> 
> def on_foo_message(mqttc,request,msg):
>     print("foo on_message")
>     pass
> 
> def on_message(mqttc,request,msg):
>     print("global on_message")
>     mqttc.subscribe("foo", 0)
>     print("Subscribed to foo")
>     mqttc.message_callback_add("foo/+",on_foo_message)
>     print("Added callback to foo")
> 
> mqttc = paho.Client()
> broker = "127.0.0.1"
> mqttport = 1883
> mqttc.on_message = on_message
> mqttc.connect(broker, mqttport, 60)
> mqttc.subscribe("bar", 0)
> mqttc.loop_forever()
> 
> I think it is because the call to self._callback_mutex.acquire() in message_callback_add never exits. This is because the mutex was already acquired in _handle_on_message and will not release until the on_message callback has finished - which cannot happen.

On 2015-06-10 22:38:22 -0400, YuLun Shih wrote:

> Same issue here, I think it's all about _callback_mutex

**Comment by AlexisBRENON** [comment]
Encounter this error too !

**Comment by yoch** [comment]
Maybe RLock must be used instead of Lock in client.

**Comment by drem-darios** [comment]
I ran into this problem too. I changed the Lock locally to RLock and it fixed the issue.

**Comment by ralight** [comment]
Thanks for the hints and confirmation that it works. I've pushed a change that fixes this.
