### ISSUE TITLE
main process hangs! when it publishes message to server

### ISSUE THREAD

**Issue by liujian883** [eclipse/paho.mqtt.python#122]
Hi,
In my main process, I create two timers with [threading.Timer] module. and I create a global MQTT client object,
then call client.loop_forever() .
when I publish a message to server in callback function of the two timers with the global MQTT client object created above,the process will hang on the publish function.meantime,the process can not be killed with Ctrl+C.
if I publish the message in the timers with creating a new MQTT client object not the global one every time, everything will be ok.
i don`t know how this happen. 
anyone help me ! Thanks!!!

**Comment by PierreF** [comment]
Hi,

The Cltr+C that don't kill the process usually means that some thread didn't not finished. In your case it's probably the Timer thread... if they hang they will never finish.

I can't reproduce your issue, so could you provide more informations about condition that produce this hang ?
Are messages using QoS 0 ? Do you had any processing that could cause this hang in paho callback (on_publish, on_message, ...) ? Also could you provide version of paho and Python that you are using ?

**Comment by PierreF** [comment]
Can't reproduce. Please provide more information before reopening if the issue persist.
