### ISSUE TITLE
Forced to do Certificate authorization for server if using SSL/TLS

### ISSUE THREAD

**Issue by asadislam94** [eclipse/paho.mqtt.python#123]
If you want to use SSL/TLS this library forces you to do certificate authorization. I was trying to connect to Azure MQTT and set up tls using the following command:

client.tls_set("/home/home/cert/Baltimore.pem", certfile=None, keyfile=None, cert_reqs=ssl.CERT_REQUIRED, tls_version=ssl.PROTOCOL_TLSv1, ciphers=None)

Here Baltimore..pem is the certificate for authorization. 
But if I change cert_reqs to ssl.CERT_NONE it still checks for certificate and gives me an error that "Certificate subject does not match remote hostname."

And also I am forced to provide a certificate file even if I don't want a certificate authorization. If I set it to 'None', it will give me an error that 'ca_certs must not be none'

**Comment by Nzbuu** [comment]
Can you try with the implementation in this pull request: https://github.com/eclipse/paho.mqtt.python/pull/92

**Comment by KohliDev** [comment]
I want to also have the same functionality where I can connect to server with ssl.CERT_NONE, but this functionality doesn`t seem to work it forces me to provide certificates.

**Comment by Nzbuu** [comment]
Try using the `develop` branch

**Comment by KohliDev** [comment]
Thanks @Nzbuu
 By the way I was able to achieve this functionality in Python with help of following code:

```
#!/usr/bin/env python

import paho.mqtt.client as mqtt
import ssl

def on_connect(client, userdata, flags, rc):
    print("Connected with result code "+str(rc))
    client.publish("paho/temperature", "temperature")

client = mqtt.Client()
client.on_connect = on_connect
client.tls_set("/Users/vkohli/Desktop/mqtt_cert/cert.pem",
               None,
               None, cert_reqs=ssl.CERT_NONE, tls_version=ssl.PROTOCOL_TLSv1, ciphers=None)
# disables peer verification
client.tls_insecure_set(True)
client.connect("ip-address", 8883, 60)

client.loop_forever()
```

I need to provide a random cacert.pem but the above configuration works and I`m able to connect to the server with SSL encryption without checking its certificate.
Why is it a forced requirement to provide caret.pem?

**Comment by Nzbuu** [comment]
@KohliDev , if you use the `develop` branch, then you can use whatever `SSLContext` object you want. Then you're only subject to the rules in the `ssl` library.

**Comment by KohliDev** [comment]
Still it enforces to provide ca_cert, even if I don't want to check server certificate or need to use client certs:

https://github.com/eclipse/paho.mqtt.python/blob/develop/src/paho/mqtt/client.py#L639

Websocket library which I was using previously never enforced to provide ca_cert.pem , it should be allowed to be None.

**Comment by Nzbuu** [comment]
Try the `tls_set_context` method

**Comment by PierreF** [comment]
In addition, in devel branch since PR #146, ca_cert is no longer needed if you Python version provide a default system CA (e.g. Python 2.7.9+ or 3.4+)

**Comment by KohliDev** [comment]
Thank for pointing this out, any plans to make it part of master branch and release on PyPi.

**Comment by Florimond** [comment]
Same here. I developped the Emitter Python SDK a couple of months ago (https://github.com/emitter-io/python), and I had to modify the mqtt library and provide this modified version in my package.

My modified verision's connect function has one more parameter, "secure", like this : 

`
def connect(self, host, port=1883, keepalive=60, bind_address="", secure=False):
    self.connect_async(host, port, keepalive, bind_address)
    return self.reconnect(secure)
`
Then, reconnect, is like this :

`
def reconnect(self, secure=False):
(...)
    if secure:
        if HAVE_SSL is False:
            raise ValueError('This platform has no SSL/TLS.')

        self._ssl = ssl.wrap_socket(sock)
`

And this part has been commented :

`            """
                certfile=self._tls_certfile,
                keyfile=self._tls_keyfile,
                ca_certs=self._tls_ca_certs,
                cert_reqs=self._tls_cert_reqs,
                ssl_version=self._tls_version,
                ciphers=self._tls_ciphers
            

            if self._tls_insecure is False:
                if sys.version_info[0] < 3 or (sys.version_info[0] == 3 and sys.version_info[1] < 2):
                    self._tls_match_hostname()
                else:
                    ssl.match_hostname(self._ssl.getpeercert(), self._host)
            """`

**Comment by PierreF** [comment]
I believe this issue is fixed. Feel free to reopen if the issue persist.

**Comment by cimba007** [comment]
Is this issue really fixed?

With the latest develop-branch
```
#!/usr/bin/env python

import paho.mqtt.client as mqtt
import ssl

def on_connect(client, userdata, flags, rc):
    print("Connected with result code "+str(rc))
    client.publish("paho/temperature", "temperature")

client = mqtt.Client()
client.on_connect = on_connect

client.tls_set(None,
               None,
               None, cert_reqs=ssl.CERT_NONE, tls_version=ssl.PROTOCOL_TLSv1, ciphers=None)
# disables peer verification
client.tls_insecure_set(True)


client.connect("raspi", 1884, 60)

client.loop_forever()
```

```
pi@raspio:~/mqtt $ python test2.py
Traceback (most recent call last):
  File "test2.py", line 15, in <module>
    None, cert_reqs=ssl.CERT_NONE, tls_version=ssl.PROTOCOL_TLSv1, ciphers=None)
  File "/usr/local/lib/python2.7/dist-packages/paho/mqtt/client.py", line 709, in tls_set
    self.tls_insecure_set(False)
  File "/usr/local/lib/python2.7/dist-packages/paho/mqtt/client.py", line 735, in tls_insecure_set
    self._ssl_context.check_hostname = not value
ValueError: check_hostname needs a SSL context with either CERT_OPTIONAL or CERT_REQUIRED

```


```
#!/usr/bin/env python

import paho.mqtt.client as mqtt
import ssl

def on_connect(client, userdata, flags, rc):
    print("Connected with result code "+str(rc))
    client.publish("paho/temperature", "temperature")

client = mqtt.Client()
client.on_connect = on_connect

ssl_ctx = ssl.create_default_context()
ssl_ctx.check_hostname = False  # Without this line, I does not work
client.tls_set_context(ssl_ctx)
client.tls_insecure_set(True)

client.connect("raspi", 1884, 60)

client.loop_forever()
```

```
pi@raspio:~/mqtt $ python test2.py
Traceback (most recent call last):
  File "test2.py", line 18, in <module>
    client.connect("raspi", 1884, 60)
  File "/usr/local/lib/python2.7/dist-packages/paho/mqtt/client.py", line 760, in connect
    return self.reconnect()
  File "/usr/local/lib/python2.7/dist-packages/paho/mqtt/client.py", line 919, in reconnect
    sock.do_handshake()
  File "/usr/lib/python2.7/ssl.py", line 840, in do_handshake
    self._sslobj.do_handshake()
ssl.SSLError: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:661)
```

**Comment by PierreF** [comment]
Hi,

there is indeed an issue with:
```
>>> mqtt.Client().tls_set(cert_reqs=ssl.CERT_NONE)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/pierref/dev/src/github.com/eclipse/paho.mqtt.python/src/paho/mqtt/client.py", line 708, in tls_set
    self.tls_insecure_set(False)
  File "/home/pierref/dev/src/github.com/eclipse/paho.mqtt.python/src/paho/mqtt/client.py", line 734, in tls_insecure_set
    self._ssl_context.check_hostname = not value
ValueError: check_hostname needs a SSL context with either CERT_OPTIONAL or CERT_REQUIRED
```

This should works. I reopen the issue to fix this.

In the meantime a workaround is to build manually the SSL context with correct option, like:
```
client = mqtt.Client()
client.on_connect = on_connect

ssl_ctx = ssl.create_default_context()
ssl_ctx.check_hostname = False
ssl_ctx.verify_mode = ssl.CERT_NONE
client.tls_set_context(ssl_ctx)
client.tls_insecure_set(True)  # This is probably redundant with ssl_ctx.check_hostname = False

client.connect("raspi", 1884, 60)
```

**Comment by cimba007** [comment]
Thanks, your proposed workaround is working for me.

**Comment by PierreF** [comment]
Committed a fix for this issue: now using cert_reqs=ssl.CERT_NONE make sure that check_hostname is False.

**Comment by niezhe** [comment]
通过使用正确的选项手动构建 SSL 上下文方式解决了问题

**Comment by Florimond** [comment]
> Reference in new

The de facto standard language in computer science is English. It's not my mother tongue either, but you don't see me posting comments in French. Please, translate your comment so we can all benefit from your insights.

Thank you for your understanding.
