### ISSUE TITLE
Error when try send a file (image)

### ISSUE THREAD

**Issue by javiisanchez** [eclipse/paho.mqtt.python#125]
Hi, I'm using paho.mqtt.python in python 2.7 and when I try to send a file (image), I see the next error:

Traceback (most recent call last):
  File "/home/pi/Desktop/Device1/Scripts/mqtt_publish.py", line 39, in <module>
    mqttc.publish(MQTT_TOPIC,byteArr,0,True)
  File "/usr/local/lib/python2.7/dist-packages/paho/mqtt/client.py", line 980, in publish
    rc = self._send_publish(local_mid, topic, local_payload, qos, retain, False, info)
  File "/usr/local/lib/python2.7/dist-packages/paho/mqtt/client.py", line 1988, in _send_publish
    upayload = payload.encode('utf-8')
UnicodeDecodeError: 'ascii' codec can't decode byte 0xff in position 0: ordinal not in range(128)

The publish script is the next:
```
# Import package
import paho.mqtt.client as mqtt

# Define Variables
MQTT_HOST = "192.168.1.39" #iot.eclipse.org
MQTT_PORT = 1883
MQTT_KEEPALIVE_INTERVAL = 45
MQTT_TOPIC = "Device1"
#MQTT_MSG = 25

def on_connect(mqttc, userdata, flags, rc):
        #Subscribe to a Topic
    mqttc.subscribe(MQTT_TOPIC, 0)
    print("Connection returned result: "+connack_string(rc))
        
    # Define on_publish event function
def on_publish(mqttc, userdata, mid):
    print "Message Published..."
    print("mid: " +str(mid))
    mqttc.disconect()
    
    # Initiate MQTT Client
mqttc = mqtt.Client(client_id="LCESS", clean_session=False)

    # Register publish callback function
mqttc.on_publish = on_publish
mqttc.on_connect = on_connect
    # Connect with MQTT Broker
    # probar mqttc.username_pw_set(username, password)
mqttc.connect(MQTT_HOST, MQTT_PORT, MQTT_KEEPALIVE_INTERVAL)		

    # Publish message to MQTT Broker
f= open("/home/pi/Desktop/images/image.jpg")
filecontent = f.read()
byteArr = bytes(filecontent)

mqttc.publish(MQTT_TOPIC,byteArr,0,True)
```

and subscribe:
```
import paho.mqtt.client as mqtt

# Define Variables
MQTT_BROKER = "192.168.1.39"
MQTT_PORT = 1883
MQTT_KEEPALIVE_INTERVAL = 45
MQTT_TOPIC = "Device1"


# Define on_connect event Handler
def on_connect(mosq, obj, rc):
    print("Connected with result code "+str(rc))
    #Subscribe to a the Topic
    mqttc.subscribe(MQTT_TOPIC, 0)

# Define on_subscribe event Handler
def on_subscribe(mosq, obj, mid, granted_qos):
    print "Subscribed to MQTT Topic"

# Define on_message event Handler
def on_message(mosq, obj, message):
    print("Received message '" + str(message.payload) + "' on topic '"
        + message.topic + "' with QoS " + str(message.qos))
    #if (type(message.payload) == 'byteArray'):
    f = open('/home/pi/Desktop/image.jpg','w')
    f.write(message.payload)
    f.close()
    print 'image received'
            
# Initiate MQTT Client
mqttc = mqtt.Client(client_id="LCSS", clean_session=False)

# Register Event Handlers
mqttc.on_message = on_message
mqttc.on_connect = on_connect
mqttc.on_subscribe = on_subscribe

# Connect with MQTT Broker
mqttc.connect(MQTT_BROKER, MQTT_PORT, MQTT_KEEPALIVE_INTERVAL )
```

When I try read or write the file out of the broker, it do correctly. 

Can you help me please?

**Comment by PierreF** [comment]
Hi,

IIRC, on Python 2 with current stable version of paho, you need to pass your binary data in a bytearray. If you don't paho will try to (re-)encode it in UTF-8.

So in your example, instead of
```
byteArr = bytes(filecontent)
```

try
```
byteArr = bytearray(filecontent)
```

Newer version of paho should fix this (it's fixed by #81 merger on master but not yet released)

**Comment by javiisanchez** [comment]
If I change it, I see the following error:

```
Traceback (most recent call last):
  File "/home/pi/Desktop/Device1/Scripts/mqtt_publish.py", line 42, in <module>
    mqttc.loop_forever()
  File "/usr/local/lib/python2.7/dist-packages/paho/mqtt/client.py", line 1378, in loop_forever
    rc = self.loop(timeout, max_packets)
  File "/usr/local/lib/python2.7/dist-packages/paho/mqtt/client.py", line 897, in loop
    rc = self.loop_read(max_packets)
  File "/usr/local/lib/python2.7/dist-packages/paho/mqtt/client.py", line 1177, in loop_read
    rc = self._packet_read()
  File "/usr/local/lib/python2.7/dist-packages/paho/mqtt/client.py", line 1766, in _packet_read
    rc = self._packet_handle()
  File "/usr/local/lib/python2.7/dist-packages/paho/mqtt/client.py", line 2245, in _packet_handle
    return self._handle_connack()
  File "/usr/local/lib/python2.7/dist-packages/paho/mqtt/client.py", line 2306, in _handle_connack
    self.on_connect(self, self._userdata, flags_dict, result)
  File "/home/pi/Desktop/Device1/Scripts/mqtt_publish.py", line 15, in on_connect
    print("Connection returned result: "+connack_string(rc))
NameError: global name 'connack_string' is not defined
```

**Comment by ralight** [comment]
Try `mqtt.connack_string(rc)` instead - that's how you've imported the module: `import paho.mqtt.client as mqtt`

**Comment by javiisanchez** [comment]
Yes, I underand, and this solution is correct!

Thanks to all and thanks for your time!!!

**Comment by Tanmayagarwal14** [comment]
Hi I am new to mqtt. I used your code for sending the text file. I was able to publish the file but not able to receive it through another script. I checked that the file is getting published using console utility. Any help will be Great. thanks in advance

This my code for subscription:-

import paho.mqtt.client as mqtt

MQTT_BROKER = "iot.eclipse.org"
MQTT_PORT = 1883
MQTT_KEEPALIVE_INTERVAL = 45
MQTT_TOPIC = "Device1"


# Define on_connect event Handler
def on_connect(mqttc, userdata, rc):
    print("Connected with result code "+str(rc))
    mqttc.subscribe(MQTT_TOPIC, 0)

# Define on_subscribe event Handler
def on_subscribe(mqttc, userdata, mid, granted_qos):
    print "Subscribed to MQTT Topic"

# Define on_message event Handler
def on_message(mqttc, userdata, message):
    print("Received message '" + str(message.payload) + "' on topic '" + message.topic + "' with QoS " + str(message.qos))
    if (type(message.payload) == 'byteArray'):
        f = open('/home/chettiar/Desktop/mqtt/filesend/qwer/aa.txt','w')
        f.write(message.payload)
        f.close()
        print 'image received'
            
# Initiate MQTT Client
mqttc = mqtt.Client(client_id="LCSS", clean_session=False)

mqttc.on_message = on_message
mqttc.on_connect = on_connect
mqttc.on_subscribe = on_subscribe

mqttc.connect(MQTT_BROKER, MQTT_PORT, MQTT_KEEPALIVE_INTERVAL )
