### ISSUE TITLE
Client.unsubscribe() fails for any unicode topics on python 2

### ISSUE THREAD

**Issue by jnill-lutron** [eclipse/paho.mqtt.python#128]
Using v1.2 on Python 2.7

Seemingly an extension of #111.

I can subscribe a single unicode topic successfully, however when attempting to unsubscribe from that topic, i receive ValueError("No topic specified, or incorrect topic type.").

**Comment by PierreF** [comment]
Hi,

Indeed, currently with Python 2, we can't subscribe or unsubscribe to non-ascii topic. Python 3 does already allow it.
It's fixed on the devel branch by #81, but before this get released, you will need to stick with ascii topic or use Python 3.

**Comment by jnill-lutron** [comment]
Thanks @PierreF!  Any ideas on the next release date?

**Comment by PierreF** [comment]
I'm closing the issue, since it's fixed in develop branch.
The release date is expected by end of June.
