### ISSUE TITLE
IPv6

### ISSUE THREAD

**Issue by hermanil** [eclipse/paho.mqtt.python#129]
I cant make it work with IPv6. Is it supported or am I mistaken about the format ? Tested with both python 2 and 3

mqttc.connect("2001:db8::1", 1883)

**Comment by PierreF** [comment]
Hi,

could you provide more information about the error you got ?

From a quick look, I don't see any issue with IPv6 and I can connect to "::1" (localhost in IPv6)

**Comment by hermanil** [comment]
Thank you for helping PierreF. In short, I created a Mosquitto relay on a Raspberry PI and were able to publish and subscribe successfully to topics using that relays IPv6 address. I also tested it using the MQTT dash Android app. When creating python programs using the paho.mqtt.client library, publishing or subscribing to topics does not work (no error messages) when addressing the realy with IPv6 in this format - mqttc.connect("2001:db8::1", 1883) - but it works when I address it with IPv4 with this format - mqttc.connect("192.168.0.1", 1883). If you mean it should work, I can recreate the problem and do some packet tracing.

**Comment by PierreF** [comment]
Yes, it should work. the host ("2001:db8::1" in your example, "::1" in my test) is passed as-is to socket.create_connection which support IPv6.

You may also get more message to added a callback to on_log:
```
def on_log(client, userdata, level, buf):
    print(buf)

mqttc.on_log = on_log
[...]
mqttc.connect(...)
```

**Comment by hermanil** [comment]
I have discovered that the client() function needs to specify the MQTT version for it to work toward the IPv6 relay. So IPv6 works fine after this change - as you said. For anyone who come across the same problem, try this: 

.Client("xxxxxxxxx", protocol=mqtt.MQTTv31)

**Comment by cemakpolat** [comment]
Hi, 
I tried the  ".Client("xxxxxxxxx", protocol=mqtt.MQTTv31)"  in may code, however, I encoutered "socket.error: [Errno 22] Invalid argument". It works with "::1" but not other IPv6 addresses.

**Comment by hermanil** [comment]
Could it be a networking issue ? Here is an example based on my working code:

def on_connect(mqttc, userdata, rc):
 mqttc.subscribe("mytopic1")
 mqttc.subscribe("mytopic2")
 mqttc.subscribe("mytopic3")
def on_message(mqttc, userdata, msg):
 if msg.topic == "mytopic1":
  if msg.payload == "1":
    -and so on  
mqttc = mqtt.Client("myclientid", protocol=mqtt.MQTTv31)
mqttc.on_connect = on_connect
mqttc.on_message = on_message
mqttc.connect("2001:db8:bad:beef::1", 1883)
mqttc.loop_start()

**Comment by cemakpolat** [comment]
Here is the console  output:

```
raceback (most recent call last):
  File "publisher.py", line 14, in <module>
    client.connect("fe80::6a97:17da:8b84:5948", 1883)
  File "/usr/local/lib/python2.7/dist-packages/paho/mqtt/client.py", line 686, in connect
    return self.reconnect()
  File "/usr/local/lib/python2.7/dist-packages/paho/mqtt/client.py", line 808, in reconnect
    sock = socket.create_connection((self._host, self._port), source_address=(self._bind_address, 0))
  File "/usr/lib/python2.7/socket.py", line 571, in create_connection
    raise err
socket.error: [Errno 22] Invalid argument
```

**Comment by hermanil** [comment]
I think the problem is that you use a link-local address. The host cannot determine which interface is the target since all interfaces use the fe80:::/64 prefix. You can probably add a % and an interface index at the end - like fe80::6a97:17da:8b84:5948%2 - or easier - use a global scoped address for the broker.

**Comment by hermanil** [comment]
If it is Linux the correct format for the link-local scoped address for the broker is probably something like fe80::ca7:fcb7:3cb3:c3a5%enp14s0 where enp14s0 is the interface id

**Comment by cemakpolat** [comment]
Thanks hermanil, it works like a charm, It seems that I need to spend a bit time to understand the concept of ipv6 :).

**Comment by hermanil** [comment]
Great. Just be aware if you move the client away from the same network as the broker, you need to target global unicast address to reach the broker

**Comment by cemakpolat** [comment]
It might be beginner question for Ipv6, how can I find the "global unicast address", should I define myself. I have seen many ipv6 unicast addresses in the forums, they are totally custom.

**Comment by hermanil** [comment]
ipv6 interfaces can have multiple addresses from multiple scopes. If you only have a link local address - starts with fe80: - you probably dont have a ipv6 routed network. The link local address is self assigned. For now,  developing in this environment is probably ok but when deployed in a production network, use an address from the GUA scope 2000::/3. You can assign it statically if you want. Addresses can also be auto assigned from a prefix advertisement or assigned by DHCP. It is a bit much to cover in this thread.

**Comment by PierreF** [comment]
I believe this issue is fixed. Feel free to reopen if the issue persist.

**Comment by cemakpolat** [comment]
yes, it is fixed, I forgot to comment
