### ISSUE TITLE
master vs. develop confusion

### ISSUE THREAD

**Issue by swails** [eclipse/paho.mqtt.python#140]
It seems recently that there is some confusion for newcomers as to the role of master and develop.  I think experience shows that for people coming to the repository on GitHub, the main branch they should be interested in is `develop` rather than `master`.

This assumes that GH visitors are primarily interested in development and the latest bleeding edge (this is not always the case, but most PRs that are opened by first-time contributors tend to be filed against master, after which they are told to resubmit against develop or fixes).

What do you (repository administrators) think about changing the Default branch to `develop` instead of `master`?  I think this would help alleviate a lot of this confusion and prevent first-time contributors from wasting time preparing a PR that is already done.

**Comment by PierreF** [comment]
The most problematic point is that develop don't have fixes committed in branch fixes, making develop branch no usable as-is.
I think a simple solution would be to always cherry-pick fixes in both branch (when the fix apply to both branches). It add a little overhead on maintainer but it's doable.

If that seems reasonable, I will merge the fixes branch in develop branch and make sure to cherry-pick all PR after that merge. @ralight, any thought ?

**Comment by Nzbuu** [comment]
Can we start by removing the `fixes` branch? In classical git flow, each hot-fix is merged into both `master` and `develop` and releases are tracked as tags. So the `master` branch in that model would look just like the `fixes` branch in this one.
