### ISSUE TITLE
Python 3  payload must be a string, bytearray, int, float or None

### ISSUE THREAD

**Issue by AdamMiltonBarker** [eclipse/paho.mqtt.python#145]
Hi guys the following code was working in one of my classes and now fails with the error in the title:

```
def publishToDeviceChannel(self, channel, data):
		if self._configs['locationID'] == None:
			print("locationID is required!")
			return False
		elif self._configs['zoneID'] == None:
			print("zoneID is required!")
			return False
		elif self._configs['deviceId'] == None:
			print("deviceId is required!")
			return False
		else:
			deviceChannel = '%s/Devices/%s/%s/%s' % (self._configs['locationID'], self._configs['zoneID'], self._configs['deviceId'], channel)
			self.mqttClient.publish(deviceChannel,json.dumps(data))
			print("Published to Device "+channel+" Channel")
```

Were the function call is as follows:

```
publishToDeviceChannel(
"Sensors",
{
"Sensor":"CCTV",
"SensorID":1,
"SensorValue":"NOT RECOGNISED"
}
)
```

I have checked and I have version 1.2, this has confused me, as have never had issues before with this function. Any ideas guys ? Thanks in advance.

**Comment by PierreF** [comment]
Hi,

I don't see way you get this error. The full traceback may help. The error "payload must be a string, bytearray, int, float or None" should not occur when payload is of type "str", which is the type of json.dumps in Python 2 and Python 3.

**Comment by Nzbuu** [comment]
I think you need to check "is None" rather than "== None", but that may not have a bearing on the error you've observed.

**Comment by AdamMiltonBarker** [comment]
@PierreF Hi, thanks for the reply I know, it doesnt make sense, the stranger thing is that using this code with exactly the same data:
	
```
	def publishToDeviceWarnings(self, data):
		if self._configs['locationID'] == None:
			print("locationID is required!")
			return False
		elif self._configs['zoneID'] == None:
			print("zoneID is required!")
			return False
		elif self._configs['deviceId'] == None:
			print("deviceId is required!")
			return False
		else:
			deviceSensorsTopic = '%s/Devices/%s/%s/Warnings' % (self._configs['locationID'], self._configs['zoneID'], self._configs['deviceId'])
			self.mqttClient.publish(deviceSensorsTopic,json.dumps(data))
			print("Published to Device Warnings "+deviceSensorsTopic)
```

Works as expected, the only difference between this code and the issue code above is that the channel is not send as a parameter, so literally, the existence of the channel parameter is what is causing the issue. 

@Nzbuu hi, no that does affect it and works fine.
