### ISSUE TITLE
Web site Getting Started example code TabError: https://eclipse.org/paho/clients/python/

### ISSUE THREAD

**Issue by ozgurturkiye** [eclipse/paho.mqtt.python#149]
Web site Getting Started code Error `Tab error`

  File "example.py", line 8
    client.subscribe("$SYS/#")
                             ^
TabError: inconsistent use of tabs and spaces in indentation

Site: On web site: https://eclipse.org/paho/clients/python/   Getting Started code has `TabError`

**Comment by PierreF** [comment]
Thanks for your report. Fix pushed.
