### ISSUE TITLE
Client.publish() fails if payload arg is <str> type and contains a byte not in range(128); python 2.7

### ISSUE THREAD

**Issue by jpwsutton** [eclipse/paho.mqtt.python#15]
migrated from Bugzilla [#462441](https://bugs.eclipse.org/bugs/show_bug.cgi?id=462441)
status UNCONFIRMED severity _normal_ in component _MQTT-Python_ for _1.1_
Reported in version _unspecified_ on platform _Macintosh_
Assigned to: Roger Light

On 2015-03-18 05:01:50 -0400, Michael Laing wrote:

> Python 2.7 <str>s may contain 8-bit bytes.
> 
> If a <str> containing a byte outside of range(128) is passed as the payload arg to Client.publish(), an error like the following occurs:
> 
> UnicodeDecodeError: 'ascii' codec can't decode byte <foo> in position <bar>: ordinal not in range(128)
> 
> Probably the best solution is to guard the encode in this part of the method with a try clause.
> 
> The workaround is to always pass in the payload as <unicode> or <bytearray>, avoiding <str>, particularly if the payload is opaque in one's application.

**Comment by karlp** [comment]
looks like some details in the workaround went missing in the import?

**Comment by PierreF** [comment]
I think this is fixed on develop branch. If not, feel free to reopen
