### ISSUE TITLE
connect_srv not working for secure mqtt

### ISSUE THREAD

**Issue by je-al** [eclipse/paho.mqtt.python#150]
(I've not thoroughly tested this)
I'm trying to use `connect_srv` with `secure-mqtt.*` records, and from looking at the code in the current master, it seems there's no way to enable the code to actually query for them.

https://github.com/eclipse/paho.mqtt.python/blob/master/src/paho/mqtt/client.py#L705

currently checks for `self._ssl` to be assigned, but that only ever happens on `reconnect` which is called from the `connect` bellow.

I've empirically solved this by changing the line to:
```
            if self._tls_ca_certs is not None:
```
instead.

**Comment by PierreF** [comment]
Hi,

Good catch! Indeed it's a bug present in released and in fixes branch.

Due to a rewrite of SSL in develop branch, this bug is fixed in this branch.

**Comment by je-al** [comment]
:+1:
