### ISSUE TITLE
Interrupting with sys.exit()

### ISSUE THREAD

**Issue by diegopx** [eclipse/paho.mqtt.python#152]
loop() should re-raise the SystemExit exception (as it re-raises the KeyboardInterrupt). Otherwise sys.exit() doesn't work if called inside the loop function, e.g. from a signal handler.

**Comment by jcgsville** [comment]
I'm experiencing something similar, and I don't know another way to fix it

**Comment by Zapaan** [comment]
Same here, I think it should only catch`Exception` to let system-exiting exceptions do their job (exit the system). The obvious workaround is to raise a `KeyboardInterrupt` directly in your code ...

**Comment by ralight** [comment]
This was fixed in v1.5.0. Thanks for the report and comments.
