### ISSUE TITLE
Trying to pass .ts and .ks certificates for a mqtt connection

### ISSUE THREAD

**Issue by Sandyroy95** [eclipse/paho.mqtt.python#153]
I am trying to connect to an mqtt broker through a paho.mqtt client in Python. When i tried to implement my testcase in a Eclipse paho mqtt utility tool, i found out that i need to pass the .ts(trust store) and .ks (key store) certificate along with the pass phrase to create a connection. The broker doesnt seem to take client side .pem certificate and the corresponding private key. 
Can anyone please tell me how do i achieve the same in my python code. tls_set doesnt seem to take .ts and .ks certificates. I am a beginner so not exactly aware of how to do that.I am attaching my code for reference:

import paho.mqtt.client as mqtt
import time
import os
import ssl

payload="""{
        "measureIds": [1],
        "timestamp": 1487225222000,
        "values": ["2763"]
}"""

def on_connect(client,userdata,flags,rc):
	print("Connection ack recieved wirh code %d." %(rc))

def on_message(client1, userdata, message):
	print("message received" ,str(message.payload.decode("utf-8")))

client1=mqtt.Client("somevalue",protocol=ssl)
client1.tls_set("/path/client.pem",certfile="/path/client.pem",keyfile="/path/privkey.pem")
client1.on_connect=on_connect
client1.om_message=on_message
time.sleep(1)
client1.connect("hostname",8883,60)
client1.loop_start()
client1.publish("measures/somevalue",str(payload))
time.sleep(5)
client1.disconnect()
client1.loop_stop()

Thanks.

**Comment by PierreF** [comment]
TrustStore and KeyStore are specific to Java world, so no Python can't use them directly.

You need to convert them to PEM file... which by looking are you Python code seems to be done.

On you code, don't create Client with protocol=ssl. Protocol should only be paho.mqtt.client.MQTTv31 or paho.mqtt.client.MQTTv311. That being said, I'm not sure it's the cause of your error.

If file are in the correct PEM format, then the errors may be the first argument to tls_set, which is ca_certs. You give "client.pem" to this argument, which may be wrong. ca_certs must contains certificate(s) needed to validated the *server* certificate.

**Comment by Sandyroy95** [comment]
@PierreF Sure i'll try to implement that. Btw, the reson why i mentioned the protocol as ssl is  because in the eclipse paho mqtt utility the server url is passed as:  'ssl://<hostname>:<port>. 
Is there a specific way to declare that in my python script?

**Comment by PierreF** [comment]
Calling tls_set will enable TLS/SSL.

**Comment by Sandyroy95** [comment]
Thanks @PierreF .However, i am still having some trouble with the CA_CERT. Where do i get it from? I have a client side certificate(client.pem and client.p12), plainkey and the private key with me!!

**Comment by PierreF** [comment]
If you are running the server side, you also have a server side certificate and private key. This certificate could be the ca_cert.
If the server side is using "real" certificate (e.g. not self-signed), you could use your system ca-certificate (/etc/pki/tls/certs/ca-bundle.crt under CentOS/Fedora, /etc/ssl/certs/ca-certificates.crt under Debian/Ubuntu) I don't know for other systems.
If none of the above are true, the server operator should provide the certificate, you could in last change extract the certificate directly from the server. Note that this reduce the protection normally offered by a TLS/SSL connection, since you will ask the server itself to prove its own identity.
To extract it, the following should work:
```
openssl s_client -showcerts -servername www.example.com -connect www.example.com:443 </dev/null
```
The certificate(s) will be shown on the console. Copy/paste them to a file and you should be good.

**Comment by Sandyroy95** [comment]
Cool.Thanks again @PierreF

**Comment by opsagenceoneo** [comment]
hi 

i want read secure MQTT message using apache bahir library. and i don't know how to intergate de pem  certificate and private file

can you help me please

**Comment by PierreF** [comment]
As said above, if you are only using broker certificate for your SSL/TLS communication and still using username/password for authentication, then you just have to call tls_set with the CA certificates. The CA certificates will be used to validate the broker certificate:
```
client.tls_set("/etc/pki/tls/certs/ca-bundle.crt")  # Redhat/CentOS/Fedora
client.tls_set("/etc/ssl/certs/ca-certificates.crt")  # Debian/Ubuntu
```

If you are also using client certificate to authenticate client, then you need to provide the client certificate and client private key to tls_set call as [documented](https://github.com/eclipse/paho.mqtt.python#tls_set).

**Comment by opsagenceoneo** [comment]
Firstly i want thank you

 i want to recieve message from aws IOT  using sqlContext.readStream in databricks: 

as example of  using code :
val lines = sqlContext.readStream
    .format("org.apache.bahir.sql.streaming.mqtt.MQTTStreamSourceProvider")
    .option("topic", "$aws/things/agence/shadow/update/accepted")
    .option("QoS", 0)
    .option("clientId", "sparkTest1989201524565")
    .option("cleanSession", "true")
    .option("com.ibm.ssl.protocol","SSL_TLS")
 .option("com.ibm.ssl.trustStore",sqlContext.read.format("text").load("/FileStore/tables/ttdc16zc1491916221234/testkeystore.p12").toString())
    .load("ssl://XXXXX.iot.eu-west-1.amazonaws.com:8883").as[(String, Timestamp)]

val words = lines.map(_._1).flatMap(_.split(" "))
val wordCounts = words.groupBy("value").count()
val query = wordCounts.writeStream
  .outputMode("complete")
  .format("console")
  .start()
query.awaitTermination()
 as response i get bad_certificate.
thanks a lot for your help

**Comment by opsagenceoneo** [comment]
Yes
 can you please helping me using python with the otpion to include ssl certificate?

i need your help if it's possible of course
