### ISSUE TITLE
Question regarding unclosed socket in a test case using python mqtt

### ISSUE THREAD

**Issue by gourish2k** [eclipse/paho.mqtt.python#156]
I am checking a unit test method using python unittest for which uses InfluxDB python module for making connection to the InfluxDB database and inserting data.

I have used the following code

    from influxdb import InfluxDBClient
    import unittest

    class addvalues:
       def __init__ (self):
          self.host='localhost'
          self.port=8086
          self.user = 'root'
          self.password = 'root'
          self.dbname = 'example'

       def initialize(self):
          self._client = InfluxDBClient(self.host,  8086, self.user,
             self.password, self.dbname)
          self._client.create_database(self.dbname)

       def add(self, data):    
          self._client.write_points(data)

    class Test1(unittest.TestCase):

       def test_connect_and_popolate(self):
          tdat = [
                {
                   "measurement": "testmeasure",
                   "tags": {
                       "tag1": "R002",
                       "tag2": "R001"
                   },
                   "fields": {
                       "value": 1.23
                   }
               }
          ]

          connector = addvalues()
          connector.initialize()
          connector.add(tdat)

    if __name__ == '__main__':
        unittest.main() 

For which I get the following warning 

      ResourceWarning: unclosed <socket.socket fd=284, family=AddressFamily.AF_INET6, type=SocketKind.SOCK_STREAM, proto=0, laddr=('::1', 50930, 0, 0), raddr=('::1', 8086, 0, 0)>
      testMethod()
      .
      ----------------------------------------------------------------------
      Ran 1 test in 0.884s

      OK

I can remove the warning message by giving

    unittest.main(warnings='ignore')

instead of

    unittest.main()

However what is the reason for the warning, and how can I remove it without giving unittest.main(warnings='ignore'), or is any update required in the mqtt python module

**Comment by PierreF** [comment]
I'm not sure to understand, how this is related to MQTT ?

**Comment by gourish2k** [comment]
I am sorry mistakenly posting python influxdb question in mqtt which is not relevant here , I shall remove this issue post.
