### ISSUE TITLE
socket out of memory on subscribe

### ISSUE THREAD

**Issue by pvizeli** [eclipse/paho.mqtt.python#158]
Hi

We use this library inside HomeAssistant. Since we run faster (with help of asyncio), we see some "Out of memory" like https://github.com/home-assistant/home-assistant/issues/6247 or https://github.com/home-assistant/home-assistant/issues/6292

I try to fix it with a lock and sleep but look like that can come back some time. So I'm not sure if we make a misstake in handling of paho.

Our paho wrapper: https://github.com/home-assistant/home-assistant/blob/dev/homeassistant/components/mqtt/__init__.py

On our startup phase we connect to brocker. After that we allow all platforms that based on mqtt to use subscribe (that can be a lot) it is also possible that some platform allready publish things to brocker in same time. Is all things setup for HomeAssistant, we start the paho loop.

Is that handling correct or need to run the Loop bevor that to prevent the socket out of memory?

**Comment by harlowja** [comment]
I've also seen this, though I don't quite understand how this happens.

**Comment by PierreF** [comment]
paho-mqtt will queue message in memory if you send them faster than the network allow.

AFAIK, the only solution to limit the size of this queue is to track yourself the size of the pending queue:
* each time you call publish() increment a counter
* each time on_publish callback is called, decrement that counter

The value of the counter will be the number of message that are waiting in the queue. Keep that small enough to avoid eating all memory.

**Comment by jacksonofalltrades** [comment]
I'm subscribing to one topic, not publishing anything, and still getting an "Out of memory error" on every third call to loop().

**Comment by pvizeli** [comment]
We start the loop now before we process subscribtion and we solve it
