### ISSUE TITLE
Client.subscribe() fails for unicode topic

### ISSUE THREAD

**Issue by jpwsutton** [eclipse/paho.mqtt.python#16]
migrated from Bugzilla [#462379](https://bugs.eclipse.org/bugs/show_bug.cgi?id=462379)
status UNCONFIRMED severity *normal* in component *MQTT-Python* for *1.1*
Reported in version *unspecified* on platform *Macintosh*
Assigned to: Roger Light

On 2015-03-17 11:13:50 -0400, Michael Laing wrote:

> If the topic arg is unicode, subscribe() considers it invalid.
> 
> This is because tests in the method are for 'str' and not 'basestring'.
> 
> The documentation for the method should be correspondingly updated.
> 
> The workaround is to encode the topic arg as utf8 before sending to the method.

On 2015-03-17 19:35:42 -0400, Roger Light wrote:

> Is this on Python 2.x?

**Comment by vutana1** [comment]
Hi,
Still not possible to subscribe to unicode topic on Python 2.7 :
`client.subscribe(u'à',` qos=0)`
leads to:
UnicodeDecodeError: 'ascii' codec can't decode byte 0xc3 in position 24: ordinal not in range(128)

**Comment by PierreF** [comment]
Hi,

Indeed, currently with Python 2, we can't subscribe or unsubscribe to non-ascii topic. Python 3 does already allow it.
It's fixed on the devel branch by #81, but before this get released, you will need to stick with ascii topic or use Python 3.
