### ISSUE TITLE
can i set path of broker?

### ISSUE THREAD

**Issue by eduard739** [eclipse/paho.mqtt.python#162]
i want to set also the path of the broker(<host>/<path>), how can i do this?
examples: 
/iot.eclipse.org:80/ws
ec2-54-234--122.compute-1.amazonaws.com/eyJraWQiO...

**Comment by PierreF** [comment]
You want to change the URL path when connecting to a broker over Websocket ?

Currently the "/mqtt" path is hardcoded, but it could indeed be a good feature to add.

**Comment by eduard739** [comment]
yea. I found it in the WS wrapper class and changed it, thanks
