### ISSUE TITLE
Proposal: Drop support for Python 3.2

### ISSUE THREAD

**Issue by Nzbuu** [eclipse/paho.mqtt.python#163]
Python 3.2 is not supported by the standard Python packaging tools, such as pip, setuptools and virtualenv since Jan 2016. Can we drop support too?

The argument in [pypa-dev mailing list](https://groups.google.com/forum/#!msg/pypa-dev/Ef0PF2ZGAv0/hrO4BHkOBQAJ) was that there is minimal Python 3.2 usage in April 2015.

Perhaps more importantly, Python 3.2 was officially end-of-life in February 2016 (See https://www.python.org/dev/peps/pep-0392/)

See:

* https://pypi.python.org/pypi/pip
* https://pypi.python.org/pypi/setuptools
* https://pypi.python.org/pypi/virtualenv

**Comment by PierreF** [comment]
One drawback is that Debian 7 (wheezy, currently oldstable) use Python 3.2 and is supported (by the LTS support) up to May 2018.
Is there any feature that fail to work on Python 3.2 ? You referenced this issue only from test and fixed them for Python 3.2.

I would say that if it don't require too much effort, we should try to keep support for Python 3.2.

**Comment by swails** [comment]
Arguments against 3.2 support:

1. Security fixes ended over a year ago at least: https://www.python.org/dev/peps/pep-0392/
2. http://www.curiousefficiency.org/posts/2015/04/stop-supporting-python26.html

The first is a bit more worrying for MQTT, in my opinion, as it is inherently a protocol for communicating information to/from anywhere. The second is about 2.6 specifically, but the arguments still apply to 3.2.

**Comment by swails** [comment]
If paho incidentally works in Python 3.2, that's fine(ish). But I think explicitly supporting a EOLed platform with known and publicly documented security vulnerabilities doesn't make sense. And I don't think it's worth even a nominal effort to keep supporting it. Just my opinion.

**Comment by Nzbuu** [comment]
**TL:DR;** I think that my preference is to say that the develop branch is preparing for Paho 2.x since it may have breaking changes, and that Paho 2.x will only releases of Python that are not going to be EOL on the target release date.

Paho 1.2.x will always run on Python 3.2, just as pip 7.1.2 does. The question is whether it's worth the extra effort to keep Paho 2.x running on Python 3.2 (or Python 2.6, which has been EOL since October 2013, or Python 3.3, for that matter, which goes EOL in September 2017, which is quite soon). If the Python project is not releasing bug fixes for these releases, then I don't think that any community project should be going out of its way to support them.

Each of these EOL releases presents extra work in making things backwards compatible and means that new language and library features can't be used. It took qutie a bit of extra work to make the new testing things that I've been working on work in Python 3.2, mostly because I wanted to know how to do it and I really want to be using a proper unit testing framework, but this will only get worse when the other tools and libraries drop support for Python 2.6 and 3.3 as well.

I would also say that it's Debian's decision to LTS Python 3.2 in wheezy, and that this project should not feel obliged to follow. The developers of pip, which is core to the Python ecosystem, did not feel the need to continue to support it, and they probably have more commerical support.

**Comment by ralight** [comment]
I'm inclined to say that for a breaking version of Paho it's a reasonable thing to drop support where we want. I'd vote to drop support for 3.2 and 3.3.

Paho Python doesn't have any packages in Debian Wheezy, we aren't tied to it.

**Comment by PierreF** [comment]
Ok, let's go with fixes branch that keep current supported version and develop branch that include breaking change and no longer support 2.6, 3.2 and 3.3.

**Comment by Nzbuu** [comment]
Great. Thanks!

**Comment by PierreF** [comment]
Push commit (d32be16) to remove support for Python 2.6, 3.2 and 3.4 on develop.
