### ISSUE TITLE
paho.mqtt.publish  multiple function will throw exception if target token list is empty

### ISSUE THREAD

**Issue by jpwsutton** [eclipse/paho.mqtt.python#17]
migrated from Bugzilla [#461574](https://bugs.eclipse.org/bugs/show_bug.cgi?id=461574)
status UNCONFIRMED severity *major* in component *MQTT-Python* for *1.1*
Reported in version *1.1* on platform *PC*
Assigned to: Roger Light

On 2015-03-06 06:08:59 -0500, henry john wrote:

> def _do_publish(c):
>     """Internal function"""
>     m = c._userdata[0]
>     c._userdata = c._userdata[1:]   # throw exception is userdata contains only one element.
>     if type(m) is dict:
>         topic = m['topic']
>         try:
>             payload = m['payload']
>         except KeyError:
>             payload = None
>         try:
>             qos = m['qos']
>         except KeyError:
>             qos = 0
>         try:
>             retain = m['retain']
>         except KeyError:
>             retain = False
>     elif type(m) is tuple:
>         (topic, payload, qos, retain) = m
>     else:
>         raise ValueError('message must be a dict or a tuple')
> 
>     c.publish(topic, payload, qos, retain)
> 
> 
> 
> 
> 
> bug fix version:
> def _do_publish(c):
>     """Internal function"""
>     if not c._userdata:
>         c.disconnect()
>         return
>     m = c._userdata.pop()
>     if type(m) is dict:
>         topic = m['topic']
>         try:
>             payload = m['payload']
>         except KeyError:
>             payload = None
>         try:
>             qos = m['qos']
>         except KeyError:
>             qos = 0
>         try:
>             retain = m['retain']
>         except KeyError:
>             retain = False
>     elif type(m) is tuple:
>         (topic, payload, qos, retain) = m
>     else:
>         raise ValueError('message must be a dict or a tuple')
> 
>     c.publish(topic, payload, qos, retain)
> 
> 
> advise:  To get more readability, the code should better write with the pep8  style guide.

**Comment by ralight** [comment]
This is now fixed.
