### ISSUE TITLE
Client destructor/ disconnect() does not close sockets

### ISSUE THREAD

**Issue by flatballer** [eclipse/paho.mqtt.python#170]
The garbage collection of Client objects produces warnings such as:
sys:1: ResourceWarning: unclosed <socket.socket fd=31, family=AddressFamily.AF_INET, type=SocketKind.SOCK_STREAM, proto=0, laddr=('127.0.0.1', 35498)>

this warning can be avoided by closing the sockets in Client's __del__() method:
def __del__(self):
    self._sockpairR.close()
    self._sockpairW.close()

**Comment by pat1** [comment]
For me is solved adding reinitialise() after disconnect().

**Comment by riccardoch** [comment]
It's really strange the absence of a **close** method.
If you need to close completely the connection you can do:

    def close(client):
        if client._ssl:
            client._ssl.close()
            client._ssl = None
            client._sock = None
        elif client._sock:
            client._sock.close()
            client._sock = None
        if client._sockpairR:
            client._sockpairR.close()
        if client._sockpairW:
            client._sockpairW.close()

**Comment by PierreF** [comment]
I've a bit forgotten this issue. While I agree that paho should close its objects and not rely on garbage collector, is it currently an real issue or just a warning for you ? (this question is to help prioritizing issues)

**Comment by pat1** [comment]
The garbage collector (inserting socket close in __del__ ) do not work for me; is possible there is some reference that forbid  this.
For me is a bug and I have an application that crash after some time of work.
Solved using code in reinitialise() as reported by @riccardoch .

**Comment by keomabrun** [comment]
It is a real issue for me. I have an app where the MQTT client connects and disconnects at lot. Every time it creates two sockets that are never closed. After reaching my system limit of number of socket per process, my app crashes with a `Too many open files` error.

**Comment by pietrodn** [comment]
This issue is fixed by PR #325, which has been merged in the `develop` branch.
I think it can be closed.

**Comment by PierreF** [comment]
PR #325 released in version 1.4.0
