### ISSUE TITLE
Current PAHO MQTT client does not support SSL context 

### ISSUE THREAD

**Issue by cah-sachin** [eclipse/paho.mqtt.python#185]
Hello,

For our project need we need to add ALPN support to existing paho client. This is not enabled in 1.1 version as complete SSL context variable is missing from client.py ( self._ssl_context )

My questions is, when you guys will be releasing paho mqtt with this support ? I see this support on development branch.

-Sachin

**Comment by swails** [comment]
I believe this has since been released in 1.3.0 (if not 1.2.3).

Can you check this and close the issue if it's resolved?

**Comment by PierreF** [comment]
SNI support was added in the 1.3 release
