### ISSUE TITLE
print_topic in _handle_publish in develop branch

### ISSUE THREAD

**Issue by michaelboulton** [eclipse/paho.mqtt.python#186]
Just a minor thing - in the current develop branch the 'print_topic' variable in _handle_publish is assigned to but never used: 

https://github.com/eclipse/paho.mqtt.python/blob/fdb46b4e40c4c1a8d661ccb9a59b1975e6512db8/src/paho/mqtt/client.py#L2436-L2441

It used to print it out in the log message, but now it just prints the message topic.

master: https://github.com/eclipse/paho.mqtt.python/blob/master/src/paho/mqtt/client.py#L2456

develop: https://github.com/eclipse/paho.mqtt.python/blob/fdb46b4e40c4c1a8d661ccb9a59b1975e6512db8/src/paho/mqtt/client.py#L2455

**Comment by PierreF** [comment]
Commit 6d9ce3a make use of print_topic to (re)fix #75 in develop.
