### ISSUE TITLE
Client doesn't disconnect properly when CONNACK indicates failure

### ISSUE THREAD

**Issue by Nzbuu** [eclipse/paho.mqtt.python#192]
In https://github.com/eclipse/paho.mqtt.python/commit/e0c1a16a1e14392a070f731504285993e169a492, added `client.disconnect()` to callback. But I think this should happen automatically when the CONNACK rc indicates failure.

What do you think?

**Comment by Nzbuu** [comment]
Possibly related to: https://github.com/eclipse/paho.mqtt.python/issues/170

**Comment by PierreF** [comment]
Yes and no :)
Client should reconnect itself if we don't call disconnect(), that why I've added it.
That being said, it may be better to not explicitly disconnect and be sure it disconnect by itself. Committed this change.
