### ISSUE TITLE
on_message call back is not getting called while on_connect is getting called.

### ISSUE THREAD

**Issue by varsha33** [eclipse/paho.mqtt.python#200]
# This is the Publisher
import paho.mqtt.client as mqtt
client = mqtt.Client()
client.connect("localhost",1883,60)
client.publish("topic/test","hi",0,True);

# This is the subscriber
import paho.mqtt.client as mqtt
def on_connect(client,userdata,flags,rc): 
	print("Connected with result code"+" "+str(rc))
	client.subscribe("topic/test")
def on_message(client,userdata,message):
	print(msg.topic+" "str(msg.payload))
client = mqtt.Client()
client.on_message = on_message
client.on_connect = on_connect
client.connect("localhost",1883)
client.loop_forever()

My hivemq broker message log gives this when its been published
2017-06-12 07:05:37,727 INFO  - Client paho/765579CDED21EA00DC connected
My hivemq broker message log gives this when its been subscribed 
2017-06-12 07:05:37,774 INFO  - Subscribe from client paho/765579CDED21EA00DC received: topic/test QoS: 0

But I get only the following message on my terminal
Connected with result code 0 
It fails to print (msg.topic+" "str(msg.payload)). Please help me resolve this issue

**Comment by ralight** [comment]
Your hivemq log doesn't show any messages being received, so are you sure that any have been sent?

**Comment by PierreF** [comment]
If your published code is complete, it's missing few points:
* You never start the client, with loop_forever, loop_start or a manually managed loop
* Even if you start the loop, with QoS=0 you need to ensure the client is connected before publishing the message. For example using on_connect callback. Failing to do so will result in message being discarded.

If your use-case is to connect, send one message and disconnect, look at publish helper that handle all those details for you.

**Comment by varsha33** [comment]
@PierreF . That solved the issue. I changed my publisher code and it worked. Thank you
