### ISSUE TITLE
Transaction Handling When Receiving QoS2 Messages

### ISSUE THREAD

**Issue by samba2** [eclipse/paho.mqtt.python#201]
We use MQTT to broadcast live status events. Since we need those events to be submitted exactly once we use QoS2. While implementing client logic we were wondering what would happen if the client application crashes. Since the message was delivered, the message is lost. Next time the (now hopefully fixed) client subscribes the next message will be sent (if persisted). The old message was lost in the client crash.

[Here is a sequence diagram of the client message getting lost]( https://www.planttext.com/plantuml/img/TL51ReCm4BplAqRqckRGOmvL0a9gLD8GGi-LGnomQcoqDbNvVGr1LQGsFgqyCxipksld1Vk-rKJ6UWdx9Hb9jatVoWKsUOw7JDMDZtKlAUcPfV43LDjfsOPIU6ND4jiBejs0HAlm5w5YuHhfu1k9LZedQWdbeAtpIo9fpXX7ZPLNeLkqEvGbOhQVaYC8XxZOlwO5dUptRLj2U5qmgohL2UDdtHL5fauiU9ZqL_j_-PkkqwgQF2EpjQecTWWvUGhZY4JlhUdRasIwki3ZyzmFA-JlSROzlk1WZqyq_mPyPavuaIPtb4MQtT4a-rr-0urRNw4IMYjJ8xBcOrvYX4jlgj4-ZPnVwfG5JSWYcIql_Zi6qJg437V-0G00)

Using the retained message is no option is our use case: other clients connecting to the same topic are expecting to see the events coming in live. If there are currently no events than it is fine and wanted to just sit there waiting for the next event to occur.

What we like to do is something like this:
After the client received the PUBLISH, it sends back a PUBREC and then starts processing the message with a yet non existing callback function. I called it *on_publish_received*. This callback contains the application logic. If it fails (Exception) the MQTT client does *not* respond to the PUBREL package received in the meantime. This would lead to an incomplete QoS2 transaction effectifly marking the message as "not transmitted successfully" on the broker. 
The next time we connect back with the fixed logic, the broker presents the old message again (persisted session).

[Here is the sequence diagram for the intended flow.](https://www.planttext.com/plantuml/img/TLB1Rjim3BthAmZtckMmOmz3co30WhbhccQt0GMjC3OHMN8bEcd-lhJi1W666GOicNoFJ-_f8Gb6wLjdZ0z244uKOLckLxztCtZSRE2kvBgHXUl9hBsGt-iBt7QEMlA2mi7FuR7h7Dky0HTgjY1uf0ITGqjGaPo9F1mu9W63If381lr8H9zQJca0TiXn3cPzWEBf0jQnyXTW8wQ6qWoaKQOOZgfF8Ykv1EZwod5gSgsbbB0cm1hPW_B5OOOdAtCpQ1wEPtGbB1UTyBBRmIBJ5O095jldNwkjgS97dhuSfnlGfrE3s7A7NYRSM8MIguZnal6ZPV_stpfJ3ixaRZKsQz9nnc0lmVTjHT6CAk3RZuaFxc7pPr6kNt_2ItZzRgQ_MfywStsxMjvKXj3kmQ9px6lmT8OY-BV9gRT89qjyedsHMogqHpCWhi0i4XeLIJ66EBkruokC_-ZShigRobNX5De-Q6OQmf3Be00SwcqOOL_XpU2llmPvPkVqxi1xJptjuH2YGfFQfkSova4NUcq_0G00)

Question: Is there a trick to do this or something similar witth Python Paho?

Thanks,

MAik

**Comment by PierreF** [comment]
Hi,

I'm not aware of any way to achieve this kind of "transaction" using Python Paho. It would indeed probably require change in the Paho code to add an additional callback like the one you proposed.

**Comment by MattBrittan** [comment]
I'm going to close this because of it's age and the fact that the links no longer function. The long term fix would probably require adding persistent session storage (which is recorded as a [known limitation](https://github.com/eclipse/paho.mqtt.python#known-limitations)). Note that the hypothetical solution has an issue; if the broker has received the `PUBREC` then it will only resend a `PUBREL` upon reconnection (not the original publish).
