### ISSUE TITLE
help please ! 

### ISSUE THREAD

**Issue by YousseMes** [eclipse/paho.mqtt.python#203]
I am a beginner for mqtt !
And the examples that you have done help me to learn programming with pytthon 
so now i can make some pub&sub but i have a problème
 if i receive data from some publisher  i want make publish automatically 
for example if a receive "on" from topic1 send "off" to topic2 
please thear's no example for that hope you can help me thank you .

**Comment by swails** [comment]
This test script does precisely that using the ``test.mosquitto.org`` mosquitto broker:

```python
from paho.mqtt.client import Client

# Create the client. Don't forget to do anything else you need to do, like
# set TLS parameters for a secured connection, etc.
client = Client()

# Define the callback you want to use
def topic_callback(client, userdata, message):
    """ The callback that will be called automatically whenever posted to the target topic

    Parameters
    ----------
    client : Client
        The MQTT Client object that received the message
    userdata : object
        An arbitrary object passed back to you
    message : MQTTMessage
        The message sent through MQTT
    """
    if message.payload.decode('utf-8') == 'on':
        client.publish('topic2', payload='off')

# Add the callback to topic1
client.message_callback_add('topic1', topic_callback)

# Connect to whatever broker you want to use and loop connect
client.connect('test.mosquitto.org', port=1883)

client.subscribe('topic1')

client.loop_forever()
```

Note that this is only to demonstrate how to use the API here, *not* a recommended way to design a program.  I'd highly recommend consulting the API documentation in the top-level README file and try playing around with it a bit.

Good luck!

**Comment by YousseMes** [comment]
Thank you soooo much 🥇
