### ISSUE TITLE
Client constructor does not create a random client identifier when not using MQTTv31 protocol

### ISSUE THREAD

**Issue by marschal** [eclipse/paho.mqtt.python#209]
This issue reffers to the Client constructor where the client id should be generated. After update from paho-mqtt 1.2 to 1.3 i run in tho the issue that leaving the clilent_id parameter empty did not generated an unique client id for me.

I'm not into the different protocol versions of mqtt, but the reffered if statement should simply return an empty client_id hence this won't be unique in an M2M scenario.

[/src/paho/mqtt/client.py](https://github.com/eclipse/paho.mqtt.python/blob/f53da37ce6305f4be081106c46942112465f52be/src/paho/mqtt/client.py#L504-L508)

**Comment by PierreF** [comment]
This may not be an issue, as with MQTT 3.1.1 an empty client_id mean that broker may generate an random client id for you.
I'm assuming that you broker does not do that (specification say MAY, broker don't have to do that). Out of curiosity (and to better prioritize the issue) with which broker you have this issue ?

**Comment by marschal** [comment]
This issue is popped up with the java moquette mqtt broker

**Comment by PierreF** [comment]
Committed a fix for this issue:
* paho will still try an empty client_id by default with MQTT 3.1.1.
* but if the connect fail with rejected identifier (and client_id is empty), an random one is generated.

With this fix, broker that support empty client id will use it, and for other broker a random one will be generated on client side.
