### ISSUE TITLE
Improve documentation

### ISSUE THREAD

**Issue by PierreF** [eclipse/paho.mqtt.python#210]
There is multiple issue with people not used paho-mqtt as expected and losing message especially the fact the publish is asynchronous: the return of publish() does not guaranteed that message is effectively  published.

This occurred twice last month on the mailing list.

The documentation should insists that publish is asynchronous (you need to wait for on_publish callback). Also publish(qos=0) on not yet connected session lost the message (here also, connect() is asynchronous, you need to wait for on_connect). Probably reinforce suggestion to using publish helper.

Adding a example of publish loop in the getting started may also be useful to show recommended publishing loop.

**Comment by ralight** [comment]
I expect that

    msginfo = client.publish(...)
    msginfo.wait_for_publish()

could do with more prominence in the documentation/examples as well. The publish helper is great, but is only suited for a fairly limited set of programs.

**Comment by PierreF** [comment]
Updated documentation to:
* explicitly remain that calling disconnect() will not wait for queued message to be sent
* Document MQTTMessageInfo and wait_for_publish()

This is committed on fixes, not yet on master.
