### ISSUE TITLE
Documentation is out of date on Eclipse.org

### ISSUE THREAD

**Issue by samjetski** [eclipse/paho.mqtt.python#211]
The documentation is here: https://eclipse.org/paho/clients/python/docs/

It doesn't appear to have been updated recently, and is out of sync with this repo.

For example, it still shows the v1.2 `on_connect()` callback signature: https://eclipse.org/paho/clients/python/docs/#callbacks

It is also still full of links to the old Git repo (git.eclipse.org).

Is there a way to have this automatically updated in future?

**Comment by PierreF** [comment]
@ralight is there any particular reason to have a copy of the documentation on eclipse.org ? Isn't github page enough ?
I would opt with removing the documentation page on eclipse.org and only use github page.

**Comment by ralight** [comment]
@PierreF I think that is something that you'd have to ask the project leads about :)

**Comment by ralight** [comment]
It is possible to at least semi automate it.

**Comment by PierreF** [comment]
Documentation updated manually (rst2html and copy/paste)
