### ISSUE TITLE
on_message only gets called if no message callback has been defined

### ISSUE THREAD

**Issue by MrLeeh** [eclipse/paho.mqtt.python#212]
For the on_message callback the documentation says: "This callback will be called for every message received."

That is not true. If a topic-specific callback has been defined via `message_callback_add()` the `on_message` callback will not be called anymore. This is clearly not the behavior described in the documentation.

I suggest fixing this by changing the _handle_on_message method as follows:

    def _handle_on_message(self, message):
        matched = False
        with self._callback_mutex:
            try:
                topic = message.topic
            except UnicodeDecodeError:
                topic = None

            if topic is not None:
                for callback in self._on_message_filtered.iter_match(message.topic):
                    with self._in_callback:
                        callback(self, self._userdata, message)
                    matched = True

            if self.on_message:   # <<< remove matched == False
                with self._in_callback:
                    self.on_message(self, self._userdata, message)

**Comment by PierreF** [comment]
This behavior was documented on message_callback_add:
> only messages that do not match a subscription specific filter will be passed to the ``on_message`` callback

So indeed documentation is wrong for the on_message callback, but only if message_callback_add is used (so user had a change to see the contradiction, test the behavior and adapt to real behavior).

For those reason I prefer to keep current behavior and clarify documentation on this subject.

**Comment by PierreF** [comment]
Clarify documentation, which now state in both on_message() and message_callback_add() that the on_message callback is only used if no other callback processed the message.

Also added tests to check this behavior. 

Committed on fixes branch, not yet on master.
