### ISSUE TITLE
Deadlock when using an external mutex before calling publish and inside on_publish

### ISSUE THREAD

**Issue by amrbekhit** [eclipse/paho.mqtt.python#226]
Hello all,

I have code that basically looks like the following:

```
publish_lock = threading.Lock()

def tx_thread:
	while True:
		time.sleep(SOME_DELAY)
		
		messages = get_messages_from_database()
		
		for msg in messages:
			with publish_lock:
				result, mqtt_id = mqtt_client.publish(msg.topic, msg.payload, msg.QOS)
				
				mark_message_as_transmitted(msg, mqtt_id)
				
				
				
def on_publish(client, userdata, mid):
	with publish_lock:
		remove_message_from_database(mid)
```
		
Explanation:

I have a mysql database where I store messages to be transmitted in a table. The tx_thread regularly polls the database and pulls out some of the messages, whereby it publishes them and then updates their entry in the database with the mqtt_id variable that the publish method returns. When the on_publish callback is called with that message's ID, I know that the message has been transmitted successfully and thus remove it from the database.

You'll notice that I'm using a Lock (publish_lock) to make sure that the publish and database update commands are atomic. If I don't do this, there is a possiblity that after I publish the message, but before I update the database, the on_publish callback gets called and tries to delete the message from the database but can't because the mqtt_id hasn't been assigned to the message yet. However, it seems that due to some other internal mutexes in the mqtt client library, I sometimes get the following deadlock condition:

* tx_thread: acquire publish_lock
* on_publish: callback get's called. Some internal mutex gets acquired.
* on_publish: callback attempts to acquire publish_lock but can't, because it is held by tx_thread. Waits.
* tx_thread: attempts to call publish. publish attempts to acquire the same internal mutex mentioned previously but can't because it is held by on_publish

Any thoughts as to how I can go around this problem? Is this potentially an issue in the library that needs to be addressed? The benefit of the on_publish callback is that it notifies you when a message has been successfully published, but in order to do that I need to record the mqtt_id somewhere *before* on_publish is called and this needs to be atomic.

**Comment by imZack** [comment]
`on_publish` is only ensure your message had been sent to broker not clients.
If you want to make sure messages are received in ordered I think you have to add something in payload such as timestamp or sequence id.

**Comment by imZack** [comment]
How about using Event instead of Lock

```
publish_event = threading.Event()
publish_event.set()

def tx_thread:
  while True:
    time.sleep(SOME_DELAY)

    messages = get_messages_from_database()

    for msg in messages:
      publish_event.wait()
      publish_event.clear()
      result, mqtt_id = mqtt_client.publish(msg.topic, msg.payload, msg.QOS)
      mark_message_as_transmitted(msg, mqtt_id)

def on_publish(client, userdata, mid):
  remove_message_from_database(mid)
  publish_event.set()
```

**Comment by amrbekhit** [comment]
@imZack Thanks for the suggestion - in the example you gave, every publish waits indefinitely until the on_publish callback is called, which may be very slow (or not at all) if the connection is poor.

What I ended up doing in the end was having the on_publish callback populate a separate list with the id's of the messages that were successfully sent. In tx_thread, I regularly check that list against the database and delete those messages that have been sent.

The reason why I'm wondering whether it's worth looking at the design is because it seems normal that after publish is called, you're going to want to assign that ID to the message, but also want to ensure that is done *before* on_publish is called. In the end, the solution I'm currently using works, but adds an extra layer of complexity in my opinion and the original method using a mutex seemed like the "obvious" solution to me.

**Comment by PierreF** [comment]
IIRC, with QoS = 0, your code will always deadlock, because on_publish callback it called immediately (e.g. in the call graph of publish() method).
Are you sending QoS = 0 message ?

**Comment by amrbekhit** [comment]
No I'm using QoS 2, which is probably why I only see the problem occasionally.

**Comment by MattBrittan** [comment]
I'm going to close this due to age/inactivity and the fact that issue #603 (which appears very similar) was fixed. Please feel free to reopen if you are still encountering the issue. This is part of a general project to clean-up issues (which should make it simpler to identify priorities going forward).
