### ISSUE TITLE
Using CBOR(Concise Binary Object Representation) MQTT compressed format for time series.

### ISSUE THREAD

**Issue by hossam92** [eclipse/paho.mqtt.python#232]
I'm trying to use CBOR to send the data instead of sending JSON

```
    data_json = "[#array of dicts]"
    data_json = json.loads(data_json)
    data_json = cbor2.dumps(data_json)
    #subscribing to a event
    client.subscribe(""+str(user)+"/tasks/json")
    # client.subscribe(""+str(user)+"/messages/ts")

    client.publish(""+str(user)+"/messages/ts", data_json, 0)

```
but this doesn't work no data is being sent

#! cbor2.dumps return bytes

**Comment by PierreF** [comment]
Paho support sending binary payload, so even if cbor2 is binary, it should be supported.
Is your code working when sending json data ?

**Comment by hossam92** [comment]
Yes it does, when I change the Topic to ""+str(user)+"/messages/json" and do nothing to data_json string it works fine but I need to use CBOR instead

**Comment by PierreF** [comment]
In this case the issue is not the payload being JSON or CBOR, but the topic on which you publish.

Did you updated topic on both published and subscriber ? (in your sample code, the correct subscribe is commented)

**Comment by hossam92** [comment]
Yes PierreF I tried both, both didn't work.

**Comment by PierreF** [comment]
I can't reproduce this issue. I'll need more information or a working code that exhibit this issue.

The following code do sent and receive CBOR data:
```
import paho.mqtt.client
import time
import cbor2

def on_message(client, userdata, message):
    print("Got message: %r" % message.payload)

data_json = [{"borker": "mosquitto"}, {"python version": 3}]
data_json = cbor2.dumps(data_json)
client = paho.mqtt.client.Client()
client.connect("localhost", port=1884)
client.on_message = on_message
client.loop_start()
client.subscribe("/tasks/json")
time.sleep(1)  # wait for subscription to be acknowledged
client.publish("/tasks/json", data_json, 0)
```

Tested with both Python 2 and 3.

**Comment by hossam92** [comment]
how does this even work when you publish on topic "/tasks/json"
According to MQTT CBOR refs you should publish on MQTT topic: {IMEI or SN}/messages/ts (for Time Series)
https://doc.airvantage.net/av/reference/hardware/protocols/mqtt-ts/

here is the working code
https://codeshare.io/axgA3k

**Comment by PierreF** [comment]
MQTT does not specify any topic on which publish any data. My example is limited to MQTT.
Your reference is MQTT to talk with AirVantage. It's the same as HTTP versus an API over HTTP.

I'm able to run you full code (against a local broker without authentication) by change one thing: do not disconnect in on_publish callback but instead on on_message callback. By disconnecting in on_publish callback, you close your connection immediately after publishing the message (e.g. before the broker had time to sent the message back to you).

Also be aware of the following possible issue with a non-local broker with authentication:
* the time.sleep(1) in the callback will not really help. paho is single-threaded, so you are blocking to processing thread anyway.
* You should only subscribe & publish in on_connect if rc==0. For example on_connect could be called with rc=CONNACK_REFUSED_BAD_USERNAME_PASSWORD.
* If you expect the message to come back to you, you should only inside the on_subscribe callback. The broker could deny your subscription

For your information, if your intention is just to connect, send some messages and disconnect, there is a publish helper that is easier to use.

**Comment by hossam92** [comment]
Yes PierreF I only want to connect and send msgs then disconnect.
When I followed what you say the connection didn't disconnect because I receive nothing so on_message is never called. And the data still not being sent on AirVantage.

Please keep in mind that the code works fine when I send JSON the only problem that happens is when I send bytes.

**Comment by PierreF** [comment]
Are your on_subscribe callback called ? If not, it's AirVantage that deny your subscription.

Could you try against another broker ? test.mosquitto.org on port 1883 could be used for this. Remember to remove credentials as this broker does not need authentication.

**Comment by hossam92** [comment]
No it's not called but why it works when I send json ?
on_subscribe doesn't get called but it sends data successfully

**Comment by hossam92** [comment]
So Pierre no hope for me?

**Comment by hossam92** [comment]
on_subscribe runs if I don't disconnect in on_publish but it doesn't make any difference.
When I sending the JSON on_subscribe doesn't get called yet data is sent.

**Comment by PierreF** [comment]
>  When I sending the JSON on_subscribe doesn't get called yet data is sent.

This seems very strange. AFAIK MQTT *require* that message are ordered. That means you can NOT receive a message before the subscription acknowledgement. Which seems to indicate your broker does not follow the standard.

If "data is sent" mean AirVantage get the data, that looks like a bug in your provider that does not process CBOR but does for JSON.

For me this bug looks like your provider does not works as you expect and you should look with them how to solve your issue.

If you still believe this is a paho issue, please reproduce this bug against another broker (test.mosquitto.org for example).

**Comment by hossam92** [comment]
how to test if the data is being sent or not to test.mosquitto.org ?

**Comment by PierreF** [comment]
You will need to subscribe on the topic to see the message you just sent.

If using your code which subscribe and publish, receiving the message in your on_message callback means that message was sent (and broker re-sent it to you).

If you go with the publish helper, you can not subscribe with the same program. In this case, the easiest solution is to run another program using the subscriber helper. While the subscriber is running, launch the publisher, and see the message doing a round-trip.

**Comment by hossam92** [comment]
Really thank you Pierre, I got it all now thanks to you. I didn't solve the problem yet but know I see it better. 
I'll contact AirVantage.
