### ISSUE TITLE
Messages don't get published right away flushed after on_messages returns

### ISSUE THREAD

**Issue by steviethecat** [eclipse/paho.mqtt.python#234]
From within my `on_message` callback, I am trying to publish 2 messages, with a 5 second delay in between them. The `on_log` callback shows that the messages get send out in time, but from a subscriber point of view this is not the case.  It seems that the messages get flushed only when the on_message callback returns. 

The code from the subscribers point of view (with timestamps):

```
2017-09-29 13:05:38.718 tasks/mqttpi x
2017-09-29 13:05:43.794 received A
2017-09-29 13:05:43.841 received B
```

And from the calling python script:

```
<paho.mqtt.client.Client object at 0x76a12910>
2017-09-29 13:05:32.515228 Received CONNACK (0, 0)
2017-09-29 13:05:32.536386 Received SUBACK
2017-09-29 13:05:38.750625 Received PUBLISH (d0, q0, r0, m0), 'tasks/mqttpi', ...  (1 bytes)
message received  x
message topic= tasks/mqttpi
message qos= 0
message retain flag= 0
2017-09-29 13:05:38.777709 Sending PUBLISH (d0, q0, r0, m2), 'b'received'', ... (1 bytes)
2017-09-29 13:05:43.798801 Sending PUBLISH (d0, q0, r0, m3), 'b'received'', ... (1 bytes)
^C
keyboard interrupt
```

The `on_log` callback clearly shows that the messages get send out 5 seconds apart (13:05.38 and 13:05.43), but they get received at 13:05.43. 

The script that I use to test is: 

```
#!/usr/bin/python3

import paho.mqtt.client as mqtt 
import time
import datetime
import os
import socket
import pprint

def on_log(client, userdata, level, buf):
    print(datetime.datetime.now(), buf)

def on_message(client, userdata, message):
    print("message received " ,str(message.payload.decode("utf-8")))
    print("message topic=",message.topic)
    print("message qos=",message.qos)
    print("message retain flag=",message.retain)
    client.publish("received", "A")
    time.sleep(5)
    client.publish("received", "B")

broker_address="localhost" 
hostname = socket.gethostname()
client = mqtt.Client( hostname )
client.connect(broker_address)
client.on_log=on_log
pprint.pprint(client)

client.on_message=on_message
client.loop_start();
client.subscribe( "tasks/" + hostname ); 

try:
    while True:
        pass

except KeyboardInterrupt:
    print('\n\rkeyboard interrupt')

client.loop_stop();
```

If I replace the `client.publish` calls by `subprocess.call("mosquitto_pub -h 10.240.242.153 -t 'received' -m 'A'", shell=True)`, the messages do get out directly. Even though that works, that is just bypassing the paho.mqtt library and does not feel good.

**Comment by PierreF** [comment]
Hi,
your issue is that you are blocking the paho.mqtt library by doing a sleep inside the callback. The library is single threaded, doing such sleep will block all operation (including sending packet on the network).

If you really need to wait 5 seconds between two messages, you need to do that sleep outside the callback. Either spawning a thread from the callback or notifying another thread that is allowed to sleep.

**Comment by steviethecat** [comment]
I did not know that, thank you. I've rewritten the code to send messages out side of the callback using a global, which works as expected. Though I am not thrilled about using globals. 

One other thing I noticed, but which is obviously logical, is that the `client_id` needs to be unique. 

For reference, the complete working script is now:

```
#!/usr/bin/python3

import paho.mqtt.client as mqtt 
import time
import datetime
import os
import socket

def on_log(client, userdata, level, buf):
    print(datetime.datetime.now(), buf)

def on_message(client, userdata, message):
    global publish
    print("message received " ,str(message.payload.decode("utf-8")))
    print("message topic=",message.topic)
    print("message qos=",message.qos)
    print("message retain flag=",message.retain)
    publish = 1

broker_address="localhost" 
hostname = socket.gethostname()
client = mqtt.Client( client_id = hostname + str(os.getpid()) )
client.connect(broker_address)
client.on_log=on_log

client.on_message=on_message
client.loop_start();
client.subscribe( "tasks/" + hostname ); 
publish = 0

try:
    while True:
        if publish == 1:
            print("time to start testing")
            client.publish("received", "A")
            time.sleep(5)
            client.publish("received", "B")
            publish = 0

except KeyboardInterrupt:
    print('\n\rkeyboard interrupt')

client.loop_stop();
```
