### ISSUE TITLE
__dict__ function addition in paho client library

### ISSUE THREAD

**Issue by hmchaitra** [eclipse/paho.mqtt.python#237]
in paho client __dict__ fuction is not defined, if a nonzero clientid is given the the server has to assign a new clienttid for client. how to get this client id value from client.
if __dict__ function is defined we can get a class instance variable(clientid is also a  instance vaiable of class Client)

**Comment by PierreF** [comment]
Hi,
I don't understand your issue. If a non-zero client id is given... it's that client-id that must be used by both client and server.
Or you wanted to said "if a ZERO [length] clientid is given, the server has to assign a new clientid", and then want to retrieve this client id, then this is not possible. The server don't send the server-side generated clientid so paho never get it.
Finally if you want to get the client id in the case when you provided a zero length clientid and the paho library generated the client id (e.g. if using MQTT 3.1 - not 3.1.1 - or if broker don't support server-side generated clientid), then I would argue that you should not provide a zero length clientid.

If knowing the clientid is important to you, why don't you provide the clientid when creating client ? Could you provide a rational on why doing so is not adapted to your situation ?

**Comment by hmchaitra** [comment]
Hi,
I want to test a scenario wherin from client zero-byte clientid is provided and the server allocates a clientid for such special case,so i thaught when server assign  a clientid  the id gets updated at the paho client instance variable  will that happen or not??

**Comment by PierreF** [comment]
No, if the server generate the clientid then it is not send to client.

**Comment by hmchaitra** [comment]
thank you for your time.
Thanks.

**Comment by ralight** [comment]
I'm closing this because it is solved, but as a note MQTT v5 does allow clients to find out their server assigned client ids.
