### ISSUE TITLE
payload of publish packet  is  UTF-8 encoded??

### ISSUE THREAD

**Issue by hmchaitra** [eclipse/paho.mqtt.python#239]
Hi,
i am sending a PUBLISH packet with payload "abc\0". the server is accepting this payload, if anyting  UTF-8 encoding NULL is sent the server MUST disconnect client.is payload not UTF-8 encoded??in specification its mentioned all strings are UTF-8 encoded.

if i send PUBLISH with topic "abc\0" it will disconnect client as UTF-8 cannot have null encodings.

**Comment by joernheissler** [comment]
Publish payload has no encoding, it's bytes. Not strings, not UTF-8. Bytes. Therefore "\x00" is acceptable.

"\x00" is also valid UTF-8. Non-Valid UTF-8 would e.g. be '\xFF'.
But MQTT specifies in Section 1.5.3 that the null character is invalid.

I see no issue here.

**Comment by hmchaitra** [comment]
MQTT-1.5.3-2 this says no null encodings are allowed, then why do topic name with null encoding leads to rejection?? Text fields in the Control Packets described later are encoded as UTF-8 strings section 1.5.3 the payload is also a text field so it should be UTF-8 encoding???

**Comment by joernheissler** [comment]
> MQTT-1.5.3-2 this says no null encodings are allowed, then why do topic name with null encoding leads to rejection??

Because "MQTT-1.5.3-2 […] says no null encodings are allowed".

> the payload is also a text field

The payload of PUBLISH is not a text field. See section 3.3.3

**Comment by hmchaitra** [comment]
thank you...
