### ISSUE TITLE
How to get access to MQTT Client attribute on callback functions that returns the current subscribed topics?

### ISSUE THREAD

**Issue by Pacheco95** [eclipse/paho.mqtt.python#240]
I'm trying to print log messages on callback functions and I need access to some attributes from Client instance.

Example:

```
def on_subscribe(mqttc, userdata, mid, granted_qos):
    print("Client", mqtt.clientID, "sucessfuly subscribed on topics:", mqtt.topics)
```

How can I get access to these attributes?

Thank you!

**Comment by joernheissler** [comment]
When you invoke subscribe, you pass the topic and get a mid in return. Remember it.
The library won't remember your topics.

The client_id is what you pass on the constructor; this, the lib remembers as _client_id (have a look at the source code!). But it's a private attribute, so you should either add a property to the lib to retrieve it. Or remember it too.

**Comment by Alpha-Phoenix** [comment]
I thought about using private client data to retrieve all this fields, but it looks a bad choice.

**Comment by PierreF** [comment]
There is an issue with client ID. It is possible to not known the value at all. See #237.
About the topic itself, as @joernheissler said, the solution is the keep the mid value when calling subscribe() and matching it in on_subscribe callback. Paho don't keep the value of the topic name.

**Comment by MattBrittan** [comment]
Closing as it looks like an answer was provided (and the issue has been inactive for some time).
