### ISSUE TITLE
Behaviour of the library in case same topic is subscribed with different QoS Level?

### ISSUE THREAD

**Issue by KohliDev** [eclipse/paho.mqtt.python#241]
Would like to understand the behavior of the library if the same topic is subscribed with different QoS level? Will I be subscribed to the same topic (with different QoS Level & Callback) twice or once? If it once will it be the last subscription call and if it is twice then how does unsubscription works without QoS parameter?

```
Subscribe(foo, qos=1, myCallback)
Subscribe(foo, qos=0, myOtherCallback)
Unsubscribe(foo)
```

**Comment by joernheissler** [comment]
Did you check the mqtt specs?
