### ISSUE TITLE
Client.subscribe() does not validate success/failure of actual call

### ISSUE THREAD

**Issue by jeremylink** [eclipse/paho.mqtt.python#242]
If the subscribe call fails (not authorized or ACL rejection), the client does not detect this and always reports the subscription as being successful.

It looks like the only error/failure checking has to do with:
- verifies connectivity to the broker
- verifies the arguments passed to the function are valid

**Comment by joernheissler** [comment]
Did you have a look at the on_subscribe callback? What do you get in granted_qos when the broker rejected your request?

**Comment by jeremylink** [comment]
You're absolutely correct - the on_subscribe callback does return QoS of 128.

I was used to getting the QoS of 128 immediately with the Java client and didn't realize I was getting that in the on_callback.

Thanks for the response.
