### ISSUE TITLE
Connect to client via WebSockets

### ISSUE THREAD

**Issue by vascodmendes** [eclipse/paho.mqtt.python#243]
Hi,
I am having problems connecting to a client via WebSockets.

I am able to do it via mosquitto_pub, however i cannot do it using the paho pyhon.
For instance, this command line code works fine, and the message is sent:
`mosquitto_pub -p 9001 -t TestTopic -m TestMessage`

However doing the same thing using paho python script i get an error:
`import paho.mqtt.publish as publish
publish.single(topic = "TestTopic",payload="TestMessage",port=9001,transport="websockets")`

The issued exception is:
```
Traceback (most recent call last):
  File "MQTT_Example.py", line 2, in <module>
    publish.single(topic = "TestTopic",payload="TestMessage",port=9001,transport="websockets")
  File "/usr/local/lib/python2.7/dist-packages/paho/mqtt/publish.py", line 216, in single
    protocol, transport)
  File "/usr/local/lib/python2.7/dist-packages/paho/mqtt/publish.py", line 152, in multiple
    client.connect(hostname, port, keepalive)
  File "/usr/local/lib/python2.7/dist-packages/paho/mqtt/client.py", line 768, in connect
    return self.reconnect()
  File "/usr/local/lib/python2.7/dist-packages/paho/mqtt/client.py", line 935, in reconnect
    self._websocket_path, self._websocket_extra_headers)
  File "/usr/local/lib/python2.7/dist-packages/paho/mqtt/client.py", line 2706, in __init__
    self._do_handshake(extra_headers)
  File "/usr/local/lib/python2.7/dist-packages/paho/mqtt/client.py", line 2748, in _do_handshake
    byte = self._socket.recv(1)
socket.error: [Errno 104] Connection reset by peer
```

In the Broker i get the following:
```
1509663006: New connection from ::1 on port 9001.
1509663006: Socket error on client <unknown>, disconnecting.

```
Have any idea of what it can be or how can i debug this problem?

Thank you,

Vasco Mendes

**Comment by PierreF** [comment]
Are you sure your server is a websocket one ? I don't think mosquitto_pub support WebSocket, which would means your server is using standard TCP.

**Comment by vascodmendes** [comment]
Hello,
I was not sure before, but i made some tests and i can confirm that it is running on por 9001 webockets.
I know that because my javascript page is connecting using javascript.paho to connect to the broker via websockets, and it is working. I can publish and subscribe via paho.javascript to the mqtt broker.

However, when executing the code from my python script i get an error:

`Traceback (most recent call last):
  File "simpleWebsockets.py", line 31, in <module>
    client1.connect(broker,port)           #establish connection
  File "/usr/local/lib/python2.7/dist-packages/paho/mqtt/client.py", line 768, in connect
    return self.reconnect()
  File "/usr/local/lib/python2.7/dist-packages/paho/mqtt/client.py", line 935, in reconnect
    self._websocket_path, self._websocket_extra_headers)
  File "/usr/local/lib/python2.7/dist-packages/paho/mqtt/client.py", line 2706, in __init__
    self._do_handshake(extra_headers)
  File "/usr/local/lib/python2.7/dist-packages/paho/mqtt/client.py", line 2786, in _do_handshake
    raise WebsocketConnectionError("WebSocket handshake error")
paho.mqtt.client.WebsocketConnectionError: WebSocket handshake error
`
From the broker side, i get this error:
`1509919618: Socket error on client MQQTT_HomeClient, disconnecting.
1509919674: Socket error on client mosqsub|1252-pipplware, disconnecting.`

This is my python code:

`import paho.mqtt.client as paho
import time
broker="192.168.1.73";
port = 9001
sub_topic='VMhouse/Hello'

def on_subscribe(client, userdata, mid, granted_qos):   #create function for callback
   print("subscribed with qos",granted_qos, "\n")
   pass
def on_message(client, userdata, message):
    print("message received  "  ,str(message.payload.decode("utf-8")))
def on_publish(client,userdata,mid):   #create function for callback
   print("data published mid=",mid, "\n")
   pass
def on_disconnect(client, userdata, rc):
   print("client disconnected ok")

def on_connect(client, userdata, flags, rc):
   print("Connection returned result: ")

client= paho.Client("MQQTT_HomeClient",transport='websockets')       #create client object
print("created")

client.on_subscribe = on_subscribe       #assign function to callback
client.on_publish = on_publish        #assign function to callback
client.on_message = on_message        #assign function to callback
client.on_disconnect = on_disconnect
client.on_connect = on_connect

client.connect(broker,port)           #establish connection

print("-------------Connected--------")

client.loop_start()

while 1:
        time.sleep(0.1)
`

**Comment by PierreF** [comment]
Is the TLS settings matching ?
Could you provide more details on the server (software version, configuration if possible).

Currently I can only reproduce this issue if i'm not talking to a plain-text websocket server.

**Comment by MoudhafferMG** [comment]
Hello !
I am having an issue with basic connection via websockets

`import paho.mqtt.client as paho
broker="wss://iot.eclipse.org:443"
client = paho.Client("client-001")
client.connect(broker)`

This is the error message : 

Traceback (most recent call last):
  File "temporary.py", line 7, in <module>
    client.connect(broker)
  File "C:\Users\MoudhafferMG\Anaconda3\lib\site-packages\paho\mqtt\client.py",
line 768, in connect
    return self.reconnect()
  File "C:\Users\MoudhafferMG\Anaconda3\lib\site-packages\paho\mqtt\client.py",
line 895, in reconnect
    sock = socket.create_connection((self._host, self._port), source_address=(se
lf._bind_address, 0))
  File "C:\Users\MoudhafferMG\Anaconda3\lib\socket.py", line 704, in create_conn
ection
    for res in getaddrinfo(host, port, 0, SOCK_STREAM):
  File "C:\Users\MoudhafferMG\Anaconda3\lib\socket.py", line 745, in getaddrinfo
    for res in _socket.getaddrinfo(host, port, family, type, proto, flags):
socket.gaierror: [Errno 11001] getaddrinfo failed

**Comment by PierreF** [comment]
@MoudhafferMG This is another isssue. Your problem is that connect expect an host, not an URL. You can't connect to MQTT over Websocket-tls like this. Please look at example like https://github.com/eclipse/paho.mqtt.python/blob/master/examples/client_sub-ws.py

**Comment by MattBrittan** [comment]
I'm going to close this due to inactivity. If you are still experiencing the issue then please feel free to reopen (but please try to provide enough info for us to reproduce the issue). This is part of a general project to clean-up issues (which should make it simpler to identify priorities going forward).
