### ISSUE TITLE
V1.3.1 crashing silently where 1.2 runs forever

### ISSUE THREAD

**Issue by MrBillium** [eclipse/paho.mqtt.python#249]
I have little hard data to report but here is what I do have:
After routine update of my libraries  my IOT device just quit working between 5 minutes and 6 hours after startup - at least 10 runs made. I  turned on debug logging everywhere but never saw any errors anywhere - app just quit working every time.
I then  tried python mtrace and did see that trace log always stopped at client.py line 1099.  I then rolled Paho back to V 1.2 ( no other changes) and everything is working reliably again.

I am running TLS with connect_async

Any ideas or pointers on how to instrument this to narrow  down?

Bill

**Comment by PierreF** [comment]
Hi,

thank for your patience. Could you provide a bit more information, esp. on how you publish message.
If you get stuck on line 1099 (with self._out_message_mutex), it seems you had a dead-lock where two thread are publishing a messages.
I'm interested on caller to publish(): do they run from one thread, multiple thread and/or from callbacks. And also if on your callback you are calling paho and/or taking a lock that might be hold by a publisher.

**Comment by MrBillium** [comment]
I agree this does smell like a dead-lock given that it always dies  but across a very wide range of time.
This code has been in the field for about a year and works well on 1.2

Lots going on in my code - here is an overview.

I have a ConnectionManager class that calls paho ( not inherited). As in self.pahoclient = MQC.Client()
I did it this way to have better support for srv records.
Once up, I have an ApScheduler job that fires every minute. I consider this  a callback on a new thread.
 In this job, if paho is Not connected then it runs  connectnext() which does the following:

with self.lock  
. Gets the next broker from my srv list - for both load balancing and to make we don't keep trying the first broker forever if it is refusing connections for some reason!
self. pahoclient.disconnect()
self.pahclient.reinitialize()
creates tlsclient
self.pahoclient.connect_async()
self.pahoclient.loop_start()

Note all of the above is wrapped  using 'with self.lock'

My main loop  calls publish  to data topic every x seconds. Simple publish call with  no lock
Logging system also publishes logs to a different topic upon generation using my custom MQTTLogHandler Again I assume that Python  logging is running its own thread. This code also does not lock.

I realize how hard it can be to diagnose such vague symptoms so please let me know if you have any ideas on how to instrument this better.

Thanks

Bill

**Comment by PierreF** [comment]
Thanks for your detailed description.

Are you able to known if your are within your ApScheduler job when the dead-lock occur ? I'm thinking of some bad behavior when some function like disconnect()/reinitilize() and co are called concurrently with publish.
From your description, the dead-lock seems only "internal" of paho (e.g. does not involve an external lock). I'll try to find a way to reproduce this dead-lock.

It may help to reproduce this issue: you are stopping the loop somewhere ? If i understand well, your ApScheduler may call loop_start while the loop is already running (which will just return MQTT_ERR_INVAL and should works but that means - for reproducing the bug - that disconnect() and co may be called while the loop is busy).

**Comment by MrBillium** [comment]
I don’t know enough about ApScheduler to know if a repeating scheduled job is always running but it is what calls the connectnext.

 

There is a loop stop in there before restarting 

try:
    if self.pahoclient._state == 1:
        self.pahoclient.disconnect()
    self.pahoclient.loop_stop(force=True)
    self.pahoclient.reinitialise()
except:
    pass

 

 

Bill

**Comment by PierreF** [comment]
The _out_message_mutex is the first lock took by publish() method. As you said, call to publish don't hold locks (neither lock from your application, and since not called from paho callback, no lock from paho). Therefor it can't be the publish call that cause the deadlock. It's something else that deadlocked while holding the _out_message_mutex.

I would be interested if you can trace other call to paho and see if they deadlock. Especially your reconnect logic (mainly because it probably not well tested to disconnect()/reinitilize()/reconnect() often). Could you check if you disconnect/connectNext get stuck ?

Also to help narrowing which code path is used, are you sending QoS=2 packet ? Is this code receiving packet ? (and which QoS)

**Comment by MrBillium** [comment]
Currently I am running QOS = 1.

The code does listen to a topic but this topic is for program updates only and is rarely used. I am confident that it was not used during the crashes.

 

I am still running into the same problem that despite all my instrumentation, in 1.3 the code just stops without logging anything

 

The connect/reconnect sequence  I built was a problem when I first tried to use it and it evolved through trial and error into the code below which has worked reliably in 1.2

 

# kill any existing client

try:
    if self.pahoclient._state == 1:
        self.pahoclient.disconnect()
    self.pahoclient.loop_stop(force=True)
    self.pahoclient.reinitialise()
except Exception as e:
    logger.error('Kill client error %s ', e)
 

 

 

# create new client from scratch

 

 

 

Bill

**Comment by MattBrittan** [comment]
I'm going to close this due to age/inactivity (the library has seen significant changes since this issue was raised; apologies no one was able to respond to your last comment). If you are still experiencing the issue then please feel free to reopen. This is part of a general project to clean-up issues (which should make it simpler to identify priorities going forward).
