### ISSUE TITLE
tls_set method accepts path instead of cert string

### ISSUE THREAD

**Issue by cah-sachin** [eclipse/paho.mqtt.python#254]
tls_set function is expecting paths to the files not the contents of the file to be passed in. Is there any way through which we can add contents of the path using tls_set and still get MQTT connection ?

If  not is there any plan to do it ?

**Comment by PierreF** [comment]
We are using Python standard ssl module under the hood. Which does not support passing content but only file path. So we can't support this feature.
You will have to write the content in a temporary file to achieve this.

**Comment by ralight** [comment]
Closing because there's nothing we can really do here.

**Comment by RFRIEDM-Trimble** [comment]
Is this the reason you can't supply paths with `~` as in `~/.aws/my_private_key.key`?
