### ISSUE TITLE
MQTT Broker connected or disconnected.

### ISSUE THREAD

**Issue by cah-sachin** [eclipse/paho.mqtt.python#256]
Hello,

Is there any quick way/immediate way to know whether My MQTT broker is connected or not ?

**Comment by PierreF** [comment]
Hi,

currently paho library don't expose this directly. You use callbacks on_connect + on_disconnect to track connection status.
When doing so, don't forget that on_connect is called when broker reply to the connection requests and could refuse it, therefor connection is established only when on_connect is called with rc=0.

**Comment by robgil** [comment]
I'm running in to a similar issue. If I shut down the broker, the client doesn't do anything.

```
    def on_disconnect(self, client, userdata, rc):
        logger.warning('Unexpectedly disconnected from {}:[]'.format(self.host, self.port))
        self.client.connect(self.host, self.port, self.timeout)

    def run(self):
        try:
            self.client.connect(self.host, self.port, self.timeout)
            logger.info('Connected to {}:{}'.format(self.host, self.port))
        except Exception  as e:
            logger.exception(e)

        rc = 0
        while rc == 0:
            rc = self.client.loop_forever(timeout=3, retry_first_connection=True)
        return rc
```

My expectation is that on an unexpected disconnect that `on_disconnect` would get called, but this does not appear to be the case.

**Comment by MattBrittan** [comment]
`is_connected(self)` was added some time ago so I'll close this isssue.
