### ISSUE TITLE
Subscribe topic with not messages

### ISSUE THREAD

**Issue by berrywhite96** [eclipse/paho.mqtt.python#262]
Hey there,
I have currently the problem if I subscribe a topic where never been published a message before, the library stuck in a loop. Only if a message is published the loops ends. For Example:
```
import paho.mqtt.subscribe as subscribe

m = subscribe.simple("emptytopic/nomessages", hostname="127.0.0.1")
```
Possible in this situation to get an empty list?

Thank you.

**Comment by PierreF** [comment]
This helper is made to receive a message from a topic, it's therefor normal to "hang" until a publish is made on this topic.
For just subscribing you should use client's subscribe() method (and then use on_message callback to get message(s))
