### ISSUE TITLE
[Feature request] helper functions for parsing topic names

### ISSUE THREAD

**Issue by vitamins** [eclipse/paho.mqtt.python#263]
Let's say i'm subscribed with client.subscribe('channel/#').
When i'm receiving a message in on_message, i need to strip of 'channel/' from the received msg.topic to retrieve the variable #.

For this simple example i am using this to strip off the beginning.
variable = msg.topic[(len('channel/'):]

This takes more work if there are more variables.

Let's make a helper function that retrieves variables from msg.topic.

**Comment by phi1010** [comment]
I just tinkered https://gist.github.com/phi1010/6f72bd3a188f67f61c5c0d0a8de33854 , this might help.

**Comment by MattBrittan** [comment]
I'm going to close this due to age/inactivity. Please do feel free to reopen but this is more likely to gain traction with a fuller proposal (currently it's not really clear how this would work).
