### ISSUE TITLE
Connection refused when logfile is not owned by mosquitto group

### ISSUE THREAD

**Issue by vitamins** [eclipse/paho.mqtt.python#265]
When the log file /var/log/mosquitto/mosquitto.log is removed or is not owned by the mosquitto user, mosquitto starts without raising any error, but refuses to accept any connections.
An error should be raised when trying to start mosquitto without log file.

Note that this bug has 6 points here.
https://iot.stackexchange.com/questions/636/mosquitto-on-raspberry-pi-refuses-connection-after-changing-log-settings/647#647

**Comment by swails** [comment]
But this isn’t mosquitto...?

This is the python client library for mqtt.

**Comment by PierreF** [comment]
This look as a Mosquitto bug (https://github.com/eclipse/mosquitto). It this bug affect paho-mqtt (the Python client) feel free to reopen.
