### ISSUE TITLE
Make code blocks in the docs highlight syntax

### ISSUE THREAD

**Issue by Benjamin-Lee** [eclipse/paho.mqtt.python#272]
Currently, the readme's code blocks look like this:

```
Client(client_id="", clean_session=True, userdata=None, protocol=MQTTv311, transport="tcp")
```

which can make it difficult to read. 

It would be better if they used Python syntax highlighting, like this:
```python
Client(client_id="", clean_session=True, userdata=None, protocol=MQTTv311, transport="tcp")
```

**Comment by PierreF** [comment]
Good idea, thanks. Pushed this on fixes branch.
