### ISSUE TITLE
Unable to send File 

### ISSUE THREAD

**Issue by Tanmayagarwal14** [eclipse/paho.mqtt.python#273]
Hi,
I am very new to the mqtt . I wanted to send a file using mqtt I used both f.read() and f.write() function but I am unable to send the File I am not understanding what is happening . Any sort of help will be Appreciated. Thanks in advance.
Publish Code:-

import paho.mqtt.client as mqtt

# Define Variables
MQTT_HOST = "iot.eclipse.org" #iot.eclipse.org
MQTT_PORT = 1883
MQTT_KEEPALIVE_INTERVAL = 45
MQTT_TOPIC = "Device1"
#MQTT_MSG = 25

def on_connect(mqttc, userdata, flags, rc):
        #Subscribe to a Topic
    mqttc.subscribe(MQTT_TOPIC, 0)
    print("Connection returned result: "+connack_string(rc))
        
    # Define on_publish event function
def on_publish(mqttc, userdata, mid):
    print "Message Published..."
    print("mid: " +str(mid))
    mqttc.disconnect()
    
    # Initiate MQTT Client
mqttc = mqtt.Client(client_id="LCESS", clean_session=False)

    # Register publish callback function
mqttc.on_publish = on_publish
mqttc.on_connect = on_connect
    # Connect with MQTT Broker
    # probar mqttc.username_pw_set(username, password)
mqttc.connect(MQTT_HOST, MQTT_PORT, MQTT_KEEPALIVE_INTERVAL)		

    # Publish message to MQTT Broker
f= open("/home/chettiar/Desktop/mqtt/filesend/aa.txt")
filecontent = f.read()
byteArr = bytes(filecontent)

mqttc.publish(MQTT_TOPIC,byteArr,0,True)

Subscribing Code:-

import paho.mqtt.client as mqtt

# Define Variables
MQTT_BROKER = "iot.eclipse.org"
MQTT_PORT = 1883
MQTT_KEEPALIVE_INTERVAL = 45
MQTT_TOPIC = "Device1"

# Define on_connect event Handler
def on_connect(mosq, obj, rc):
    print("Connected with result code "+str(rc))
    #Subscribe to a the Topic
    mqttc.subscribe(MQTT_TOPIC, 0)

# Define on_subscribe event Handler
def on_subscribe(mosq, obj, mid, granted_qos):
    print "Subscribed to MQTT Topic"

# Define on_message event Handler
def on_message(mosq, obj, message):
    print("Received message '" + str(message.payload) + "' on topic '"
        + message.topic + "' with QoS " + str(message.qos))
    #if (type(message.payload) == 'byteArray'):
    f = open('/home/pi/Desktop/image.jpg','w')
    f.write(message.payload)
    f.close()
    print 'image received'
            
# Initiate MQTT Client
mqttc = mqtt.Client(client_id="LCSS", clean_session=False)

# Register Event Handlers
mqttc.on_message = on_message
mqttc.on_connect = on_connect
mqttc.on_subscribe = on_subscribe

# Connect with MQTT Broker
mqttc.connect(MQTT_BROKER, MQTT_PORT, MQTT_KEEPALIVE_INTERVAL )

Thanks

**Comment by PierreF** [comment]
You code is quiet hard to read due to formatting issue. I'm assuming that your issue is that you receive no error nor the message is received ?
I see two potential issue:
* You don't start the loop (with loop_start or loop_forever)
* It seems your publisher terminate before waiting for message to be sent. publish() is asynchronous, when the function return the message may not yet be sent.

You may have a look to example (https://github.com/eclipse/paho.mqtt.python/tree/master/examples), especially client_sub and client_pub-wait that seems to match your current use case.

**Comment by Tanmayagarwal14** [comment]
Hi thanks for reply.
I am able to publish the file as I was able to see it by subscribing the topic from the command line. 
But when I am running the subscribing part that time I am not able to read the file.
So I thing the problem is in receiving part.

I also include loop_start()

This is my code for publish:-

import paho.mqtt.client as mqtt

# Define Variables
MQTT_HOST = "iot.eclipse.org" #iot.eclipse.org
MQTT_PORT = 1883
MQTT_KEEPALIVE_INTERVAL = 45
MQTT_TOPIC = "Device1"


def on_connect(mqttc, userdata, flags, rc):
        #Subscribe to a Topic
    mqttc.subscribe(MQTT_TOPIC, 0)
    print("Connection returned result: "+connack_string(rc))
        
    # Define on_publish event function
def on_publish(mqttc, userdata, mid):
    print "Message Published..."
    print("mid: " +str(mid))
    mqttc.disconnect()
    
    # Initiate MQTT Client
mqttc = mqtt.Client(client_id="LCESS", clean_session=False)

    # Register publish callback function
mqttc.on_publish = on_publish
mqttc.on_connect = on_connect
mqttc.connect(MQTT_HOST, MQTT_PORT, MQTT_KEEPALIVE_INTERVAL)		
mqttc.loop_start()
# Publish message to MQTT Broker
f= open("/home/chettiar/Desktop/mqtt/filesend/aa.txt")
filecontent = f.read()
byteArr = bytes(filecontent)

file=mqttc.publish(MQTT_TOPIC,byteArr,0,True) 
file.wait_for_publish()

**Comment by Tanmayagarwal14** [comment]
Thanks. I solve the error now it working fine .
Thanks a lot.
