### ISSUE TITLE
 publish.single and publish.multiple examples are not working 

### ISSUE THREAD

**Issue by hemantkamalakar** [eclipse/paho.mqtt.python#274]
Hi,
Installed paho-mqtt using pip.
`pip install paho-mqtt`
Examples publish.single and publish.multiple are not working.

```import paho.mqtt.publish as publish
msgs = [{'topic':"paho/test/multiple", 'payload':"multiple 1"},
    ("paho/test/multiple", "multiple 2", 0, False)]
publish.multiple(msgs, hostname="localhost")
#publish.single("paho/test/single", "payload", hostname="localhost")
```
Error while publishing single message.

```Traceback (most recent call last):
  File "test.py", line 6, in <module>
    publish.single("paho/test/single", "payload", hostname="localhost")
AttributeError: 'module' object has no attribute 'single'
```
Error while publishing multiple messages.
```Traceback (most recent call last):
  File "test.py", line 5, in <module>
    publish.multiple(msgs, hostname="localhost")
AttributeError: 'module' object has no attribute 'multiple'
```

```
sudo pip show paho-mqtt
Name: paho-mqtt
Version: 1.3.1
Summary: None
Home-page: None
Author: None
Author-email: None
License: None
Location: /usr/local/lib/python2.7/dist-packages
```

**Comment by PierreF** [comment]
Hi,

your installation is broken in some way. I've just trying your step and it works for me.
In addition, when I run pip show:
```
$ pip show paho-mqtt
Name: paho-mqtt
Version: 1.3.1
Summary: MQTT version 3.1.1 client class
Home-page: http://eclipse.org/paho
Author: Roger Light
Author-email: roger@atchoo.org
License: Eclipse Public License v1.0 / Eclipse Distribution License v1.0
Location: /home/pierref/.virtualenvs/tmp/lib/python2.7/site-packages
Requires: 
```

I've much more information like Summary, Home-page, Author, etc.

This make me think that your initial pip install failed. Did you have any error while installing ? I will try a guess, you had system crash closely after installation and all files are empty (/usr/local/lib/python2.7/dist-packages/paho/mqtt/publish.py is empty) ?

**Comment by hemantkamalakar** [comment]
Thanks a lot.
Indeed my installation was broken. Uninstalled pip and installed it again and it is working fine now.
Thanks again.
