### ISSUE TITLE
Roadmap for dropping support for Python 2

### ISSUE THREAD

**Issue by jamesmyatt** [eclipse/paho.mqtt.python#279]
Is there any roadmap for dropping support for Python 2, along the lines of https://python3statement.org/?

**Comment by vrst37** [comment]
@PierreF @ralight what do you guys think about this? I think it makes sense, but I am not sure how many people will be affected by this.

**Comment by ralight** [comment]
I am not involved in the Paho Python code at the moment, but take the stance that if upstream doesn't support something then neither should I. Support for 2.7 should go before 1st January 2020. I'd also support the suggestion to drop it before/as part of the MQTT v5 work.

**Comment by akx** [comment]
Python 2.7 support was implicitly dropped in 1.6.x.

Future versions will only support Python 3.7+: https://github.com/eclipse/paho.mqtt.python/blob/b29e31c8943702cd5fcc3dbddc505107c57eaaa8/pyproject.toml#L13

**Comment by MattBrittan** [comment]
I'm going to close this as the readme now states "It supports Python 3.7+" (and the next release should be out shortly).
