### ISSUE TITLE
Ssl lost connection results in non functional connection

### ISSUE THREAD

**Issue by jpwsutton** [eclipse/paho.mqtt.python#28]
migrated from Bugzilla [#436463](https://bugs.eclipse.org/bugs/show_bug.cgi?id=436463)
status UNCONFIRMED severity *normal* in component *MQTT-Python* for *0.9*
Reported in version *0.9* on platform *PC*
Assigned to: Roger Light

On 2014-06-03 10:39:43 -0400, Hiram van Paassen wrote:

> We use a script to subscribe a power supply to mqtt over ssl. We notice that sometimes the network connection is not stable and the script looses its connection.  It should try to reconnect because we use loop_start() (same behavior with loop_forever()) but it fails to make a proper connection.
> 
> I noticed that in a previous version the ssl.read(1) call in loop_read() would sometimes "read" 0 bytes when this happens
> 
> Unfortunately I have not been able to find the real source or to create better logging but here is some logging from our script to show what happens:
> 
> The source of published messages is guaranteed to publish every 5 seconds even after the network failure
> 
> $ ./start_script.py
> Checking watchdogs
> Connection Accepted.
> subscribed
> Got published message
> Checking watchdogs
> Got published message
> Checking watchdogs
> Got published message
> Checking watchdogs
> Got published message
> Checking watchdogs
> Got published message
> Checking watchdogs
> Got published message
> Checking watchdogs
> Got published message
> Checking watchdogs
> Got published message
> Checking watchdogs
> Got published message
> Checking watchdogs
> Got published message
> Checking watchdogs
> Got published message
> Checking watchdogs
> Got published message
> Checking watchdogs
> Got published message
> Checking watchdogs
> [Errno 104] Connection reset by peer
> Checking watchdogs
> Checking watchdogs
> Connection Accepted.
> Connection Accepted.
> Checking watchdogs
> Connection Accepted.
> Checking watchdogs
> Connection Accepted.
> Connection Accepted.
> Checking watchdogs
> Connection Accepted.
> Checking watchdogs
> Connection Accepted.
> Checking watchdogs
> Checking watchdogs
> Connection Accepted.
> 
> 
> relevant code:
> 
> def on_message(mosq, userdata, mqtt_message):
>     print "Got published message"
> 
> def on_connect(mosq, userdata, rc):
>     print mosquitto.connack_string(rc)
>     # subscribe to commands
>     mqtt.subscribe(COMMAND_TOPIC, 2)
> 
> def on_subscribe(mosq, userdata, mid, granted_qos):
>     print "subscribed"
> 
> mqtt = mosquitto.Client(clean_session=True)
> mqtt.tls_set(CERT_DIR)
> mqtt.username_pw_set("user", "password")
> 
> # set message callback
> mqtt.on_message = on_message
> mqtt.on_connect = on_connect
> mqtt.on_subscribe = on_subscribe
> 
> 
> # keepalive of 50 seconds
> # because loadbalancer loses connection after 60 seconds of inactivity
> mqtt.connect(MQTT_HOSTNAME, 8883, 50)
> 
> mqtt.loop_start()
> 
> 
> 
> I would expect to see the script reconnect and to start receiving published messages again. This regardless of clean_session=True btw.

On 2014-06-17 04:12:04 -0400, Roger Light wrote:

> I wonder if the fix used for bug # 436615 fixes this for you as well. Would you be able to try the latest code from the repository please?

On 2014-09-12 17:22:12 -0400, Roger Light wrote:

> Could this be related to the other bugs you've filed? It feels like it could be.

**Comment by ralight** [comment]
Closing as likely to have been fixed with another bug.
