### ISSUE TITLE
subscribe.simple can‘t sub all messages at the same moment

### ISSUE THREAD

**Issue by chutingxia** [eclipse/paho.mqtt.python#292]
i want to use subscribe.simple as i need tls verification,but i don‘t know how many msg_count the topic would publish at the same moment，the subscribe.simple function connect itself and will disconnect after its subscription，then some messages will be ignored, how can i subscribe when i don't konw msg_count.

**Comment by PierreF** [comment]
I'm not sure to understand your use case.

Using subscribe.simple allow to subscribe and receive N (fixed) messages from topics. By default it's only one.
If you need to process an unknown number of message subscribe.callback could be useful.

**Comment by chutingxia** [comment]
thank you very much!
