### ISSUE TITLE
what is the state of develop and fixes?

### ISSUE THREAD

**Issue by swails** [eclipse/paho.mqtt.python#295]
I've brought up this confusion several times in the past, and it's causing me pains again:

*What is the current state of the develop and fixes branches?*

fixes does not merge cleanly into develop -- not even close.  Some changes go into fixes and some into develop ("features" and "bug fixes" are not always cut-and-dry).  I can't find the discussion, but I was originally told the branching model we're using here is basically [this](http://nvie.com/posts/a-successful-git-branching-model/).

Except it's not.  It's broken.  The fixes branch needs to be *continuously* updated into develop, which doesn't happen.  Otherwise I find myself spinning my wheels trying to merge in diverged fixes and develop branches by hand, not knowing what to keep and what to reverse.

If a release were to be cut today, *there is no branch or even automated process that can generate the code that would be released.*  This is absolutely crazy.  I fail to see how this is a sustainable development strategy.  I can understand the value of the strategy in the link, but the purported need for a "fixes" branch is rather undercut by the incredibly slow release cycle -- we're talking about 1/year, with maybe a couple quick bugfix branches immediately after a release -- certainly nothing that justifies a dedicated branch to rapidly-releasable hotfixes.

I'm going to *try* and push my merge attempt fixes -> develop soon, but I would really like to never have to do this again; it's endlessly frustrating.  But nobody seems to have the time to maintain the branching structure being used here.  I'd really like to see this repo to move to something simpler and more manageable, even if it sacrifices aspects that quite frankly aren't even utilized, anyway.

<\/rant>

**Comment by jamesmyatt** [comment]
I'm with you, @swails . Also this: https://github.com/eclipse/paho.mqtt.python/issues/141

**Comment by lyssdod** [comment]
Same here. This library really looks abandoned. @PierreF can you please maybe give a hint on the support status of this? Because while there are other solutions available, the library remains the most popular choice for MQTT stuff with Python (despite lots of issues which pop up here and there if you need some beyond-the-scope-of-the-tutorial-application), and thus user base is quite big as it seems to me. While nobody here probably have time to devote themselves on maintainer role, it would be really nice to at least come to some stable state and at least setup some Travis CI for PRs and branches (I can do this).

**Comment by swails** [comment]
@lyssdod - you need to look at the `develop` branch, not `master` (the latter is very rarely updated, the former, with `fixes` are those that are typically developed more regularly).

Both of those branches were changed as recently as May 1, 2018.  The library certainly doesn't get the attention it probably needs, but "abandoned" is an exaggeration.

> and at least setup some Travis CI for PRs and branches (I can do this).

Look at any of the PRs (or the PR page itself) and you'll see either a check or an X indicating the status of the Travis build.  This is already done.

The problem I'm raising here is that there's no single branch of truth that indicates the actual state of what would be released today.  You have to pull the relevant changes from `fixes` into `develop` and resolve the differences (and I have no idea which commits to `fixes` fits that description).

I'm not upset with the pace of development.  I'm upset with the fact that we can't reliably *test* or try the latest version before a release is cut (and I can't wrap my head around the actual branching strategy being employed here).

**Comment by jamesmyatt** [comment]
@swails, can you add a link to the Travis CI project in the README files?

**Comment by lyssdod** [comment]
@jamesmyatt That's nice for the development perspective, but PyPi release uses `master` branch, which was updated quite a while ago (I'm speaking from the point of end user, who just wants to do `pip install paho-mqtt`). I understand the problem of merging, although I thought `develop` is the most recent branch

**Comment by PierreF** [comment]
@lyssdod as other replied, this project is not abandoned but indeed could require more attention. Help is always welcomed :)
Master branch is the latest released code (that why PyPI "uses" master branch). There aren't release since then because: 1) it take time to do a release 2) I don't though that pending changes were important enough to justify a release.

@swails I'll try to come with a simpler branching models after the next feature release. Probably as you suggest keeping only develop branch and no longer doing fixes release (urgent hot fixes could always be cherry-picked on master in rare case that require it).

**Comment by PierreF** [comment]
I suggest the following new workflow:

* kept only one branch "master"
* Any commits, bug fixes or new feature go to master
* A new major release is made from master. As currently release are tagged on git

For a minor release:
* The change to include in the minor release are, like all other contribution, committed to master.
* A branch is created from the release tag
* Fixes that must be included are cherry-picked from master
* tag & release the new minor version
* (unsure if needed) merge this branch into master and delete the branch

This workflow will make minor release slightly more complicated (need to sort-out which commit to cherry-pick and resolve potential conflict). Be regarding the number of minor release I think this is acceptable and easier that current branching that should require constant merging of fixes branch into develop branch.
It will also cause master branch to no longer being the latest release as it's with current model. While this allow to see documentation of latest release from github (and not next release), I think this is acceptable and usually master branch is the next release to people are used to it.
In general it will ease contribution, as PR are mostly created for master branch.

If nobody object for this workflow, I will start using it with the next major release, which I hope will arrive soon.

**Comment by swails** [comment]
> (unsure if needed) merge this branch into master and delete the branch

This step doesn't make sense with cherry-picking fixes from master.  You would do this if you made a fix against a release branch and *also* wanted that fix in `master`.

But if you make the fix to master first, like I think you should (and you suggested), the way to propagate that fix to the necessary release branches is to cherry-pick (again, as you suggested).  You may have to resolve conflicts (but that would be true with merging release into master if you patched against the release version first).

With the exception of this one step, I like this workflow much better. 👍

**Comment by swails** [comment]
One other comment:

It may be that a fix is only needed in a release branch because a major refactor in master had the side-effect of fixing the bug in question.

Assuming that refactor was not desired in the release branch (probably true), then the fix would be created as a PR against the release branch, and nothing done to `master`.

In other cases, fixing master and cherry-picking is the right way to go, I think.

**Comment by swails** [comment]
It also may be worth creating a new issue specifically for this proposal to increase its visibility.

**Comment by PierreF** [comment]
Good idea, new issue created as #320. I'm closing this issue as #320 will fix this issue. Any further discussion should go to #320 to avoid 2 thread.
