### ISSUE TITLE
paho client sends pubrel with dup flag

### ISSUE THREAD

**Issue by uboscolo** [eclipse/paho.mqtt.python#298]
Hi,

according to MQTT specs there should be no dup flag set for the PUBREL message (section 3.6.1-1 in mqtt 3.1.1 specs)

I see this statement where the pubrel is sent with Dup = True

elif m.state == mqtt_ms_wait_for_pubcomp:
                        m.timestamp = now
                        m.dup = True
self._send_pubrel(m.mid, True)

**Comment by PierreF** [comment]
This is now fixed on fixes branch. Thanks for the report.
