### ISSUE TITLE
Reconnect on an SSL socket can block forever

### ISSUE THREAD

**Issue by jpwsutton** [eclipse/paho.mqtt.python#3]
migrated from Bugzilla [#478959](https://bugs.eclipse.org/bugs/show_bug.cgi?id=478959)
status UNCONFIRMED severity _major_ in component _MQTT-Python_ for _1.2_
Reported in version _unspecified_ on platform _PC_
Assigned to: Roger Light

Original attachment names and IDs:
- _[paho-client-TLS-reconnect-timeout.patch](https://bugs.eclipse.org/bugs//attachment.cgi?id=257015)_ (ID 257015)

On 2015-10-03 13:25:52 -0400, Jeff Jasper wrote:

> Created attachment 257015
> Patch for the bug.
> 
> The ssl.wrap_socket call within the reconnect method can block forever if the broker (for whatever reason) does not respond during the handshake. I don't know what's causing the broker (RabbitMQ) to not respond but it occurs occasionally and happens more frequently under network conditions with high latencies.
> 
> I'm including a patch where I perform the TLS handshake after wrapping the socket and give the socket a 10 second timeout. After the handshake completes I set the socket to non-blocking. Feel free to change my hard coded 10 sec. block to something more configurable.
> 
> Also included in the patch is a broad exception catch to release the _current_out_packet_mutex to avoid potential deadlock (I've never experienced this but noticed it when I was troubleshooting the previous issue).

On 2016-01-04 19:04:49 -0500, Adam mills wrote:

> We are seeing this as well with Mosquitto as a broker.

**Comment by PierreF** [comment]
PR #124 merged
