### ISSUE TITLE
Run asynchronous consumer 

### ISSUE THREAD

**Issue by shaloba** [eclipse/paho.mqtt.python#301]
Hi ,

First of all I love your package, easy to use and with helpful documentation. 
I wish to use your package in asynchronous way in order to use it more efficiently. 
I didn't find anything beside the repository below   

https://github.com/mossblaser/aiomqtt

do you have something like that in your to do list or can suggest a better way to implement it ?

Thanks!

Shlomy.

**Comment by MattBrittan** [comment]
Closing this as the question is fairly vague (if asking this kind of thing please be specific and, ideally, include some code).
