### ISSUE TITLE
Paho does not initialize audio files after payload is received

### ISSUE THREAD

**Issue by netrosec** [eclipse/paho.mqtt.python#303]
I think i just found a potential bug in paho.

Below is my python script that listens for incoming mqtt payloads and should play a sound file with 

> Sox os.system('play --no-show-progress %s --channels 2 synth %s' % (sound1, duration))

 depending on the publication from the client, but it doesn't.

Upon further investigation i discovered that when i put the call to initialize the sound file directly under the on_message function, the sound file plays. But if i make the statement conditional it fails to play without giving any error.

Here's my full code.

> 
```
> import paho.mqtt.client as mqtt
> from subprocess import Popen
> import os
> import sys
> import subprocess
> import time
> 
> 
> 
> mqtt_topic = "light"
> mqtt_broker_ip = "192.168.0.55"
> duration = 5  # second
> sound1 = "/home/pi/on.wav"
> 
> client = mqtt.Client()
> 
> 
> def on_connect(client, userdata, rc):
>    
>     print "Connected!", str(rc)
>     
>  
>     client.subscribe(mqtt_topic)
>     
> def on_message(client, userdata, msg):
>     if msg.payload == "0":
>         os.system('play --no-show-progress %s --channels 2 synth %s' % (sound1, duration))
>         #os.system('aplay -d {} {}'.format(duration_time, song_path))
>     print "Topic: ", msg.topic + "\nMessage: " + str(msg.payload)
>     
>     
> 
> 
> client.on_connect = on_connect
> client.on_message = on_message
> 
> client.connect(mqtt_broker_ip, 1883)
> 
> 
> client.loop_forever()
> client.disconnect()
> 
```

**Comment by PierreF** [comment]
Hi,

my guess it that you condition is never true. If you are using Python 3, IIRC, the payload will be bytes and not string. You must use "msg.payload == b'0'".

Also be aware that on_message callback should not hang for too long, as paho-mqtt is single-threaded it will block all network processing which may cause keep-alive the disconnect you. "Too long" depends on your keep-alive (60 seconds by default), so blocking for 1-10 seconds should be fine.

**Comment by ralight** [comment]
Closing because this appears to be mostly unrelated to Paho operation itself. If you still have a problem with the Paho Python client please reopen and add more details.
