### ISSUE TITLE
ModuleNotFoundError: No module named 'paho'

### ISSUE THREAD

**Issue by thanhcra** [eclipse/paho.mqtt.python#304]
I'm newbie. I installed paho-mqtt but when IDE PyCharm/Spyder can't find Module Paho
![image](https://user-images.githubusercontent.com/37483861/41394818-9ca63d78-6fd5-11e8-9738-6f2e6f03184a.png)
![image](https://user-images.githubusercontent.com/37483861/41394841-af59fbd0-6fd5-11e8-8326-cf4355ffbe1f.png)
Please help me!

**Comment by swails** [comment]
You probably didn't install the paho-mqtt library to the same Python environment your IDE is using.  You almost certainly have more than 1 Python installation.  Installing it in one Python installation does not make it available in any other one.

**Comment by ralight** [comment]
Closing because this has been answered.
