### ISSUE TITLE
About the reconnect  interval.

### ISSUE THREAD

**Issue by LindaWang1234** [eclipse/paho.mqtt.python#307]
I want it to keep re-connect, how to set minRetryInterval and maxRetryInterval? 
my setting now is:
automaticReconnect = 1;
cleansession = 0;	
keepAliveInterval = 60;
connectTimeout=30
retryInterval=0
minRetryInterval=1
maxRetryInterval=32768

**Comment by PierreF** [comment]
Hi,

I'm not sure to understand what your settings are. None of those variable name exists in this project.

That being said, paho.mqtt.python does support automatic reconnect which is enabled by default if you are using loop_forever()/loop_start(). When using manual loop(), you will need to call reconnect yourself.

About possible correspondence to minRetryInterval and maxRetryInterval there is a reconnect_delay_set that allow you to specify the shortest and longest delay between two reconnect try. Note that it's the delay between two reconnect, so if you set max_delay to 32768 it means that reconnect may wait 32768 seconds (or ~9 hours) before retrying. The re-connection process will re-attempt forever (until you either explicitly call disconnect() or - if using loop_start() - you explicitly call  loop_stop())

**Comment by LindaWang1234** [comment]
Thank you for your reply.
I want to know:
How it do re-connect and never don't stop.(when it disconnect).
Maybe some flag or parameter cand set?!

**Comment by LindaWang1234** [comment]
Sorry, I post wrong place.

**Comment by lincoln310** [comment]
@DavidDong33 
MQTTAsync_connectOptions conn_opts = MQTTAsync_connectOptions_initializer;
conn_opts.automaticReconnect = true;
MQTTAsync_connect(client, &conn_opts)
