### ISSUE TITLE
MQTT5 Status

### ISSUE THREAD

**Issue by AtosNicoS** [eclipse/paho.mqtt.python#313]
Hi,
I was unable to find any status about a version for mqtt5. Is there anything planned/working on? Is the code public yet?

**Comment by NicoHood** [comment]
@icraggs Could you maybe tell me more about the Python client here:
https://github.com/eclipse/paho.mqtt.testing/blob/master/interoperability/mqtt/clients/V5/main.py

Is this one fully functional? Why is it not merged here?

I am searching for an mqtt library that supports persistent session. Mqtt5 is not top prio, but nice. And it seems that this paho library here does not support this feature, nor Mqtt5. So I am wondering what would be an argument for/against using the library in the test suit?

**Comment by ralight** [comment]
I'm not currently able to work on the Paho project, so can't promise MQTT 5 support from me.

**Comment by icraggs** [comment]
@NicoHood there's no reason why you couldn't use the Python client in the test repo, it's entirely up to you of course.  I added MQTT V5 support as part of creating a broker that client libraries could test with.

Why isn't it merged here?  That's for historical reasons - it was a project of my own which I used for test purposes.  It's fairly complete as you might see from the client_test.py and client_test5.py broker test programs which use it.  The API style is different of course, I tended to reimplement the first Java MQTT API in various languages to give a 'family' feel, for better or worse.  

I'm motivated to add V5 support to this Python client too, and may well get around to it before Pierre.  Of course, we're always open to PRs from anyone who would like to contribute too!

**Comment by NicoHood** [comment]
That sounds good! I would recommend to use the **better API**. We do not want to maintain both, even though compatibility is nice. I'd personally want to use the better API that is well supported across the whole paho project. Do you have any compiled docs for your current v5 library? Maybe we can just 'transfer' it here, and its all done.

**Comment by icraggs** [comment]
I don't think it's a question of which is the better API, as different people will always have different opinions.  Whichever API is used, there will be outstanding issues or enhancements which could be deal-breakers for different situations.

My plan was to submit an MQTT V5 update for this API.    Are there particular features of MQTT V5 that you are interested in?

**Comment by NicoHood** [comment]
Okay that sounds nice.

The features that I'd like to use are:
* Message persistence (retrieve stored messages >= QoS 0 with a persistant session) -> not a V5 feature, but still missing
* Message Properties
* Time to live for messages (Message expiry)

**Comment by icraggs** [comment]
@AtosNicoS Not yet I'm afraid.  I'm finishing off the Paho C client V5 support, then I'll get to look at this one.

**Comment by icraggs** [comment]
I'm making the changes in https://github.com/icraggs/paho.mqtt.python before creating the PR, if anyone wants to take a look.

**Comment by jamesmyatt** [comment]
Is it worth doing things like dropping support for old versions of Python (e.g. <3.5) and all of the associated compatibility code, before making a big change like this?

**Comment by AtosNicoS** [comment]
I'd say yes. I personally would also drop python2 support, as nobody should develop a new mqtt5 infrastructure in python2. That would be the time to migrate both. If it simplifies the code, makes it better maintainable, readable and less error-prone, I'd go for it. Good idea.

**Comment by Monarda** [comment]
I'm stuck on Python 2.7.2 (a long story) for now, so I'd personally appreciate retaining backward compatibility there. But obviously do what's better for the overall health of the project.

**Comment by icraggs** [comment]
I'm going to leave that decision to the project maintainers - my aim is just to add the V5 support.  I'll make the basic V5 function work and then submit a PR for review/comments.   Quite a lot of the V5 code is in separate modules so the main module isn't getting more complication than it needs.

**Comment by icraggs** [comment]
I've created the initial changes to allow basic MQTT V5 to work, here: 

https://github.com/icraggs/paho.mqtt.python/commit/d2d62a169426273449cfd14294591f9b9b8935a5

An example program to show how this works is here: 

https://github.com/icraggs/paho.mqtt.python/blob/master/src/test_mqttv5.py

(this program works using the V5 broker in https://github.com/eclipse/paho.mqtt.testing).  I reused some code from my previous Python implementation, with few changes at the moment.

(@AtosNicoS sorry your previous comments have been lost because I redid the commit from the proper base level, 1.4.  I have an email with them in though, and have taken note.  Thanks!)

**Comment by AtosNicoS** [comment]
So I did another quick review. Not all of my comments might make sense to you. I thought it would be better to write down my ideas than maybe missing something.

Overall the PR looks extremely good to me and also simple to review. The diff is quite simple (did not expect this) and the added files are only a few. Good work!

It would be interesting to me what features are still missing from the spec. They might be no prio1 or required at all. What I wish for is (maybe another separate PR) persistant session support. As far as I know this is not yet supported. Did you also reflect that in the connection properties? I remember you can tell the broker what mqtt features your support and what not.

**Comment by icraggs** [comment]
I realised that that PR doesn't work in Python 2, only Python 3.  I'm working on that.

**Comment by petersilva** [comment]
the details of using the c client:
publish:

`./paho_c_pub mytopic --message hoho -V 5 --user-property lala hoho
`
subscribe 
 
`./paho_c_sub mytopic -V 5 -v`

When I use the c subscriber with the python publisher, the properties do not show up.  So I suspect the publish in python isn't working.

**Comment by icraggs** [comment]
Hi.  I'm working on the Java client release (https://github.com/eclipse/paho.mqtt.java/milestone/2) at the moment as my top priority.  I'll get back to this when I can.  I'm happy to have any help.

**Comment by ralight** [comment]
MQTT v5 support was released in v1.5.
