### ISSUE TITLE
Client.connect() throws exception on providing URL scheme mqtt://**:1883

### ISSUE THREAD

**Issue by itsgk92** [eclipse/paho.mqtt.python#316]
When I try connecting to brocker with fully formed URL it gives socket stream error on get address info

socket.gaierror: [Errno -2] Name or service not known

Stack trace: 

   client.connect(broker_url)
  File "/usr/local/lib/python2.7/site-packages/paho/mqtt/client.py", line 768, in connect
    return self.reconnect()
  File "/usr/local/lib/python2.7/site-packages/paho/mqtt/client.py", line 895, in reconnect
    sock = socket.create_connection((self._host, self._port), source_address=(self._bind_address, 0))
  File "/usr/local/lib/python2.7/socket.py", line 557, in create_connection
    for res in getaddrinfo(host, port, 0, SOCK_STREAM):

**Comment by arvindh92** [comment]
Okay! I noted the similar issue here on JAVA branch! https://github.com/eclipse/paho.mqtt.java/issues/464. Link them if appropriate!

**Comment by PierreF** [comment]
The Python library does not support URL. It take host and as second argument a port. E.g.
```
mqttc.connect("test.mosquitto.org", 1883)
```

Note that the port is not mandatory and default to 1883.

**Comment by ralight** [comment]
Closing because I believe this has been addressed.
