### ISSUE TITLE
I do not know how to use it on my server。 when I use my server，i can not receive my subscribe。

### ISSUE THREAD

**Issue by pengbo19921206** [eclipse/paho.mqtt.python#322]
```
import paho.mqtt.client as mqtt
message = 'ON'
def on_connect(mosq, obj, rc):
    mqttc.subscribe("test", 0)
    print("rc: " + str(rc))

def on_message(mosq, obj, msg):
    global message
    print(msg.topic + " " + str(msg.qos) + " " + str(msg.payload))
    message = msg.payload
    mqttc.publish("f2",msg.payload);

def on_publish(mosq, obj, mid):
    print("mid: " + str(mid))

def on_subscribe(mosq, obj, mid, granted_qos):
    print("Subscribed: " + str(mid) + " " + str(granted_qos))

def on_log(mosq, obj, level, string):
    print(string)

mqttc = mqtt.Client()
# Assign event callbacks
mqttc.on_message = on_message
mqttc.on_connect = on_connect
mqttc.on_publish = on_publish
mqttc.on_subscribe = on_subscribe
# Connect
mqttc.connect("my server", 1883,60)
mqttc.subscribe("test", 0)

# Continue the network loop
mqttc.loop_forever()
```

**Comment by vrst37** [comment]
What is it your are asking?

**Comment by wuyanbei24** [comment]
maybe i have meet the same problem in my work
when i use it as a server and running a few days(almost two weeks) later, it can not receive message and without connect error
at the same time, i use an another thead publish topic, there is no problem

**Comment by PierreF** [comment]
As said in #323:
* I don't see issue with this code. It not perfect, but it should work (see below for how to improve it)
* Log from client (by adding mqttc.on_log = on_log) and from broker (if using mosquitto, with option -v) could help
* Information on how you publish message, and if the publish happend *after* the subscribe will also be helpful

The point that could be improved is where the subscribe is done. By doing the subscribe here, the subscription will only exists for current connection. If the connection is broken and client reconnect, the subscribe is lost.
This may explain @wuyanbei24 : the subscribe works for the first connection, but after a reconnection (after few days, it may happen depending on network quality) the subscription is lost.

To avoid this issue, the best it to subscribe within the on_connect callback. As such you will be sure to subscribe on each (re)connection.

**Comment by csabaszan** [comment]
hi, it took me some time yesterday to find out that the signature of on_connect has now changed, without keywords the on_connect posted above fails and therefore no subscription is made. Almost the same example code can be found here: https://www.eclipse.org/paho/clients/python/ which, at least in my case, also failed. Changing the definition of 
`def on_connect(client, userdata, rc)`
to
`def on_connect(client, userdata, flags, rc)`
solved the issue for me.

**Comment by PierreF** [comment]
Indeed, good catch: the website have a broken example.

on_connect callback must accept 4 argument since version 1.3.0. I'll update the website.

**Comment by MattBrittan** [comment]
Closing as it looks like an answer was provided (and the issue has been inactive for some time).
