### ISSUE TITLE
mqtt reconnect takes more than  40 seconds

### ISSUE THREAD

**Issue by chutingxia** [eclipse/paho.mqtt.python#331]
```
client = Mqtt.Client()
client.connect(self.mqtt['server'], port=self.mqtt['port'])
client.loop_start()

while True:
       msg = {'topic': '/dev/20', 'payload': b'dsjfheruweioe', 'qos': 0, 'retain': False}
       client.publish(**msg)
       time.sleep(2)
```

I use this code in python 3.5, It should be publish the message 2 seconds,but some times the interval between two publish can be more than 40 seconds, It occur about 1 or 2 times during 48 hours, I want to ask your how can I reduce the reconnect time, Do I use in a wrong method,best wishes !

**Comment by chutingxia** [comment]
client = Mqtt.Client()
client.connect(self.mqtt['server'], port=self.mqtt['port'])
client.loop_start()

while True:
        msg = {'topic': '/dev/20', 'payload': b'dsjfheruweioe', 'qos': 0, 'retain': False}
        client.publish(**msg)
        time.sleep(2)

I use this code in python 3.5, It should be publish the message every 2 seconds,but some times the interval between two publish can be more than 40 seconds, It occur about 1 or 2 times during 48 hours, I want to ask your how can I reduce the reconnect time, Do I use in a wrong method,best wishes !

**Comment by PierreF** [comment]
You code seems correct.
In the title you talk about "reconnection", is your connection broken and a reconnect happen ?
In that case, it may be the exponential reconnect delay, you can configure is using https://github.com/eclipse/paho.mqtt.python#reconnect_delay_set

**Comment by chutingxia** [comment]
thank you very much ! do you mean that i reduce the max_delay seconds,like:
client.connect(self.mqtt['server'], port=self.mqtt['port'])
client.loop_start()
client.reconnect_delay_set(min_delay=1, max_delay=30)
while True:
msg = {'topic': '/dev/20', 'payload': b'dsjfheruweioe', 'qos': 0, 'retain': False}
client.publish(**msg)
time.sleep(2)
what the best max_delay should i set?

**Comment by PierreF** [comment]
This delay is an exponential delay, which means that first re-connection attempt will be done after 1 seconds (if min_delay=1). If that re-connection fail, the next attempt will be after 2 seconds. Then 4, 8, ... until reaching 30 (max_delay).

Usually for simple disconnection, the first reconnect attempt will success (e.g. after min_delay). But if the cause of the disconnection persist (network is saturated, broker is overloaded, or no connection at all), then you may reach the max_delay.

Then the max_delay is mostly a tradeoff between faster re-connection and saving resources:
* With short max_delay, you get reconnected as soon as the issue is solved, but you may contribute to aggravate that situation (since you will retry connection more often, generating network traffic and/or broker processing)
* With long max_delay, you may need to wait longer for the reconnected (but remember that the first re-connection attempt use min_delay), on the other hand you will generate less traffic due to fewer retry in the same period.

That max_delay may be very useful in case where your broker had an outage. With a too short max_delay, all your clients will be hammering the server trying to reconnect.
The importance between a faster re-connection and avoiding hammering the broker depend on your need (can you accept 10 seconds delay ? 1 minute ? more ?) but also the number of clients (with 10 clients, it does not matter).

**Comment by chutingxia** [comment]
thank you very much, i was not care of the network traffic until you refer this. In fact, I really have a number of clients, maybe I should use other method to solve this problem,not just to reduce max_delay.thank you very much for you great help!

**Comment by nityasantoshi** [comment]
@chutingxia, How did you solve this issue? My Paho MQTT client is taking 1 minute between each message for publishing. I didnot configure any where to send like that. 
Please take a look at my code:

import argparse
import json
import ssl
import sys
import datetime

import paho.mqtt.client as mqtt



def parse_args():
    # Parse arguments
    parser = argparse.ArgumentParser(description="Connect and send device data to Sentience")
    parser.add_argument("-t", "--token", dest="token",
                        help="specify a device JWT token in the format '<token>'", required=True,
                        type=str)
    parser.add_argument("-b", "--broker", dest="broker",
                        help="specify the broker to connect to", default="mqtt-ws.XXXX",
                        type=str)
    parser.add_argument("-p", "--port", dest="port",
                        help="specify the port to connect with", default=443,
                        type=int)

    parser.add_argument("--project", dest="project_id",
                        help="specify the project the device exists within", required=True,
                        type=str)
    parser.add_argument("--device", dest="device_id",
                        help="specify the device to send data to", required=True,
                        type=str)

    parser.add_argument("payload", metavar="P", nargs="+",
                        help="<measurement>=<value>")

    return parser.parse_args()


def verify_on_connect(rc):
    if rc == 0:
        print("rc printing")
        print("Connection successful")
        print(datetime.datetime.utcnow().strftime("%m/%d/%Y, %H:%M:%S"))
    else:
        if rc == 1:
            print("Connection refused - incorrect protocol version", file=sys.stderr)
        if rc == 2:
            print("Connection refused - invalid client identifier", file=sys.stderr)
        if rc == 3:
            print("Connection refused - server unavailable", file=sys.stderr)
        if rc == 4:
            print("Connection refused - bad username or password", file=sys.stderr)
        if rc == 5:
            print("Connection refused - not authorized", file=sys.stderr)
        exit(2)


# The callback for when the client receives a CONNACK response from the server.
def on_connect(client, userdata, flags, rc):
    
    print("On connect called")
    print(datetime.datetime.utcnow().strftime("%m/%d/%Y, %H:%M:%S"))
    verify_on_connect(rc)

    # Subscribing in on_connect() means that if we lose the connection and
    # reconnect then subscriptions will be renewed.
    client.subscribe("telemetry")

    # Send some data
    data_payload = {arg[0]: float(arg[1]) for arg in [arg.split("=") for arg in args.payload]}
    payload = json.dumps({"points": data_payload})

    rc, mid = client.publish(topic="/telemetry", payload=payload)

    
    #mqtt_client.loop_stop()

    print("Publish result: {} messageId: {}".format(rc, mid))
    print(datetime.datetime.utcnow().strftime("%m/%d/%Y, %H:%M:%S"))


# The callback for when a PUBLISH message is sent to the server
def on_publish(client, userdata, mid):
    print("Message sent successfully with payload: {}".format(args.payload))
    print(datetime.datetime.utcnow().strftime("%m/%d/%Y, %H:%M:%S"))


# The callback for when a PUBLISH message is received from the server.
def on_message(client, userdata, msg):
    print(msg.topic + " " + str(msg.payload))

def on_disconnect(client, userdata,rc=0):
    print("DisConnected result code "+str(rc))
    mqtt_client.loop_stop()

def main():

    print("Called Python Connector with args:", args)

    if args.project_id is None:
        print("No Project ID was specified", file=sys.stderr)
        exit(1)

    if args.device_id is None:
        print("No Device ID was specified", file=sys.stderr)
        exit(1)

    mqtt_client = mqtt.Client(client_id=f"{args.project_id}.{args.device_id}", transport="websockets")
    print(rc1)
    
        #print("printing")
     mqtt_client.on_connect = on_connect
     mqtt_client.on_message = on_message
     mqtt_client.on_publish = on_publish
     mqtt_client.on_disconnect = on_disconnect

    mqtt_client.username_pw_set("none", password=args.token)
    mqtt_client.ws_set_options(path="/mqtt", headers=None)
    mqtt_client.tls_set(cert_reqs=ssl.CERT_NONE)

    try:
        print("End time")
        print(datetime.datetime.utcnow().strftime("%m/%d/%Y, %H:%M:%S"))
        
        mqtt_client.connect(args.broker, args.port, 300)
       
        
    except Exception as e:
        print("Connection failed:", e)

    # Blocking call that processes network traffic, dispatches callbacks and
    # handles reconnecting.
    # Other loop*() functions are available that give a threaded interface and a
    # manual interface.
    #print("Start time")
    #print(datetime.datetime.utcnow().strftime("%m/%d/%Y, %H:%M:%S"))
    mqtt_client.loop_forever()
    print(datetime.datetime.utcnow().strftime("%m/%d/%Y, %H:%M:%S"))
    print("End time")


if __name__ == "__main__":
    args = parse_args()
    main()

**Comment by MattBrittan** [comment]
Closing as it looks like an answer was provided (and the issue has been inactive for some time). Note that when asking questions like this it's helpful if you can provide [logs](https://github.com/eclipse/paho.mqtt.python#enable_logger).
