### ISSUE TITLE
tests missing from pypi source distribution

### ISSUE THREAD

**Issue by andir** [eclipse/paho.mqtt.python#332]
Currently the `tests` folder is missing from source distributions of this package on PyPi. I would like to be able to run the tests during the NixOS packaging.

The following additional lines within your `MANIFEST.in` should be sufficient:

```
recursive-include tests *.py
```

**Comment by andir** [comment]
I just saw that those were removed on purpose (https://github.com/eclipse/paho.mqtt.python/commit/4f3ef85dc377d6aafe3cbecbfee142c11736f318). Was there a  good reason for that?

**Comment by jamesmyatt** [comment]
I don't think that tests are typically included in PyPI distributions. If you want the tests then you can go back to the source repo (i.e. here)
