### ISSUE TITLE
Paho Client didn't connect with mqttroute.com

### ISSUE THREAD

**Issue by nikson-a** [eclipse/paho.mqtt.python#333]
I try to connect paho Client (https://www.eclipse.org/paho/clients/js/utility/) with [mqttroute.com](http://mqttroute.com), it didn't connect. The broker is running in 10443 in Non TLS mode. 
But When I run bevywise [mqtt broker](https://www.bevywise.com/mqtt-broker/)  in the my machine ( localhost), it is working fine. 
Can you help me connect to the mqttroute.com ?

Thanks in advance.
![paho_client](https://user-images.githubusercontent.com/43266690/45870552-cad65680-bda8-11e8-91ce-ebd2b551ae06.png)

**Comment by vrst37** [comment]
This is python library for mqtt, not js library. Please close this issue and ask in correct forum.
