### ISSUE TITLE
message_callback_add - multiple callbacks on same topic

### ISSUE THREAD

**Issue by hiravebapu** [eclipse/paho.mqtt.python#336]
Hello,
in my current project, we have a component. In that same component, couple of places are subscribing to same topic and each time its being subscribe, there is new callback method provided. Is this supported ? i am seeing that only last subscriber callback receives the message, not others.

**example (portion of code):**
```
def pahoo_on_message(client, userdata, msg):
    #print(msg.topic+" "+str(msg.payload))
    print("method1: "+ msg.topic + " " + str(msg.qos) + " " + str(msg.payload))

def pahoo_on_message_two(client, userdata, msg):
    print("method2: "+ msg.topic + " " + str(msg.qos) + " " + str(msg.payload))

def test():
    mqttClient.subscribe('sampleTopic',pahoo_on_message)
    mqttClient.subscribe('sampleTopic',pahoo_on_message_two)
```

**subscribe method from our wrapper class:**
```
    def subscribe(self,topic,subscribe_callback,i_qos=1):
        self.client.subscribe(topic, i_qos)
        self.client.message_callback_add(topic,subscribe_callback)
```
Any suggestion ?

**Comment by PierreF** [comment]
Hi,

no, it's not supported by message_callback_add: (quoting README about message_callback_add)
> Only one callback may be defined per literal sub string

Also not that MQTT protocol does not support multiple subscribe with the same topic ([MQTT-3.8.4-3])
> If a Server receives a SUBSCRIBE Packet containing a Topic Filter that is identical to an existing Subscription’s Topic Filter then it MUST completely replace that existing Subscription with a new Subscription. The Topic Filter in the new Subscription will be identical to that in the previous Subscription, although its maximum QoS value could be different. Any existing retained messages matching the Topic Filter MUST be re-sent, but the flow of publications MUST NOT be interrupted

Which mostly means that the most recent subscribe's qos will be used.


To workaround those limitation I would:
* If my real callbacks are fixed, only have on callback per topic and that callback dispatch to each real callbacks
* If not, store each (topic, subscribe_callback, i_qos) used in the wrapper's subscribe.
   * The message_callback_add will use a wrapper callback. This callback will use the stored couple (topic, subscribe_callback) to call each real callbacks.
   * The wrapper's subscribe will call client.subscribe with the highest i_qos stored for that topic.

**Comment by vikahl** [comment]
Is there a reason for not implementing the wrapper method in the library so that message_callback_add can support multiple callbacks?

(I am not trying to blame with "why haven't it been done" or similar, just curious what the project thinks about it and if it is worth to create a PR)

**Comment by kwesolowski** [comment]
Removing callbacks would be one example of making it harder to design nice API - if add callback actually allowed many callbacks for same topic, then removing subscriptions would not be as simple as today. 

Seems either you have unique topics and can use add/remove, or in more complex scenarios need to build sth on your own with on_message or reference counting for message_callback_add (to remove subscription when all subscribers are gone)

**Comment by pavloblindnology** [comment]
+1 vote for the functionality.

**Comment by MattBrittan** [comment]
I'm going to close this due to age/inactivity and because it looks like the OP's question was answered (if there is demand for a router than can call multiple call backs per topic then that's probably best discussed in a new issue).
