### ISSUE TITLE
Exponential backoff on message retry

### ISSUE THREAD

**Issue by vrst37** [eclipse/paho.mqtt.python#339]
Hello,

Currently the message_retry_set is set to a static value. Would it be better to implement an exponential backoff on this?

**Comment by PierreF** [comment]
If I understand correctly the use-case for this message retry, I would probably prefer to remove it completly or as very least disable it by default.
I think it's used for (quoting http://docs.oasis-open.org/mqtt/mqtt/v3.1.1/os/mqtt-v3.1.1-os.html#_Toc398718103)
> Historically retransmission of Control Packets was required to overcome data loss on some older TCP networks.

Are anyone using Python with such TCP stack ?

**Comment by vrst37** [comment]
I think we can simplify the code by following your suggestion.

**Comment by ralight** [comment]
Message retry is only allowed on reconnect not on a time basis, as per the v5.0 spec and discussions around the intention of the v3.1.1 and earlier specs, so time based reconnection has been removed and I'm closing this issue as no longer needed.
