### ISSUE TITLE
Rc - Out of memory 

### ISSUE THREAD

**Issue by ahmetalperenbulut** [eclipse/paho.mqtt.python#340]
if client disconnects, can occur "out of memory" error constantly.
The error occurs in this line
`rc = 1`  please check this assigment in code
if it is true, please change it in this way  rc = MQTT_ERRNOMEM 

Thank you..

**Comment by PierreF** [comment]
It's indeed wrong. RC = 1 is not out of memory, it's "generic error".

**Comment by bjoernbusch** [comment]
Is there any way to find out what's actually causing the disconnect? I have the issue that my client constantly disconnect after about 1 minute with error code 1. How can I drill down on the reason?

**Comment by nawab36085** [comment]
Is there any plan to fix this. I think fix is quite simple by setting rc to MQTT_ERR_CONN_LOST before passing rc to self.on_disconnect(self, self._userdata, rc) in function loop_misc. The loop_misc function later on anyway returns the right value MQTT_ERR_CONN_LOST in case of an failed ping.

**Comment by nawab36085** [comment]
Created a pull request to fix this issue: https://github.com/eclipse/paho.mqtt.python/pull/441

**Comment by drmikecrowe** [comment]
@bjoernbusch seeing a similar issue -- did you discover what the issue was?

**Comment by bjoernbusch** [comment]
it was something on the server side that the packages where not handled properly or something. I had to use a different reverse proxy on my server and now it works.

**Comment by MattBrittan** [comment]
I believe this was resolved in [this commit](https://github.com/eclipse/paho.mqtt.python/commit/332834e7ec293f1bfe385180b8691863af5a7738) (Jul 7, 2021). As such I'm going to close the issue; if the problem still exists then please free free to reopen it.
