### ISSUE TITLE
Is sleep after publish() valid way to determine if message was published?

### ISSUE THREAD

**Issue by MrBillium** [eclipse/paho.mqtt.python#341]
I am running connect_async() and want to save any messages that fail publish to disk rather that queuing them up in client. So in my main loop I am inspecting the MQTTMessagInfo returned by the publish().
It appears that If I immediately query the result of the publish then it always shows failed - which makes sense because it is non blocking and the publish takes time .

```
mqtt.loop_start()
# test main loop
x = 0
while True:
    x += 1
    sleep(5)
    message = 'hello {}'.format(x)
    msginfo = mqtt.publish(topic='/test', payload=message, qos=1)

    # need to wait here to ever see ._ published == True - why does it work?
    sleep(1)

    if mqtt.isconnected and msginfo._published:
        print('message sent ', message)
    else:
        print('message failed ', message)
```

What does not make sense to me is why  my query DOES WORK if I sleep(1) after the publish call since the msginfo has already been populated. 
Is this expected behavior ( which would be nice) or just a fluke of internal threading and not to be trusted?

**Comment by ralight** [comment]
What is happening here is that `loop_start()` starts the thread that handles the network code. `publish()` queues up a message to be published, which is handled by the network thread. The return value of publish is an object which contains information about the state of the message. The library keeps a reference to that object so it can update it once it is published.

The documentation says this about publish():

        Returns a MQTTMessageInfo class, which can be used to determine whether
        the message has been delivered (using info.is_published()) or to block
        waiting for the message to be delivered (info.wait_for_publish()). The
        message ID and return code of the publish() call can be found at
        info.mid and info.rc.

You can call `info.is_published()` after a sleep, but there is no **guarantee** that it will have worked by then. The best bet is to use `info.wait_for_publish()`, or keep on checking `is_published()` until true if you need to do other tasks.

**Comment by MrBillium** [comment]
Thanks, this makes it easy since I am publishing on a regular schedule so waiting a little after sending to see what happened is fine.

However if I add unscheduled publish calls on another thread  ( e.g. alarms that can not wait) then they could potentially happen at the same time as the regular publish calls. Will the client just handle them or do I need to be careful about contention and look at using locks etc?

**Comment by ralight** [comment]
It will just handle them, there are locks internally.

**Comment by MrBillium** [comment]
Thanks,

 

Consider adding this to documentation since published support for async operation begs the question – just how async can I go?

 

Bill

**Comment by MattBrittan** [comment]
I'm going to close this due to it's age and because it appears the original question was answered (the library has also moved on a bit since 2018).
