### ISSUE TITLE
German umlauts like "ä" ü"ö" are not supported 

### ISSUE THREAD

**Issue by HannHank** [eclipse/paho.mqtt.python#347]
Ich would like to send some german umlauts over my mqtt broker but is alway return just a weird number. Please fix this for me .

thanks

**Comment by HannHank** [comment]
import paho.mqtt.client as mqtt
# -*- encoding: utf-8 -*-
global Message 
Message = True
# Define event callbacks
def on_connect(client, userdata, flags, rc):
    print("rc: " + str(rc))

def on_message(client, obj, msg):
    global Message
    print(msg.topic + " " + str(msg.qos) + " " + str(msg.payload))
    Message = str(msg.payload)
    Message = Message[:-1] 
    Message = Message[2:] 

def on_publish(client, obj, mid):
    print("mid: " + str(mid))
    

def on_subscribe(client, obj, mid, granted_qos):
    print("Subscribed: " + str(mid) + " " + str(granted_qos))

def on_log(client, obj, level, string):
    print(string)
def state():
    global Message
    
    return Message
mqttc = mqtt.Client()
# Assign event callbacks
mqttc.on_message = on_message
mqttc.on_connect = on_connect
mqttc.on_publish = on_publish
mqttc.on_subscribe = on_subscribe

# Uncomment to enable debug messages
#mqttc.on_log = on_log



# Connect
mqttc.username_pw_set("*******", "**********************")
mqttc.connect("*******************", *******)
topic = "SH1/actor/in"
# Start subscribe, with QoS level 0
mqttc.subscribe(topic)
mqttc.loop()
# Publish a message
#mqttc.publish("SH1/actor/ATemp", "my message")

# Continue the network loop, exit when an error occurs


##if __name__ == '__main__':
 #   start()



I wrote a messager in python, and normally the code is working, but when i send Umlauts. I just get for "ä" this "\xc3\xa41" help :( sorry for my bad english :(

**Comment by ralight** [comment]
My guess is that you're expecting the payload to be a string, when in fact it is a set of bytes. Please try:

```
print(msg.payload.decode('utf-8'))
```

instead of what I presume you are doing at the moment:
```
print(msg.payload)
```

**Comment by HannHank** [comment]
Message = str(msg.payload.decode('utf-8'))
          ^
SyntaxError: invalid syntax

mhhhm do i need to import something ? :/

**Comment by ralight** [comment]
Looks like a syntax error for before that line to me...

**Comment by HannHank** [comment]
okay i was a little bit to fast :) Now it works. Thank you so much, you saved my day :)

**Comment by HannHank** [comment]
Ähm i have also another question, would it be possible to send a picture over this lib ? I guess no, but iam not sure about it .

**Comment by ralight** [comment]
Always best to open a new issue when you're asking a different question - but the answer is that MQTT doesn't do anything with its payload, so you can send text, pictures, anything you want.
