### ISSUE TITLE
can't sent big file

### ISSUE THREAD

**Issue by vic68liu** [eclipse/paho.mqtt.python#350]
Hi Team, I want to send a audio file from Raspberry ,but I can't sent the file out if the size is more than 80k.  Follow is my code.  

```
import paho.mqtt.client as mqtt
import os, time, json,sys,socket,base64
import yaml

audio_path = "/home/pi/record/"
host = "192.168.6.21"
port = 1883
keep_alive = 600


def on_connect(client, userdata, flags, rc):
    print("Connected with result code "+str(rc))


def on_message(client, userdata, msg):
    print(msg.topic+" "+str(msg.payload))


def publish_message(tile,payload,qos):
    client = mqtt.Client()
    client.on_connect = on_connect
    client.on_message = on_message
    client.connect(host, port, keep_alive)
    print(payload)
    client.publish(tile, payload=payload, qos=qos)
    client.loop_start()


def publish_audio_file():
    #audio_ab_path = record_sound()
    #f = open("/home/pi/record/audio.wav", "rb")
    f = open("/home/pi/record/test.txt","rb")
    audio_data = f.read()
    audio_bytes = bytes(audio_data)
    publish_message("voice/audio", audio_bytes, 0)
    f.close()
	
	
def encode_audio(audio_ab_path):
    f = open(audio_ab_path, "rb")
    audio_data = f.read()
    
    return base64.b64encode(audio_data)


if __name__ == "__main__":
    publish_audio_file()
```

**Comment by ZsnZeeshan** [comment]
@vic68liu I would never recommend sending files over the mqtt protocol. For audio files, you may use UDP sockets (for streaming, recorded files) or maybe TCP iff (recorded files).
You may use mqtt protocol for a handshake between the two or more devices for that purpose.

**Comment by ralight** [comment]
```
    client.loop_start()
```

The problem is that you call loop_start(), and then exit immediately. The data doesn't have chance to get sent.

I'd suggest setting up an `on_publish()` callback in which you call `client.disconnect()` - this will be called when your client has sent the message. Combine that with `loop_forever()` instead of `loop_start()` and you should be fine.

Alternatively, if you are just sending a single message at once, you could use the publish helper, which does everything for you:

```
import paho.mqtt.publish as publish

publish.single("paho/test/single", "message", hostname="test.mosquitto.org")
```

**Comment by MattBrittan** [comment]
Closing as it looks like an answer was provided (and the issue has been inactive for some time).
