### ISSUE TITLE
connection timeout

### ISSUE THREAD

**Issue by deiv23** [eclipse/paho.mqtt.python#353]
Is there any way of setting a timeout for the client.connect method?

**Comment by agm30** [comment]
I want to do the same thing. I'm having a connection timeout error as well when I try to establish connection over TLS. I initially thought the networks was slow but OpenVPN works on the same network. How can I modify the timeout value when connecting?

**Comment by vrst37** [comment]
Hello guys, from what I can understand [here](https://github.com/eclipse/paho.mqtt.python/blob/4fa31585e501a4e5b5c0d91c2dd14a0f69a6f89c/src/paho/mqtt/client.py#L993) you can just set the timeout by setting the keepalive variable. Give it a shot and see what comes of it.

**Comment by gilbertwong96** [comment]
This issue hasn't been resolved.

**Comment by azdobylak** [comment]
As a workaround you can set default socket timeout and then use `client.connect`.
```python
import socket
socket.setdefaulttimeout(timeout)
```

**Comment by creyD** [comment]
The default timeout for socket doesn't work, using `paho.mqtt.publish.single` as it probably get's overwritten by paho in the process.

**Comment by MattBrittan** [comment]
[Changes](https://github.com/eclipse/paho.mqtt.python/pull/578) have been made since this issue was raised; you can now use:

```
mqtt_client = mqtt.Client()
mqtt_client._connect_timeout = 1.0
```

I believe that this addresses the original issue so am going to close this. If you are still having problems then please raise a new issue (but please include as much information as possible including code/logs).

**Comment by Sporarum** [comment]
The issue seems to still persist in some cases: https://github.com/eclipse-paho/paho.mqtt.python/pull/876
