### ISSUE TITLE
Update DB after on_message callback

### ISSUE THREAD

**Issue by ciolo** [eclipse/paho.mqtt.python#359]
Hi everyone,
I've a problem. I'd like to update a table in my DB after that I received a message, so after _on_message_ callback. The message will be a json object and I'd like to build query dynamically, so I've to iterate on message. 
I tried but for loop not working inside _on_message_ callback. 
Any ideas?

Thank u very much.

**Comment by swails** [comment]
Your post doesn't contain any actual code, so it's impossible to tell what went wrong.

Rest assured that for loops *do* work inside any callbacks functions -- there are no arbitrary restrictions like that.

**Comment by ciolo** [comment]
Yeah, you're right sorry. This is my _on_message_ callback:
<img width="508" alt="screenshot 2019-02-10 at 10 19 03" src="https://user-images.githubusercontent.com/21953595/52531990-3b611e00-2d1e-11e9-95fa-b888d40386bb.png">
But the execution flow not enter inside for loop, I don't know why.

**Comment by vrst37** [comment]
You really should not block for that long in the on_message.

Take a look at [this](https://github.com/eclipse/paho.mqtt.python/issues/368#issuecomment-477502146).

**Comment by ralight** [comment]
The linked bug gives some good ideas to help you out, so I'm going to close this issue. If you still have problems please feel free to reopen it.
