### ISSUE TITLE
As a client, how to get the id of the publisher.

### ISSUE THREAD

**Issue by haitanghuadeng** [eclipse/paho.mqtt.python#362]
This problem has been bothering me, and I looked at the paho source code, and I still don't know what to get from on_subscribe.I don't want every publisher subject party to put its own id in the data at the time of publication.Also look for advice.

**Comment by vrst37** [comment]
So you want clientID of every publisher?? There is no provision for this in the MQTT specification. I think you will have to build this in the payload of the message, or use another communication protocol.

**Comment by haitanghuadeng** [comment]
Thank you very much for your help!
