### ISSUE TITLE
Identify broken connection

### ISSUE THREAD

**Issue by jvrahav** [eclipse/paho.mqtt.python#363]
I have a client connected to a broker. im using loop_start on the client side after connection is established. My client publishes data to the broker at scheduled intervals in a thread.

After some time if the connection to broker is lost either the broker has gone down or the network is bad, in such cases im not getting a disconnect callback.

Is there a way to figure out in the client if there is an active connection to the broker. For some reason in such cases where the broker is unreachable, i see the client stuck and not processing any message.

**Comment by tarunw07** [comment]
Can you please share your relevant code and logs?

**Comment by vrst37** [comment]
Are you using the threaded version of loop_start?

**Comment by Queuecumber** [comment]
I have the same problem with `loop_forever`. I need to be robust to broker failures for my application, and when testing by connecting to the broker, killing the broker, then restarting, my client just sits there not doing anything even after the broker is restarted. Here is relevant code:


```
def main():
    broker_address = os.environ['BROKER']
    light_controller = light.Light()

    client = mqtt.Client(client_id='...', userdata=...)

    client.will_set(availability_topic, 'offline', retain=True, qos=1)
    client.on_connect = on_connect
    client.on_message = command

    client.connect(broker_address)

    client.subscribe(command_topic)

    state(client, light_controller)

    reconnect = False
    while True:
        try:
            if reconnect:
                client.reconnect()
                reconnect = False

            client.loop_forever()
        except (socket.error, OSError):
            print('UNEXPECTED DISCONNECT')
            reconnect = True
            time.sleep(3)


if __name__ == '__main__':
    main()
```

**Comment by Queuecumber** [comment]
I'm revisiting this again to see if there's any workaround I can come up with, I don't know what relevant log files I can provide, but when I kill the server, it does see a reconnect as soon as it comes back up. The messages from my client aren't coming through. Here's the relevant server log after restarting:

```
1593972949: mosquitto version 1.6.10 starting
1593972949: Config loaded from /mosquitto/config/mosquitto.conf.
1593972949: Opening ipv4 listen socket on port 1883.
1593972949: Opening ipv6 listen socket on port 1883.
1593972951: New connection from 10.244.1.1 on port 1883.
1593972951: New client connected from 10.244.1.1 as home/test (p2, c1, k60).
```

I have set up the client to do a heartbeat, e.g. every time it receives a message it sends one on the same topic:

```
def command(client: mqtt.Client, light_controller: light.Light, message: mqtt.MQTTMessage):
    if message.topic == 'heartbeat':
        print(f'beat: {time.localtime()}')
        client.publish('heartbeat', '{}')
        return

def main():
    broker_address = os.environ['BROKER']
    light_controller = light.Light()

    client = mqtt.Client(client_id='home/test', userdata=light_controller)

    client.will_set(availability_topic, 'offline', retain=True, qos=1)
    client.on_connect = on_connect
    client.on_message = command

    client.connect(broker_address)

    client.subscribe('heartbeat')

    client.publish('heartbeat', '{}')

    client.loop_forever()
```

With this I can see the client printing up until the broker is killed, at which point it stop receiving those messages:

```
beat: time.struct_time(tm_year=2020, tm_mon=7, tm_mday=5, tm_hour=14, tm_min=23, tm_sec=16, tm_wday=6, tm_yday=187, tm_isdst=1)
beat: time.struct_time(tm_year=2020, tm_mon=7, tm_mday=5, tm_hour=14, tm_min=23, tm_sec=16, tm_wday=6, tm_yday=187, tm_isdst=1)
beat: time.struct_time(tm_year=2020, tm_mon=7, tm_mday=5, tm_hour=14, tm_min=23, tm_sec=16, tm_wday=6, tm_yday=187, tm_isdst=1)
beat: time.struct_time(tm_year=2020, tm_mon=7, tm_mday=5, tm_hour=14, tm_min=23, tm_sec=16, tm_wday=6, tm_yday=187, tm_isdst=1)
beat: time.struct_time(tm_year=2020, tm_mon=7, tm_mday=5, tm_hour=14, tm_min=23, tm_sec=16, tm_wday=6, tm_yday=187, tm_isdst=1)
beat: time.struct_time(tm_year=2020, tm_mon=7, tm_mday=5, tm_hour=14, tm_min=23, tm_sec=16, tm_wday=6, tm_yday=187, tm_isdst=1)
beat: time.struct_time(tm_year=2020, tm_mon=7, tm_mday=5, tm_hour=14, tm_min=23, tm_sec=16, tm_wday=6, tm_yday=187, tm_isdst=1)
```

If there was some way to identify the broker failing, that would be good enough to put my service into a restart loop until the broker came back up

**Comment by MattBrittan** [comment]
I'm going to close this due to its age and the fact that the OP did not provide the requested details.

@Queuecumber change your code to call `Subscribe` in `on_connect` (as shown in [this example](https://github.com/eclipse/paho.mqtt.python#getting-started)). Otherwise the subscription may be dropped if the client reconnects.
