### ISSUE TITLE
Real-time Callback Processing

### ISSUE THREAD

**Issue by dorintt** [eclipse/paho.mqtt.python#368]
Let's say I have one client publishing 10 times a second on a given topic, and another client that must process the data on that topic, but the processing takes 150 ms (more than 1/10 seconds).

Obviously, the processing client cannot keep up with the messages, so the callbacks will queue up. However, I want my client to always process the latest message, and ignore the ones that arrive while a message is still being processed (the callback didn't return yet).

What is the correct way / recommended methods to handle this problem and not have an infinitely growing callback stack?

**Comment by tarunw07** [comment]
You can create a global variable called PROCESSING = False.
And inside on message callback, 
```
if PROCESSING == False: 
    set PROCESSING = True
    start processing data in a seperate thread and ensure that after processing data you set PROCESSING to False again
else:
    pass
```

I think it would be much better if you use locks instead of PROCESSING variable

**Comment by vrst37** [comment]
Here is my recommendation:
When using callbacks, do not do any processing. Just populate a queue in the on_message callback. Then in a separate thread, you can do whatever you want. My on_message often looks like:

        def on_message(self, client, userdata, msg):
            logger.info("Received message", mqtt_msg=msg)
            mq.put(msg)


Then in another thread I do:

        msg = mq.get(block=True)
        # process msg
        # here you can empty the queue as per your requirement of only processing the latest message
        # just ignore all the msg you do not want to handle

Hope this helps.

**Comment by dorintt** [comment]
Thank you for the responses. I successfully used threading locks with threads started from the callback.

It's true that this is a more general question suited for stackoverflow, but I wanted to make sure the library doesn't already have some hidden built-in functionality to handle this automatically (for cleaner application code and / or to help newbies that are not so familiar with threading subtleties).

Here is another solution using events for when there is only one callback processing function:
```
message_data = None
callbackEvent = threading.Event()


def callback(client, userdata, message)
    global message_data
    message_data = message.payload
    callbackEvent.set()


def main()
    while True:
        callbackEvent.wait(1) # timeout after 1 second
        callbackEvent.clear()
        process_data(message_data)
```
This would have the advantage of no thread starting overhead.

**Comment by ralight** [comment]
I think that this issue has been answered, so I'm going to close it. If there's still more to add, please reopen and ask/answer away!
