### ISSUE TITLE
incorrectly reporting incorrect protocol version

### ISSUE THREAD

**Issue by jvrahav** [eclipse/paho.mqtt.python#371]
Hi,

I have a client written on paho. I have implemented callbacks for disconnect, connect.

although my client sends the message successfully, on_disconnect callback keeps getting called due to error code 1. Error code 1 refers to incorrect protocol version. Connection doesnt seem to be broken but this error message keeps coming up.

Im using emqtt version 2.1.2.

**Comment by ralight** [comment]
The documentation for the on_disconnect callback says:

```
    on_disconnect(client, userdata, rc): called when the client disconnects from the broker.
      The rc parameter indicates the disconnection state. If MQTT_ERR_SUCCESS
      (0), the callback was called in response to a disconnect() call. If any
      other value the disconnection was unexpected, such as might be caused by
      a network error.
```

So the 1 here indicates that your client is disconnecting for a reason other than you calling the `client.disconnect()` function. Error code 1 is mismatching protocol for CONNACK only.

The typical sort of problem is that people aren't calling one of the `loop*()` functions to process the background network loop. Do you have some example code you could share that shows your problem?

**Comment by jvrahav** [comment]
```
def __init__(self, config):
        # TODO: clean up call hierarchy to remove unwanted params
       self.client = mqtt.Client(self.clientId)
        self.tls_dict = {
            'ca_certs': os.path.join(somepath),
            'certfile': os.path.join(somepath),
            'keyfile': os.path.join(somepath),
            'cert_reqs': ssl.CERT_NONE,
            'tls_version': ssl.PROTOCOL_TLSv1_2}
            self.mqtt_client = None
            self.mqtt_client = mqtt.Client(self.clientId)
            self.mqtt_client.username_pw_set("user", "pass")
            self.mqtt_client.tls_set(**self.tls_dict)
            self.mqtt_client.on_disconnect = self.on_disconnect
            self.mqtt_client.on_connect = self.on_connect
            self.mqtt_client.on_publish = self.on_publish
            self.mqtt_client.on_log = self.on_log
            self.mqtt_client.connect(host=self.broker_host, port=self.broker_tcp_port, keepalive=60)
            self.mqtt_client.loop_start()

def on_connect(self, mqtt_client, userdata, flags, rc):
        log.debug("connect to data plane was invoked.")
        if rc == 0:
            self.mqtt_client.loop_start()
            log.debug("connected to data plane ...")
        else:
            error_msg = self.getErrorString(rc)
            log.error("Error occurred when trying to establish connection to data plane. %s" % error_msg)
           raise RuntimeError(error_msg)

def on_disconnect(self, mqtt_client, obj, rc):
        try:
            if rc == 0:
                log.info("disconnect request was initiated")
            else:
                if rc >= 1:
                    error_msg = self.getErrorString(rc)
                    log.error("disconnect occurred due to {}. Will attempt to reconnect".format(error_msg))
                    mqtt_client.reconnect()
        except Exception as e:
            log.error("Error occurred in disconnect callback with error {}", str(e), exc_info=True)
```

**Comment by dev00** [comment]
Can you try using loop_forever in your constructor?

I assume there is some weird state error, because when I use loop_forever (with similar code) it works, using loop_start seams to break something before on_connect returns wether the connection was successful or not.

**Comment by mjcumming** [comment]
Were you able to solve this?

**Comment by MattBrittan** [comment]
I'm going to close this due to age/inactivity (apologies for the fact that you did not get an answer back in 2019!). Please do feel free to reopen if you are still encountering the issue; however if doing so it would be really useful if you could include broker logs. A common cause of this kind of error is having two clients using the same client ID (second one connects; server drops connection to first one, first one reconnects so broker drops second etc).

Note: This is part of an exercise to clean up old issues so that the project can move forwards. Due to the number of issues being worked through mistakes will be made; please feel free to reopen this issue (or comment) if you believe it's been closed in error.
