### ISSUE TITLE
ESP32 cant connect to mosquitto broker on Raspberry pi

### ISSUE THREAD

**Issue by monthern** [eclipse/paho.mqtt.python#380]
I'm using Raspberry Pi 3 where I Installed Mosquitto broker, it is tested and working perfectly. Im trying the following code on ESP32 to connect to this Mosquitto broker but getting error code -4.  I'm getting connected to wifi but not MQTT

#include <WiFi.h> // Enables the ESP32 to connect to the local network (via WiFi)
#include <PubSubClient.h> // Allows us to connect to, and publish to the MQTT broker

// WiFi Credentials
const char* ssid = "iPhone";
const char* wifi_password = "auwz1234";

// MQTT Broker IP and Credentials

const char* mqtt_server = "169.254.135.104";
const char* mqtt_topic = "moisture";
const char* mqtt_username = "monther";
const char* mqtt_password = "mosquitto";

const char* clientID = "ESP32_Pump";
const int mqttPort = 1883;

// Initialise the Pushbutton Bouncer object
//Bounce bouncer = Bounce();

// Initialise the WiFi and MQTT Client objects
//WiFiClient wifiClient;
//PubSubClient client(mqtt_server, 1883, wifiClient); // 1883 is the listener port for the Broker

WiFiClient espClient;
PubSubClient client(espClient);

void setup() {
  
  Serial.begin(115200);

  Serial.print("Connecting to ");
  Serial.println(ssid);

  //Added by Monther on 04.may2019  WIFI_STA
  //WiFi.mode(WIFI_STA);

  // Connect to the WiFi
  WiFi.begin(ssid, wifi_password);

  // Wait until the connection has been confirmed before continuing
  while (WiFi.status() != WL_CONNECTED) {
    delay(500);
    Serial.print("Trying to connect");
  }

  // Debugging - Output the IP Address of the ESP32
  Serial.println("WiFi connected");
  Serial.print("IP address: ");
  Serial.println(WiFi.localIP());

    //Added by Monther on 04.may2019  setServer & Callback
  client.setServer(mqtt_server, mqttPort);
  //client.setCallback(callback);
}
/*
void callback(char* topic, byte* payload, unsigned int length) {
 
  Serial.print("Message arrived in topic: ");
  Serial.println(topic);
 
  Serial.print("Message:");
  for (int i = 0; i < length; i++) {
    Serial.print((char)payload[i]);
  }
 
  Serial.println();
  Serial.println("-----------------------");
 
}
*/
void loop() {
    // Connect to MQTT Broker
  if (client.connect(clientID, mqtt_username, mqtt_password)) {
    Serial.println("Connected to MQTT Broker!");
  }
  else {
    Serial.println("Connection to MQTT Broker failed...");
  }
if (client.publish(mqtt_topic, "Monther Button pressed!")) {
      Serial.println("Button pushed and message sent!");
    }
    // Again, client.publish will return a boolean value depending on whether it succeded or not.
    // If the message failed to send, we will try again, as the connection may have broken.
    else {
      Serial.println("Message failed to send. Reconnecting to MQTT Broker and trying again");
      Serial.print("failed with state ");
      Serial.print(client.state());
      client.connect(clientID, mqtt_username, mqtt_password);
      delay(10); // This delay ensures that client.publish doesn't clash with the client.connect call
      client.publish(mqtt_topic, "Monther Button pressed!");
    }
  }

**Comment by monthern** [comment]
Here is the error Im getting
Message failed to send. Reconnecting to MQTT Broker and trying again
failed with state -4Connection to MQTT Broker failed...
Message failed to send. Reconnecting to MQTT Broker and trying again
failed with state -4Connection to MQTT Broker failed...
Message failed to send. Reconnecting to MQTT Broker and trying again
failed with state -4Connection to MQTT Broker failed...
Message failed to send. Reconnecting to MQTT Broker and trying again
failed with state -4Connection to MQTT Broker failed...
Message failed to send. Reconnecting to MQTT Broker and trying again
failed with state -4Connection to MQTT Broker failed...
Message failed to send. Reconnecting to MQTT Broker and trying again
failed with state -4Connection to MQTT Broker failed...
Message failed to send. Reconnecting to MQTT Broker and trying again
failed with state -4Connection to MQTT Broker failed...
Message failed to send. Reconnecting to MQTT Broker and trying again
failed with state -4

**Comment by akx** [comment]
This does not seem to be related to the Python `paho.mqtt` library.

**Comment by MattBrittan** [comment]
Closing this as it's an issue with another library.

Note: This is part of an exercise to clean up old issues so that the project can move forwards. Due to the number of issues being worked through mistakes will be made; please feel free to reopen this issue (or comment) if you believe it's been closed in error.
