### ISSUE TITLE
multiple topics, display all at once, one each only

### ISSUE THREAD

**Issue by prankousky** [eclipse/paho.mqtt.python#386]
Hi everybody,

I am not very familiar with python in general, but kept reading about `paho-mqtt` when researching how to realize this little project I am trying to build. So I gave it a shot. Sorry if these are dumb questions; I have no background in IT and am just a self taught hobbyist, usually using bash scripts only for my workflows. 

My version is `Python 3.7.3`.

Here is what I am trying to do

* subscribe to multiple mqtt topics
* display **each topic's** *most recent* payload
* display all those payloads at the same time
* display *one* payload per topic **only**

My test script (code see below) will currently produce this output

```
battery sally => 95%
window bedroom => open
battery sally => 95%
battery sally => 95%
```

Basically what it will do is first display line 1 - 2, then after a while display line 3, then line 4. I have tried using `import os` and `os.system('clear')` in the script, but that will produce something like `battery sally => 95%`, then clear the screen, then display nothing for a while, then display `window bedroom => open`, clear the screen, display nothing, eventually display one of those lines again.

My script should always display 

```
battery sally => $payload %
window bedroom => $payload
```

When either value changes, it should 1) clear the page 2) insert each current value (if value has not changed, display last value).

This is a modified version of my script (tried to change everything to English while the original script is in German)

```
#!/usr/bin/env python3
# paho-mqtt 
import paho.mqtt.client as mqtt
# clear the screen
import os
# colorized output
from termcolor import colored

# colors
open = colored("open", "red")
closed = colored("closed", "green")

def on_connect(client, userdata, flags, rc):
    # display connection infos; irrelevant for now
    # print("Connected with result code " + str(rc))

    # this works as well
    # client.subscribe([("home/misc/vacuum/sally/stat/battery",1), ("home/oben/schlafzimmer/open/fenster/open",2)])
    client.subscribe("home/misc/vacuum/sally/stat/battery",1)
    client.subscribe("home/oben/schlafzimmer/open/fenster/open",1)

def on_message(client, userdata, msg):
    # don't display like `b'payload'` 
    msg.payload = msg.payload.decode("utf-8")
    # print(msg.topic + " " + str(msg.payload))
    # os.system('clear')
    # print("Wert ==> " + str(msg.payload))
    if msg.topic == "home/misc/vacuum/sally/stat/battery":
        print("Batterie Sally \t\t ==> \t " + str(msg.payload + "%"))
    if msg.topic == "home/oben/schlafzimmer/open/fenster/open":
        if msg.payload == "true":
            print("window bedroom \t ==> \t " + open)
        elif msg.payload == "false":
            print("window bedroom \t ==> \t " + closed)
        # print("Fenster Schlafzimmer ==> " + str(msg.payload))

# def on_message(client2, userdata, msg):
    # does this work?
    # print("Fenster Schlafzimmer: " + str(msg.payload))

client = mqtt.Client()
client.on_connect = on_connect
client.on_message = on_message

client.connect("MYIP", MYPORT, REFRESH_TIME(??))
#Set userid and password
client.username_pw_set("USERNAME", "QWERTY123_VERYSECURE")

client.loop_forever()
```

There is **a lot** to improve, but I wanted to see if the constant output of all values is possible. Once I got this done, I am planning on using a dict to automatically define what each topic should be named, for example

```
mydict = {
"battery sally": "home/misc/vacuum/sally/stat/battery",
"window bedroom": "home/oben/schlafzimmer/open/fenster/open"
(etc)
}
```

I have also tried this (`on_message` part only, rest as in script above)

```def on_message(client, userdata, msg):
    msg.payload = msg.payload.decode("utf-8")
    os.system('clear')
    sally = ""
    f_schlafz = ""
    if msg.topic == "home/misc/vacuum/sally/stat/battery":
        # print("battery sally \t\t ==> \t " + str(msg.payload + "%"))
        sally = "battery sally \t\t ==> \t " + str(msg.payload + "%\n")
    if msg.topic == "home/oben/schlafzimmer/open/fenster/open":
        f_schlafz = ""
        if msg.payload == "true":
            f_schlafz = "window bedroom \t ==> \t" + open
        elif msg.payload == "false":
            f_schlafz = "window bedroom \t ==> \t" + closed

    print(f_schlafz)
    print(sally)
```

This will **not** work. It will *only* print `window bedroom => $payload` **and an empty line underneath it**; if I put `print(sally)` above `print(f_schlafz)`, it will *only* print `battery sally => $payload %` (+ empty line underneath). No matter how I tried to construct this, it will not produce the desired output

```
window bedroom => closed
battery sally => 95%
```

The final script is supposed to have more than just those two lines; I am planning something like

```
UPSTAIRS
    bedroom
window bedroom => $payload
door bedroom => $payload
temp bedroom => $payload °C
    hallway
window hallway => $payload
door hallway => $payload
temp hallway => 
DOWNSTAIRS
    misc
battery sally => $payload %
```

Whenever any payload changes, the entire page should be cleared, then re-drawn. I thought saving each payload in a dedicated variable would do this, but I must have messed something up. 

I already have an overview like this generated by `node-red` as an html dashboard, but I'd prefer a terminal version like this that I can throw in a `tmux` window and quickly look at at any time without using a browser.

Would somebody please help me figure this out? Thanks in advance for your help :+1:

**Comment by MattBrittan** [comment]
Apologies that you did not get an answer; I'm going to close this due to age/inactivity. If you are stil having issues please feel free to reopen (but as this is not really a question that's specific to this library stackoverflow might be a better venue; this kind of question generally receives an answer quickly there).
