### ISSUE TITLE
Bad return code on failed ping

### ISSUE THREAD

**Issue by dryvenn** [eclipse/paho.mqtt.python#392]
Hello all!

Sometimes, I get a strange error code: `MQTT_ERR_NOMEM`. I grepped the source to try and understand how it was happening, but I could not find any occurrence of the error... until I came across [this line](https://github.com/eclipse/paho.mqtt.python/blob/a8b2b4d039571e9bd873dd550a1dddabc6d3cb61/src/paho/mqtt/client.py#L1481)!!

I don't think the error there was meant to be "Out of memory", maybe `1` could be replaced with `MQTT_ERR_CONN_LOST` or perhaps a new, dedicated error code?

**Comment by ralight** [comment]
I'd say you're reading too much into that value I'm afraid. The `on_disconnect` reason code is just intended as a flag to indicate whether the call was as a result of you asking to disconnect or not, nothing more. There is more meaning in the code for MQTT v5 clients, so this has almost certainly changed for that update anyway.

**Comment by dryvenn** [comment]
Okay, I understand. Thanks!
