### ISSUE TITLE
Rpi - One core completely pegged when using client.loop_start()

### ISSUE THREAD

**Issue by raghur** [eclipse/paho.mqtt.python#396]
As the title says, 1 core is completely pegged when using `client.loop_start()`
If I replace the code with the `loop()` inside a forever loop, CPU drops to 0.

Running this on a Rpi 2B+ 
```
# client.loop_start()

while 1:
  client.loop()
  try_read_data()
```

try_read_data does not have any sleep/delays. What gives?

**Comment by ralight** [comment]
If `try_read_data()` returns without any sleep or delays, then that part of your code will loop very quickly and cause the excess CPU usage you are seeing. When you include `client.loop()`, that introduces a delay into the loop as the call is waiting for network traffic.

**Comment by raghur** [comment]
:man_facepalming: That's there but that isn't the whole story. 
So I tried right now and added a 250ms, then 1s and 2s delay to `try_read_data` and even with the 2s delay, CPU is at 4.5% on a single core of the RPI.
Comparatively, with the the client.loop version CPU sits at 0.0! - so there's still a massive difference.

**Comment by MattBrittan** [comment]
I'm going to close this to age/inactivity. If you are still seeing this with the latest version please reopen and provide simple runnable demo apps for both cases (want to confirm that the issue is with the threaded loop and not something else in your code)
