### ISSUE TITLE
Any insights about next release??

### ISSUE THREAD

**Issue by bh4r4th** [eclipse/paho.mqtt.python#397]
Out of curiosity, I am asking this question. 
When can we expect the next release to be? What are the caveats in using the proxy configuration from latest project. 

However, I am able to access and try the latest paho-mqtt by doing `pip install git+https://github.com/eclipse/paho.mqtt.python.git`. Please let me know about the progress /limitations in relation to this proxy feature. 

It would be great to just include versioning in my `requirements.txt`.

**Comment by antechrestos** [comment]
:+1:

**Comment by antechrestos** [comment]
That's a good question, there has not been any activity for a long time.

For your issue, I put that line in my `requirements.txt`

`git+https://github.com/eclipse/paho.mqtt.python.git@a8b2b4d039571e9bd873dd550a1dddabc6d3cb61#egg=paho_mqtt`

And for my `Dockerfile` that does not have `git`: 

`pip install --no-cache-dir https://github.com/eclipse/paho.mqtt.python/zipball/a8b2b4d039571e9bd873dd550a1dddabc6d3cb61`

**Comment by g-escoffre** [comment]
Hi, I have exactly the same need. When can we expect a new release integration proxy management? Thanks

**Comment by MattBrittan** [comment]
Closing due to age (and the fact there have been releases since the issue was raised).
