### ISSUE TITLE
can't get messages after loop_forever

### ISSUE THREAD

**Issue by Black3rror** [eclipse/paho.mqtt.python#398]
System: ubuntu 16.04 server

### Problem explanation
I'm using this library to connect to a local mosquitto broker and subscribe to "#" and then `loop_forever`. it successfully connects to the broker and subscribes to the "#" and then gets the _retain_ messages and shows them by on_message method. then it publishes an _Online_ message and receives its own _Online_ message. then it should listen for new messages. sometimes it works perfect but **sometimes** it gets a problem.
the problem is: after showing retain messages and its own _Online_ message, it doesn't show new published messages. its noticeable that it doesn't disconnect from the broker.

### Solve the problem
by restarting the system I can solve the problem but it can happen again

### Python code
```
import paho.mqtt.client as mqtt

def on_message(client, userdata, message):
    print("message received ", str(message.payload.decode("utf-8")))
    print("message topic=", message.topic)
    print("message qos=", message.qos)
    print("message retain flag=", message.retain)
    print("\n")

	
client = mqtt.Client("MQTT2DB")
client.on_message = on_message
#client.username_pw_set("username", "password")
client.will_set("MQTT2DB/status", "Offline", 0, True)
client.connect("localhost")
client.subscribe("#")
client.publish("MQTT2DB/status", "Online", 0, True)
client.loop_forever()
```

**Comment by ralight** [comment]
"Sometimes" here probably means your network connection dropped. When the client reconnects automatically it will not re-subscribe and you have the default clean_session=True so your old session will be removed on the broker when you reconnect.

The easy way to handle this is to make your call to subscribe() in an on_connect callback.

**Comment by ralight** [comment]
I'm closing this issue because I think I've provided the answer. If not, please feel free to reopen and add more details.
