### ISSUE TITLE
client.connect() just calls connect_async()

### ISSUE THREAD

**Issue by jpwsutton** [eclipse/paho.mqtt.python#4]
migrated from Bugzilla [#484733](https://bugs.eclipse.org/bugs/show_bug.cgi?id=484733)
status UNCONFIRMED severity *major* in component *MQTT-Python* for *1.2*
Reported in version *1.1* on platform *PC*
Assigned to: Roger Light

On 2015-12-20 12:06:18 -0500, Jake Callery wrote:

> Seems as thought client.connect() simply calls client.connect_async().  This goes against what the docs claim.  connect() should be a blocking call.  Since it seems to be not, trying to subscribe (like many of the examples out there show) right after a connect call will fail because the connection has not been established before the call to subscribe.
> 
> Docs:
> https://pypi.python.org/pypi/paho-mqtt#connect-reconnect-disconnect
> "The connect() function connects the client to a broker. This is a blocking function. It takes the following arguments:"
> 
> Code:
> def connect(self, host, port=1883, keepalive=60, bind_address=""):
>         """Connect to a remote broker.
> 
>         host is the hostname or IP address of the remote broker.
>         port is the network port of the server host to connect to. Defaults to
>         1883. Note that the default port for MQTT over SSL/TLS is 8883 so if you
>         are using tls_set() the port may need providing.
>         keepalive: Maximum period in seconds between communications with the
>         broker. If no other messages are being exchanged, this controls the
>         rate at which the client will send ping messages to the broker.
>         """
>         self.connect_async(host, port, keepalive, bind_address)
>         return self.reconnect()

**Comment by ralight** [comment]
This bug report is incorrect, `connect()` calls `reconnect()` as described in the report. This is the part that carries out the blocking connect.
