### ISSUE TITLE
Duplicate message at MQTT broker

### ISSUE THREAD

**Issue by ttruongatl** [eclipse/paho.mqtt.python#400]
Hi,
I implemented Paho client in Linux. I recognize that if there are more than 20 messages in Paho client queue than we receive duplicate messages in our MQTT broker. 

the issue appears when I'm using QOS=1 and a depth of several thousand messages and it went away when I tried limiting queue depth in paho to 20 (20 was picked arbitrarily)

Is anybody facing the same issue?

**Comment by MartinRiddar** [comment]
QoS=1 is specified as "at least once delivery", meaning that you are guaranteed that the message will reach the receiver (in this case the broker) at least once. This is guaranteed by having the receiver sending a PUBACK - acknowledging that it has received the message. If the sender does not receive a PUBACK within a specified amount of time it will send the message again and that is probably what is happening in your case.
If you need each message to go through exactly once you need to use QoS=2, the HiveMQ blog has some good reading on the details https://www.hivemq.com/blog/mqtt-essentials-part-6-mqtt-quality-of-service-levels/.

**Comment by ttruongatl** [comment]
Thanks, @MartinRiddar. Your explanation makes sense to me. There is a thing that makes me a surprise that is once I changed `limiting queue depth in paho to 20` and `retry connection from 20 second as default to 120 seconds`, my issue was gone. Is it a good solution in the case I still keep QOS=1?

**Comment by MartinRiddar** [comment]
That I'm afraid is completely up to your use case so can't tell you if it is good or bad.
You didn't say what you changed the queue depth to but I'm guessing that you increased it or removed the limit completely. Just make sure that you can't end up in a situation where your queue consumes all of your RAM :)

**Comment by ttruongatl** [comment]
I tried limiting queue depth in paho to 20 actually.

> the issue appears when I'm using QOS=1 and a depth of several thousand messages and it went away when I tried limiting queue depth in paho to 20 (20 was picked arbitrarily)

**Comment by MattBrittan** [comment]
Closing this as it appears a solution was found.
