### ISSUE TITLE
will_set send message delay about 90s when the network is manually disconnected

### ISSUE THREAD

**Issue by moluzhui** [eclipse/paho.mqtt.python#401]
I use will_set() API to monitor device whether the fault which includes device offline or fault interruption.

I coding a test,  it cannot respond in time when the network is `manually disconnected`, the delay is about `90s`, but it can respond in time when I press `ctrl+c` to abort the program.

Part of the test code is as follows
```
# coding=utf8  

import paho.mqtt.client as mqtt
import time  
  
def on_connect(client, userdata, flags, rc):  
    print("Connected with result code "+str(rc))  
  
client = mqtt.Client()  
client.on_connect = on_connect  
client.will_set('test/rensanning/will', 'Last will message', 2, False)  
client.connect(cloud_mqtt_broker, cloud_mqtt_port)  
  
client.loop_start()  

while 1:
    msg = "test LWT " +time.ctime()  
    client.publish("test/rensanning/time", msg, 2)  
    print("message published ",msg)  
    time.sleep(5)
#client.disconnect()  
  
# client.loop_stop()  
print("done")
```

I wrote the code to listen for all information on the MQTT port. the result is showned as follows
ctrl+c abort the program
```
15:58:59
message received  test LWT Sat Aug  3 15:58:59 2019
message topic= test/rensanning/time
message qos= 2
message retain flag= 0
-------------------------------------------------
15:59:03
message received  Last will message
message topic= test/rensanning/will
message qos= 2
message retain flag= 0
```

I manually disconnect network by close network
`first`
```
15:59:50
message received  test LWT Sat Aug  3 15:59:50 2019
message topic= test/rensanning/time
message qos= 2
message retain flag= 0
-------------------------------------------------
16:01:20
message received  Last will message
message topic= test/rensanning/will
message qos= 2
message retain flag= 0
```
`second`
```
16:07:21
message received  test LWT Sat Aug  3 16:07:16 2019
message topic= test/rensanning/time
message qos= 2
message retain flag= 0
-------------------------------------------------
16:08:50
message received  Last will message
message topic= test/rensanning/will
message qos= 2
message retain flag= 0
```
`third`
```
16:14:36
message received  test LWT Sat Aug  3 16:14:36 2019
message topic= test/rensanning/time
message qos= 2
message retain flag= 0
-----------------------------------------------
16:16:06
message received  Last will message
message topic= test/rensanning/will
message qos= 2
message retain flag= 0
```
what causes this high latency and is so stable around 90s? I am using the ubuntu virtual machine to send mqtt messages to the ubuntu cloud server.

I would very appreciate it if you guys can suggest me some advice

**Comment by ralight** [comment]
This is simply a fact of how networking works. If you press Ctrl-C then information that the connection is closing makes its way to the broker. If you pull the network cable, the broker has to wait for the keepalive timeout to detect that the client has disconnected. You are using the default keepalive=60 seconds, and the broker waits 1.5x that value, hence 90 seconds.

**Comment by ralight** [comment]
Closing, because I don't think there is anything the library can do here.
