### ISSUE TITLE
Does paho client support ipv6? Both as local adapter and client host with ipv6 literals

### ISSUE THREAD

**Issue by bh4r4th** [eclipse/paho.mqtt.python#405]
I am curious to know whether this paho mqtt client supports ipv6 adaptor and ipv6 based routing to connect. 
At the moment I have created a class wrapper and able to initialise, connect, subscribe, set will, publish, proxy config and disconnect. 
Last 2 things I wanted to try is:
1. If my adapter is configured with ipv6 instead of ipv4
2. Can i connect to client specified with ipv6 literals.

Any insights or info about how to achieve these scenarios would be grateful.

**Comment by ralight** [comment]
Yes, it supports IPv6.
