### ISSUE TITLE
OSError(Code 24) and Attribute Error

### ISSUE THREAD

**Issue by feyzikesim** [eclipse/paho.mqtt.python#406]
Hi all,

I am using Raspberry Pi for my project that reads and sends multiple sensor datas over MQTT. About 4-5 months ago, I built a system like this;
```
## Temperature Sensor
def readSensor():
xxxxxxx

def send2Cloud():
xxxxxxx

readSensor()
send2Cloud()

```
I was running this kind of scripts in service files and restarting services within the periods I want. So simple. Devices had worked for months like this without a problem. But the CPU usage was so high, average 70-80%. So I decided to build a thread based system. Now I have one read and one send threads for each of the sensors. Once device started to work, everything is fine for about 7-8 hours but after I got these 2 errors for each sending threads.

```
Aug 23 04:02:23 raspberrypi python3[1153]:   File "/usr/local/lib/python3.7/dist-packages/paho/mqtt/client.py", line 51
Aug 23 04:02:23 raspberrypi python3[1153]:   File "/usr/local/lib/python3.7/dist-packages/paho/mqtt/client.py", line 25
Aug 23 04:02:23 raspberrypi python3[1153]:   File "/usr/lib/python3.7/socket.py", line 212, in accept                   
Aug 23 04:02:23 raspberrypi python3[1153]: OSError: [Errno 24] Too many open files  


Aug 23 04:02:23 raspberrypi python3[1153]: Exception ignored in: <function Client.__del__ at 0xb5e3ae88>                
Aug 23 04:02:23 raspberrypi python3[1153]: Traceback (most recent call last):                                           Aug 23 04:02:23 raspberrypi python3[1153]:   File "/usr/local/lib/python3.7/dist-packages/paho/mqtt/client.py", line 60
Aug 23 04:02:23 raspberrypi python3[1153]:     self._reset_sockets()                                                    Aug 23 04:02:23 raspberrypi python3[1153]:   File "/usr/local/lib/python3.7/dist-packages/paho/mqtt/client.py", line 64
Aug 23 04:02:23 raspberrypi python3[1153]:     if self._sockpairR:                                                      Aug 23 04:02:23 raspberrypi python3[1153]: AttributeError: 'Client' object has no attribute '_sockpairR' 
```

I could not find a solution on web and hope you can help me to handle this problem.

**Comment by PierreF** [comment]
Hello,

are you opening one connection per thread in your "send2Cloud" ? If yes are you opening more than ~340 connections ?
There is a known issue that paho-mqtt does not support more than ~340 connection are the same time.

**Comment by Cediddi** [comment]
~340 connection limit is an interesting limitation. I think this should be in Known Limitations part of the readme.

**Comment by feyzikesim** [comment]
> Hello,
> 
> are you opening one connection per thread in your "send2Cloud" ? If yes are you opening more than ~340 connections ?
> There is a known issue that paho-mqtt does not support more than ~340 connection are the same time.

I was disconnecting after every publish, so there was no way to have +340 connections at the same time. Anyway, I changed nothing but problem solved somehow. I do not get this error anymore. Closing the issue
