### ISSUE TITLE
On_message for Mac(Mojave and High Sierra) not working

### ISSUE THREAD

**Issue by kwalkerk** [eclipse/paho.mqtt.python#408]
I have python 2.7 code which subscribes to a topic and then does some processing based upon the message received.  This exact code runs fine on a Raspberry Pi, but when I run it on my Mac the program does not receive any of the messages.  The code on the two machines is exactly the same.

Any ideas?

**Comment by quanphuong** [comment]
maybe it's my problem, too. I create a producer on my Macbook, and `on_message` function didn't show anything.

**Comment by MattBrittan** [comment]
Closing due to age (sorry no one got back to you!), inactivity and the fact that 2.7 is no longer supported.
