### ISSUE TITLE
keepalive value of 0 causes client to enter into indefinite loop

### ISSUE THREAD

**Issue by akashgoswami** [eclipse/paho.mqtt.python#42]
In one of the test cases, keepalive option was passed to 0 
This caused MQTT client to enter into a never ending loop and it keept on creating connection with broker and destroying them. Client was stuck at following location:

```
client.py", line 1281, in loop_forever
    time.sleep(1)

```
The behavior was same with **client.connect()** functions as well as **publish** functions.

Ideally keepalive of 0 should either cause an invalid argument return or should internally revert to a default value.

**Comment by ralight** [comment]
Thanks, you're quite right. keepalive=0 is a perfectly valid setting, this code now just accepts it properly.

**Comment by akashgoswami** [comment]
Awesome! Thanks for super fast response and fix.
