### ISSUE TITLE
Is it possible to wait pause subscription until callback has returned?

### ISSUE THREAD

**Issue by muety** [eclipse/paho.mqtt.python#435]
To my understanding, as long as a client subscription to a topic exists, messages from that topic are being received as they come in and then enqueued by Paho until the `on_message` callback has run for each one of them.
I would like to know whether it is possible to wait for the blocking callback to return before accepting new messages, while knowingly "missing" messages being published to the broker in the mean time.

**Comment by ralight** [comment]
This is an old issue, I apologise! I don't like to just close issues, so here is an answer:

I would approach this by adding messages to a queue in the on_message callback, then having a separate thread to process the queue. At the end of processing one message you could completely clear the queue, which would give you the behaviour you want without risking doing anything odd to the MQTT connection.

**Comment by MattBrittan** [comment]
Closing this due to age/inactivity/solution suggested.
