### ISSUE TITLE
WebsocketConnectionError: WebSocket handshake error, connection not upgraded

### ISSUE THREAD

**Issue by supersongpeng** [eclipse/paho.mqtt.python#436]
```
import paho.mqtt.client as mqtt
def on_connect(client, userdata, flags, rc):
    print("Connected")

def on_message(client, userdata, msg):
    print(msg)

client = mqtt.Client(client_id='leisu_kr899999r998',transport="websockets")
client.on_connect = on_connect
client.on_message = on_message
client.connect("v2.push.leisu.com",8084, 60)
client.subscribe("chatroom/room_2766534")
client.loop_forever()
```

I made request to host [v2.push.leisu.com:8084](url)  ,but it threw the error as below:

Traceback (most recent call last):
  File "D:\super\Documents\11.WebCrawlers\test.py", line 17, in <module>
    client.connect("push.namitiyu.com",443, 60)
  File "C:\Users\super\Anaconda3\lib\site-packages\paho\mqtt\client.py", line 937, in connect
    return self.reconnect()
  File "C:\Users\super\Anaconda3\lib\site-packages\paho\mqtt\client.py", line 1108, in reconnect
    self._websocket_path, self._websocket_extra_headers)
  File "C:\Users\super\Anaconda3\lib\site-packages\paho\mqtt\client.py", line 3556, in __init__
    self._do_handshake(extra_headers)
  File "C:\Users\super\Anaconda3\lib\site-packages\paho\mqtt\client.py", line 3610, in _do_handshake
    "WebSocket handshake error, connection not upgraded")
paho.mqtt.client.WebsocketConnectionError: WebSocket handshake error, connection not upgraded

However, I used [http://www.tongxinmao.com/txm/webmqtt.php](url)  on Chrome to connect the [v2.push.leisu.com:8084](url) and subscribed one topic and it was connected successfully with TSL.

**Comment by christopherkuemmel** [comment]
Try to add this line: `client.tls_set()` before your **connect()** call. Since it looks like you're using TSL you have to enable this setting. 

I ran into a similar issue and this solved it for me.

**Comment by fcracker79** [comment]
Hi there,

I have the same issue with the following code:

```
        client = mqtt.Client(client_id=client_id, transport="websockets")
        client.enable_logger(logging.getLogger('paho-mqtt'))
        client.on_connect = ...
        client.on_message = ...
        client.on_log = lambda *a, **kw: self._logger.info('On log', exc_info=True)
        client.ws_set_options(path="{}?{}".format(urlparts.path, urlparts.query), headers=headers)
        client.tls_set()

        self._debug('trying to connect now....')
        client.connect(urlparts.netloc, 443)
        try:
            client.loop_forever()
        except Exception:
            self._logger.exception('Error looping forever')
            raise
        finally:
            client.disconnect()
```
It works for about 24 hours, then it fails as follows:

```
May 01 20:39:21 ip-10-0-1-121 test_chattyraspi[8022]:   File "/home/ubuntu/chattyraspi/lib/python3.6/site-packages/paho/mqtt/clie
May 01 20:39:21 ip-10-0-1-121 test_chattyraspi[8022]:     self.reconnect()
May 01 20:39:21 ip-10-0-1-121 test_chattyraspi[8022]:   File "/home/ubuntu/chattyraspi/lib/python3.6/site-packages/paho/mqtt/clie
May 01 20:39:21 ip-10-0-1-121 test_chattyraspi[8022]:     self._websocket_path, self._websocket_extra_headers)
May 01 20:39:21 ip-10-0-1-121 test_chattyraspi[8022]:   File "/home/ubuntu/chattyraspi/lib/python3.6/site-packages/paho/mqtt/clie
May 01 20:39:21 ip-10-0-1-121 test_chattyraspi[8022]:     self._do_handshake(extra_headers)
May 01 20:39:21 ip-10-0-1-121 test_chattyraspi[8022]:   File "/home/ubuntu/chattyraspi/lib/python3.6/site-packages/paho/mqtt/clie
May 01 20:39:21 ip-10-0-1-121 test_chattyraspi[8022]:     "WebSocket handshake error, connection not upgraded")
May 01 20:39:21 ip-10-0-1-121 test_chattyraspi[8022]: paho.mqtt.client.WebsocketConnectionError: WebSocket handshake error, conne
May 01 20:39:21 ip-10-0-1-121 test_chattyraspi[8022]: 2020-05-01 20:39:21,194 - paho-mqtt - DEBUG - Connection failed, retrying
May 01 20:39:23 ip-10-0-1-121 test_chattyraspi[8022]: 2020-05-01 20:39:23,207 - client.raspi.alexa.mirko.io - INFO - On log
May 01 20:39:23 ip-10-0-1-121 test_chattyraspi[8022]: Traceback (most recent call last):
May 01 20:39:23 ip-10-0-1-121 test_chattyraspi[8022]:   File "/home/ubuntu/chattyraspi/lib/python3.6/site-packages/paho/mqtt/clie
May 01 20:39:23 ip-10-0-1-121 test_chattyraspi[8022]:     self.reconnect()
May 01 20:39:23 ip-10-0-1-121 test_chattyraspi[8022]:   File "/home/ubuntu/chattyraspi/lib/python3.6/site-packages/paho/mqtt/clie
May 01 20:39:23 ip-10-0-1-121 test_chattyraspi[8022]:     self._websocket_path, self._websocket_extra_headers)
May 01 20:39:23 ip-10-0-1-121 test_chattyraspi[8022]:   File "/home/ubuntu/chattyraspi/lib/python3.6/site-packages/paho/mqtt/clie
May 01 20:39:23 ip-10-0-1-121 test_chattyraspi[8022]:     self._do_handshake(extra_headers)
May 01 20:39:23 ip-10-0-1-121 test_chattyraspi[8022]:   File "/home/ubuntu/chattyraspi/lib/python3.6/site-packages/paho/mqtt/clie
May 01 20:39:23 ip-10-0-1-121 test_chattyraspi[8022]:     "WebSocket handshake error, connection not upgraded")
```
From this point on, it does not get out of this situation and the client does not receive any notification.
If I reboot the whole script, it works, but it seems to be a very bad hack.

**Comment by MattBrittan** [comment]
I'm going to close this due to age/inactivity (please feel free to reopen it if you are still encountering the issue and can provide further details).

When raising this kind of issue it's really useful if you can provide full details of the working connection (e.g. a screenshot of `http://www.tongxinmao.com/txm/webmqtt.php` showing the working config). I tried to connect myself but `v2.push.leisu.com` does not resolve. There are a range of possible issues here and often different users get the same error but for differing reasons (particularly when connecting to differing servers).
