### ISSUE TITLE
Error loading plugin paho-mqtt

### ISSUE THREAD

**Issue by stefanbschneider** [eclipse/paho.mqtt.python#452]
I'm using `tavern` for API testing, which internally apparently uses `paho-mqtt`. Currently, I'm getting the following error when running my tests:

```
E   tavern.util.exceptions.PluginLoadError: Error loading plugin paho-mqtt = tavern._plugins.mqtt.tavernhook - [Errno 20] Not a directory: '/usr/local/lib/python3.6/site-packages/tavern-0.26.1-py3.6.egg/tavern/_plugins/mqtt/schema.yaml'
```

I'm using versions

```
paho-mqtt==1.3.1
tavern==0.26.1
```

Strangely, the tests pass fine when executing them locally and the error only occurs when building and running them in Docker containers, eg, in Jenkins.

* Container build: https://github.com/sonata-nfv/tng-sdk-project/blob/master/pipeline/build/build.sh
* Unit tests: https://github.com/sonata-nfv/tng-sdk-project/blob/master/pipeline/unittest/test.sh

I further described the issue here: https://github.com/taverntesting/tavern/issues/314

**Comment by MattBrittan** [comment]
Closing this as it looks like the issue was sorted on the tavern repo.
