### ISSUE TITLE
Force close sockets after use

### ISSUE THREAD

**Issue by kaizensparc** [eclipse/paho.mqtt.python#453]
Hello, 
I'm using the library in a long-running script where I frequently connect/disconnect to brokers. After a few hours/days, I cannot connect anymore due to "too many open files" error. In fact after checking the open sockets with `lsof` I end up with hundreds of open sockets when idle.

It seems the MQTT client class relies on `__del__` method (and thus in the garbage collector) to close the sockets, which gives unpredictable results. Is there any way to force close the sockets when disconnecting? I was thinking maybe exporting the `_reset_sockets` method?

Thanks

**Comment by kevalRPansuriya** [comment]
I am experiencing the same issue I am performing a test where I disconnect from the broker every 30 seconds this left too many open sockets which is not getting closed in my case.

**Comment by MattBrittan** [comment]
I'm going to close this due to inactivity (the library has changed since this was raised). Please feel free to reopen, but if you do please provide a minimal example and details about your environment (OS etc).
