### ISSUE TITLE
why connect() returns but connection is not established?

### ISSUE THREAD

**Issue by charleshuangcai** [eclipse/paho.mqtt.python#454]
paho version is 1.5.0, python 3.8
code example:
client.connect(host=self.__profile.get_host(), port=self.__profile.get_port(),
                                       keepalive=self.__profile.get_keep_alive_interval())
client.loop_start()
client.is_connected()

but client.is_connect() reslut is false.  why sync method connect returns but connection is not established?

**Comment by Smuu** [comment]
Have the same problem and can't find a solution.

**Comment by Smuu** [comment]
I have another python script to publish data to mqtt.

```
client.connect(host, port)
client.is_connected()
client.publish(topic, message)
client.disconnect()
```

client.is_connected() returns False but data get published to the mqtt broker.

**Comment by cjdcordeiro** [comment]
same here

**Comment by billimek** [comment]
observing the same behavior

**Comment by Smuu** [comment]
For me was the problem, that I used websockets at the mqtt broker and forgot to specify that while creating the client.

**Comment by Smuu** [comment]
For me was the problem, that I used websockets at the mqtt broker and forgot to specify that while creating the client.

**Comment by denravonska** [comment]
Same issue here. `connect` is asynchronous and requires an event loop. That defeats the purpose of a synchronous variant.

**Comment by dxmann** [comment]
I'm working with AWSIoT.
After understanding that is not useful set the CA cert path, I have encountered your same problem. Looking on called callbacks I have on_disconnected called with error code 1: as wrote [here](http://www.steves-internet-guide.com/client-connections-python-mqtt/), 1 is "Connection refused – incorrect protocol version".
so I set the protocol to MQTTv311, the only one used by AWSIot, but with the same result.

**Comment by eohlde** [comment]
Same issue here. is_connected() always returns False, but MQTT data is being published. I have also overridden the on_connect and on_disconnect callbacks and they are never triggered.

**Comment by wanZzz6** [comment]
Have the same problem

**Comment by Haifischbecken** [comment]
Ran into the same problem, I didn't know that calling `client.tls_set_context()` or `client.tls_set()` was necessary as it wasn't part of any introduction I found online and I'm quit new to this whole networking thing.

**Comment by chengchenglee** [comment]
> 
> 
> I'm working with AWSIoT. After understanding that is not useful set the CA cert path, I have encountered your same problem. Looking on called callbacks I have on_disconnected called with error code 1: as wrote [here](http://www.steves-internet-guide.com/client-connections-python-mqtt/), 1 is "Connection refused – incorrect protocol version". so I set the protocol to MQTTv311, the only one used by AWSIot, but with the same result.

Same here.
I am using aws iot mqtt for data transmit.

I am using mqtt_bridge.

every time , the _on_disconnect_ will give the response code 1 back .

I do not know how to solve it.
I also raised a question here.
https://github.com/groove-x/mqtt_bridge/issues/61

**Comment by FeroxTL** [comment]
Made cool workaround:

```python

def connect():
    client = mqtt.Client()
    client.connect(host="host", port="port")

    started = time.time()
    while time.time() - started < 5.0:
        client.loop()
        if client.is_connected():
            return client

    raise OSError('Not connected')
```

**Comment by MattBrittan** [comment]
Closing this because my PR (#615) to update the documentation has now been accepted. Hopefully that will clarify things a bit!

**Comment by stefan-sherwood** [comment]
I had this same problem and I updated my code to start the network traffic processing thread and the connected state now shows correctly.

```
import paho.mqtt.client as mqtt
client = mqtt.Client( mqtt.CallbackAPIVersion.VERSION2, "my_device" )
client.connect( 'my_mqtt_server.lan' )
client.loop_start()
```

There are multiple loop functions, [documented in the main documentation](https://github.com/eclipse-paho/paho.mqtt.python#network-loop) and included in the example code. If you don't use them a bunch of things, including `client.is_connected()` do not work properly.

Note that `client.is_connected()` is updated asynchronously so its value immediately after connecting is not reliable.
