### ISSUE TITLE
Docstring for client.proxy_set()

### ISSUE THREAD

**Issue by lxnzr** [eclipse/paho.mqtt.python#461]
The new SOCKS proxy support in v1.5.0 is great, thanks for the effort that went into it. 

The proxy_set method's documentation seems to be missing the `proxy_port` parameter, though, which when missing leads to a silent failure rather than either raising an exception or using a default.

I figured this out by reading the _get_proxy() implementation, but only after trying to chase down other problems in my test setup.

https://github.com/eclipse/paho.mqtt.python/blob/master/src/paho/mqtt/client.py#L871
```
    proxy_type: One of {socks.HTTP, socks.SOCKS4, or socks.SOCKS5}
    proxy_addr: IP address or DNS name of proxy server
```

https://github.com/eclipse/paho.mqtt.python/blob/master/src/paho/mqtt/client.py#L3645
```
    "proxy_type": socks.SOCKS5,
    "proxy_addr": parts.hostname,
    "proxy_port": parts.port
```

I don't have time to do a PR today, but if no one else does either, I'm happy to come back to it later in the week. (Also, the section of _get_proxy() I quoted isn't actually where the parameter gets used, it's just an alternate way of setting it. Someone familiar with the implementation could document the usage more accurately than me.)

**Comment by MattBrittan** [comment]
PR updating docs has now been committed so closing this issue.
