### ISSUE TITLE
socket.error: [Errno 104] Connection reset by peer

### ISSUE THREAD

**Issue by bkrajendra** [eclipse/paho.mqtt.python#467]
Recently I am getting this error from the python client on my one of the VPS

```
Traceback (most recent call last):
  File "mqtt.py", line 30, in <module>
    client.connect("MYSECRET.MQTT.BROKER", 8883, 60)
  File "/usr/lib/python2.7/site-packages/paho/mqtt/client.py", line 937, in connect
    return self.reconnect()
  File "/usr/lib/python2.7/site-packages/paho/mqtt/client.py", line 1100, in reconnect
    sock.do_handshake()
  File "/usr/lib64/python2.7/ssl.py", line 831, in do_handshake
    self._sslobj.do_handshake()
socket.error: [Errno 104] Connection reset by peer
```

Settings is very simple.
I have my mqtt broker (mosquitto) on one VPS and I am connecting it from python client on another VPS. Everything was working fine till I ran update on both machines.
Or dont know what triggered this.

code I am using is:
```
#!/usr/bin/env python
# -*- coding: utf-8 -*-
#Author : Rajendra Khope
import paho.mqtt.client as mqtt
import ssl
import sys

user = "IAMNOTTELLINGYOU"
passw ="IAMNOTTELLINGYOU"
# The callback for when the client receives a CONNACK response from the server.
def on_connect(client, userdata, flags, rc):
	print("Connected with result code "+str(rc))
	client.subscribe("testings")

# The callback for when a PUBLISH message is received from the server.
def on_message(client, userdata, msg):
	print "Topic: ", msg.topic+"\nMessage: "+str(msg.payload)

client = mqtt.Client()
client.tls_set()
client.tls_insecure_set(True) 

client.username_pw_set(user,passw)
client.on_connect = on_connect
client.on_message = on_message

client.connect("HIDDENSERVER", 8883, 60)
client.publish("data/deviceInfo", "Hello", qos=0, retain=False)

```

Most important thing is that same code if I run it from my local machine works fine.
All other type of clients (Secure Websocket from browser, mqtt ssl from android and other ) works fine with my borker.
Only connection from this specific VPS with this above code does not work.
On broker I get log:
```
Client connection from CLIENTVPSIP failed: error:140760FC:SSL routines:SSL23_GET_CLIENT_HELLO:unknown protocol.

```
Pleas help to resolve this issue.

**Comment by bkrajendra** [comment]
Temporarily I have resolve the issue by changing my transport to `websockets`

```client = mqtt.Client(transport="websockets")```
and changing port to secure websocket.

**Comment by MattBrittan** [comment]
Apologies for the lack of response on this. Unfortunately, due to the issues age, I'm going to close it (because it's likely that both machines have been updated a number of times since this was logged).

If you are still having issues please reopen the isue and provide the OS and version of each machine and the output of `openssl version` (my guess is that one of the machines was updated to a version that raised the minimum TLS version supported to a level above what the other one supported - that's just a guess tho!).
