### ISSUE TITLE
How to add message_callback_add() in client_sub-class.py?

### ISSUE THREAD

**Issue by vvksahoo** [eclipse/paho.mqtt.python#468]
I was going through this example folder scripts . Ocean of Thanks , its save lot of times . I would like to follow  "paho.mqtt.python/examples/client_sub-class.py " this scripts . I have one silly doubts that how can we add message_callback_add() in this scripts ?

**Comment by makoit** [comment]
I have the same question. I tried this in the class __init__ cunction

`
import paho.mqtt.client as mqtt
import uuid


# implementation
class MqttClient(mqtt.Client):

    def __init__(self, client_name, log=True, **kwargs):

        #  own MqttClient class inherit all the methods and properties from mqtt.Client
        super(MqttClient, self).__init__(client_name + "_" + str(uuid.uuid1()), **kwargs)

        # assign event handlers to client instance
        self._on_connect = self.on_connect
        self._on_message = self.on_message
        self._on_publish = self.on_publish
        self._on_subscribe = self.on_subscribe

        # if true enable debug messages
        if log:
             self._on_log = self.on_log

    # Define event callbacks

    def mqtt_on_connect(self, userdata, flags, rc):
        # value of rc determines success or not
        if rc == 0:
            print("on_connect: client connection successful")
        elif rc == 1:
            print("on_connect: client connection refused - incorrect protocol version")
        elif rc == 2:
            print("on_connect: client connection refused - invalid client identifier")
        elif rc == 3:
            print("on_connect: client connection refused - server unavailable")
        elif rc == 4:
            print("on_connect: client connection refused - bad username or password")
        elif rc == 5:
            print("on_connect: client connection refused - not authorised")

    def mqtt_on_message(self, obj, msg):
        print(msg.topic + " " + str(msg.qos) + " " + str(msg.payload))

    def mqtt_on_publish(self, obj, mid):
        print("mid: " + str(mid))

    def mqtt_on_subscribe(self, obj, mid, granted_qos):
        print("Subscribed: " + str(mid) + " " + str(granted_qos))

    def mqtt_on_log(self, obj, level, string):
        print(string)

    # client methods


    def client_run(self, hostname, port_num, keep_alive=60):
        self.connect(host=hostname, port=port_num, keepalive=keep_alive)
        rc = 0
        while rc == 0:
            rc = self.loop()
        return rc

    def client_connect(self, hostname, port_num, keep_alive=60):
        self.connect(host=hostname, port=port_num, keepalive=keep_alive)

    def client_disconnect(self):
        self.disconnect()
    

`

But it does not work. It looks like the handlers are never called... I can not see any log in my command line...

Is there any solution?

Thanks

**Comment by MattBrittan** [comment]
I'm not really clear what the issue is here; the following works fine for me:

```
import paho.mqtt.client as mqtt


class MyMQTTClass(mqtt.Client):

    def on_connect(self, mqttc, obj, flags, rc):
        print("rc: "+str(rc))

    def blah(self, mqttc, userdata, message):
        print("blah got message on topic: " + message.topic)

    def run(self):
        self.connect("mqtt.eclipseprojects.io", 1883, 60)
        self.message_callback_add("$SYS/#", self.blah)
        self.subscribe("$SYS/#", 0)

        rc = 0
        while rc == 0:
            rc = self.loop()
        return rc


# If you want to use a specific client id, use
# mqttc = MyMQTTClass("client-id")
# but note that the client id must be unique on the broker. Leaving the client
# id parameter empty will generate a random id for you.
mqttc = MyMQTTClass()
rc = mqttc.run()

print("rc: "+str(rc))
```

Given the age of this issue and the above solution I'm going to close it.

Note: This is part of an exercise to clean up old issues so that the project can move forwards. Due to the number of issues being worked through mistakes will be made; please feel free to reopen this issue (or comment) if you believe it's been closed in error.
