### ISSUE TITLE
Publish returns success if wrong credentials are used and message is not delivered.

### ISSUE THREAD

**Issue by axmag** [eclipse/paho.mqtt.python#475]
### Context
The publish function returns MQTT_ERR_SUCCESS when wrong combination of login/password is used. 

### How to reproduce
Run following code with correct ip address of the server and login/password with correct combination in the first call of username_pw_set and wrong login or password in the second call of username_pw_set.

> import paho.mqtt.client as paho
broker="192.168.1.80"
port=1883
mosquitto = paho.Client("client1")
mosquitto.username_pw_set("login name","correct password")
mosquitto.connect(broker,port)                          
res1= mosquitto.publish("topic1","message1")
print("Return with correct credentials: " + str(res1.rc))
mosquitto.disconnect
mosquitto.username_pw_set("login name","wrong password")
mosquitto.connect(broker,port)                          
res2 = mosquitto.publish("topic2","message2")
print("Return with wrong credentials: " + str(res2.rc))
mosquitto.disconnect

### Additional note
MQTT_ERR_SUCCESS = 0 returned in rc in both cases.
 
What's wrong here? Do I understand it correctly as a bug?
Thanks a lot!

**Comment by MattBrittan** [comment]
I'm going to close this because I believe the updated docs now offer a better explanation (and all of the examples include a network loop).
