### ISSUE TITLE
How to make multiple broker connection in paho mqtt?

### ISSUE THREAD

**Issue by vvksahoo** [eclipse/paho.mqtt.python#477]
I want to connect to multiple broker , so does paho_mqtt handle it ?

**Comment by mbenabda** [comment]
do you know in advance which servers you'll be connected to or is it a HA scenario ?you need 1 socket / broker connection. have you tried using multiple client instances ?

**Comment by andrequeiroz2** [comment]
> você sabe com antecedência a quais servidores estará conectado ou é um cenário de HA?
> se fizer isso, você precisará de 1 conexão de soquete / corretor. você já tentou usar várias instâncias do cliente?


I'm trying to do this. In my case, I want the user to register several bokers.

**Comment by MattBrittan** [comment]
This is not something the library supports out of the box. Please see [this issue](https://github.com/eclipse/paho.mqtt.python/issues/308#issuecomment-406990125) for one suggestion (I have not tested this).

Given this issues age I'm going to close it (hopefully the above helps, if not and this is still a problem for you feel free to reopen).
