### ISSUE TITLE
How to implement a subclass of paho.mqtt.client.Client with custom constructor?

### ISSUE THREAD

**Issue by prouschal** [eclipse/paho.mqtt.python#479]
I tried to subclass `paho.mqtt.client.Client` and override `on_connect` and `on_message`.

Unfortunately this stops working after a custom `__init__` method was added, because the callbacks are all reset in the calll to `super().__init__(...)`.

I then tried to manually set this.on_connect to MySubClass.on_connect in the constructor but that is not quite a good solution, as then any subclass of MySubclass will run into a similar problem.

Is there a way to make this work properly?

The workaround in my case was to make the client a member of my class and not use inheritance.
I just wonder whether I overlooked something and there is a simpler solution after all.

**Comment by alexander-travov** [comment]
Look at `examples/client_sub-class.py`.

Don't forget to add `self` argument to your callback methods so:
``` python
def on_message(client, userdata, message):
    ...
```
becomes:
``` python
class MyClient(paho.mqtt.client.Client):
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        # custom initialization
    def on_message(self, client, userdata, message):
        ...
```

**Comment by MattBrittan** [comment]
Closing due to age/inactivity and the fact that it looks like an answer was provided.
