### ISSUE TITLE
PUBREL handling error in MQTT v5

### ISSUE THREAD

**Issue by sutao** [eclipse/paho.mqtt.python#481]
When using MQTT v5 broker and subscribing to a QoS 2 topic, there seems to be an issue handling `PUBREL` packets, specifically:

```py
    def _handle_pubrel(self):
        if self._in_packet['remaining_length'] != 2:  # <-- remaining_lenth is 4 for PUBREL packets.
            return MQTT_ERR_PROTOCOL
```

This causes a silent reconnection.

According to the official MQTT v5 protocol here: https://docs.oasis-open.org/mqtt/mqtt/v5.0/cos02/mqtt-v5.0-cos02.html#_Toc1477441

It appears `PUBREL` header should indeed be 4 bytes. In MQTT v3.1.1, this header is 2 bytes.

The two additional bytes are for **PUBREL Reason Code** and **Property Length**. 
Currently, I subclassed the `Client` class on my own application so it's compatible with v5 brokers. 

I did my tests on emqx. Mosquitto seems to be fine (which means it did not support full v5 protocol).

**Comment by ralight** [comment]
Mosquitto allows the pubrel reason code and property length bytes to be omitted, as allowed by the MQTT v5.0 specification just a little bit on from where you quote, so perhaps it is emqx that doesn't fully support v5 :)

This is indeed a bug in the Python client though.

**Comment by sutao** [comment]
Ah I see... yeah the client should be able to support 2 or 4 bytes of Remaining Length in the fixed header then.

**Comment by naknz** [comment]
Using emqx with the client there is now an unpack buffer error.

It's the same issue related to v5 clients and the variable header having more than 2 bytes.
Just the unpack expecting 2 bytes and getting 4 instead so throwing the exception.

Worked around with just taking the first 2 bytes:
`mid, = struct.unpack("!H", self._in_packet['packet'][:2])`
