### ISSUE TITLE
loop() function does not clear TCP buffer

### ISSUE THREAD

**Issue by spynappels** [eclipse/paho.mqtt.python#484]
I'm running an application in Python 3.7.3 using the Paho MQTT module version 1.5.0 on a Raspberry Pi3.
It subscribes to a Mosquitto broker and displays the data from messages received for the subscribed topics on an attached screen.

I've noticed that after some time it simply stops updating the values, and after some investigation it was seen that the client device is simply closing the TCP connection with a RST packet.
It turns out that when I use the non-blocking loop() method in a while loop, it does not seem to clear the  bytes from the TCP buffer. Running netstat -tn every second shows the Recv-Q counter increasing by 26 bytes for every message received.

Using the loop_forever() function, the Recv-Q counter does not increment and the script continues to work as expected, but this doesn't work for the application.

Is there anything additional required when using the loop() method as opposed to using the loop_forever() method? Or is there some bug in the loop() method?

I can provide supporting tcpdumps and netstat output or any debug output required.

**Comment by spynappels** [comment]
In this pcap, 192.168.10.60 is the MQTT broker, and 192.168.13.190 is the device running the Python code.
[mqtt-broker-traffic-extract.zip](https://github.com/eclipse/paho.mqtt.python/files/4463362/mqtt-broker-traffic-extract.zip)
The netstat output is as follows:

> pi@office-control:~ $ date; netstat -nt
> Fri 10 Apr 2020 09:51:24 PM BST
> Active Internet connections (w/o servers)
> Proto Recv-Q Send-Q Local Address           Foreign Address         State
> tcp        0      0 192.168.13.190:22       192.168.13.192:49859    ESTABLISHED
> tcp        0      0 192.168.13.190:22       192.168.13.192:60822    ESTABLISHED
> tcp        0      0 127.0.0.1:37446         127.0.0.1:40005         ESTABLISHED
> tcp        0      0 192.168.13.190:22       192.168.13.192:60842    ESTABLISHED
> tcp     1874      0 192.168.13.190:49005    192.168.10.60:1883      ESTABLISHED
> tcp        0      0 192.168.13.190:22       192.168.13.192:49842    ESTABLISHED
> tcp        0      0 192.168.13.190:22       192.168.13.192:49843    ESTABLISHED
> tcp        0     48 192.168.13.190:22       192.168.13.192:49858    ESTABLISHED
> tcp        0      0 127.0.0.1:37767         127.0.0.1:46902         ESTABLISHED
> tcp        0      0 127.0.0.1:40005         127.0.0.1:37446         ESTABLISHED
> tcp        0      0 127.0.0.1:34321         127.0.0.1:55006         ESTABLISHED
> tcp        0      0 192.168.13.190:22       192.168.13.192:60819    ESTABLISHED
> tcp        0      0 127.0.0.1:55006         127.0.0.1:34321         ESTABLISHED
> tcp        0      0 127.0.0.1:46902         127.0.0.1:37767         ESTABLISHED
> pi@office-control:~ $ date; netstat -nt
> Fri 10 Apr 2020 09:51:29 PM BST
> Active Internet connections (w/o servers)
> Proto Recv-Q Send-Q Local Address           Foreign Address         State
> tcp        0      0 192.168.13.190:22       192.168.13.192:49859    ESTABLISHED
> tcp        0      0 192.168.13.190:22       192.168.13.192:60822    ESTABLISHED
> tcp        0      0 127.0.0.1:37446         127.0.0.1:40005         ESTABLISHED
> tcp        0      0 192.168.13.190:22       192.168.13.192:60842    ESTABLISHED
> tcp     1926      0 192.168.13.190:49005    192.168.10.60:1883      ESTABLISHED
> tcp        0      0 192.168.13.190:22       192.168.13.192:49842    ESTABLISHED
> tcp        0      0 192.168.13.190:22       192.168.13.192:49843    ESTABLISHED
> tcp        0     48 192.168.13.190:22       192.168.13.192:49858    ESTABLISHED
> tcp        0      0 127.0.0.1:37767         127.0.0.1:46902         ESTABLISHED
> tcp        0      0 127.0.0.1:40005         127.0.0.1:37446         ESTABLISHED
> tcp        0      0 127.0.0.1:34321         127.0.0.1:55006         ESTABLISHED
> tcp        0      0 192.168.13.190:22       192.168.13.192:60819    ESTABLISHED
> tcp        0      0 127.0.0.1:55006         127.0.0.1:34321         ESTABLISHED
> tcp        0      0 127.0.0.1:46902         127.0.0.1:37767         ESTABLISHED
> pi@office-control:~ $ date; netstat -nt
> Fri 10 Apr 2020 09:51:33 PM BST
> Active Internet connections (w/o servers)
> Proto Recv-Q Send-Q Local Address           Foreign Address         State
> tcp        0      0 192.168.13.190:22       192.168.13.192:49859    ESTABLISHED
> tcp        0      0 192.168.13.190:22       192.168.13.192:60822    ESTABLISHED
> tcp        0      0 127.0.0.1:37446         127.0.0.1:40005         ESTABLISHED
> tcp        0      0 192.168.13.190:22       192.168.13.192:60842    ESTABLISHED
> tcp        0      0 192.168.13.190:22       192.168.13.192:49842    ESTABLISHED
> tcp        0      0 192.168.13.190:22       192.168.13.192:49843    ESTABLISHED
> tcp        0    160 192.168.13.190:22       192.168.13.192:49858    ESTABLISHED
> tcp        0      0 127.0.0.1:37767         127.0.0.1:46902         ESTABLISHED
> tcp        0      0 127.0.0.1:40005         127.0.0.1:37446         ESTABLISHED
> tcp        0      0 127.0.0.1:34321         127.0.0.1:55006         ESTABLISHED
> tcp        0      0 192.168.13.190:22       192.168.13.192:60819    ESTABLISHED
> tcp        0      0 127.0.0.1:55006         127.0.0.1:34321         ESTABLISHED
> tcp        0      0 127.0.0.1:46902         127.0.0.1:37767         ESTABLISHED
> pi@office-control:~ $ 
> 

The Recv-Q increments in 26 byte steps, which is the same as the MQTT payload as can be seen in the pcap.

**Comment by ralight** [comment]
How frequently are you calling `loop()`? Could you use `loop_start()` instead to start a new thread which handles it for you?
