### ISSUE TITLE
How can I send a message with publish packet?

### ISSUE THREAD

**Issue by xZurdo** [eclipse/paho.mqtt.python#487]
I mean, I am trying to publish the measurements of a flow meter sensor, and I don't know how to encode this measurements to be sent properly through MQTT protocol using publish. Has someone any idea to do it?

I have measures like this: 4'5; 1.'3; 0'43

And the problem is that I don't know how to send that in the publish packet

**Comment by castillo92** [comment]
Using Python it is very simple:

Sending multiple messages
```
    msgs = [{'topic': topic, 'payload': mensaje1},
            (topic, mensaje2, 0, False),
            (topic, mensaje3, 0, False),
            (topic, mensaje4, 0, False)]
    
    
    while True:
        print(".")
        mqtt_publish.multiple(msgs, hostname="localhost", port=1883,auth = {'username':"user_MQTT", 'password':"casa"})
        
        time.sleep(1)
```

**Comment by xZurdo** [comment]
> Using Python it is very simple:
> 
> Sending multiple messages
> 
> ```
>     msgs = [{'topic': topic, 'payload': mensaje1},
>             (topic, mensaje2, 0, False),
>             (topic, mensaje3, 0, False),
>             (topic, mensaje4, 0, False)]
>     
>     
>     while True:
>         print(".")
>         mqtt_publish.multiple(msgs, hostname="localhost", port=1883,auth = {'username':"user_MQTT", 'password':"psw"})
>         
>         time.sleep(1)
> ```

**Comment by xZurdo** [comment]
Sorry I didn't explain my situation at all. I am using a STM32 microcontroller with a GPRS Module SIM800L, so I have to send this publish message using TCP/IP protocol through SIM800L and I have to generate the MQTT publish packet and I am having problems with this. Do you have any other idea to solve the problem? Thank you very much for your help.

**Comment by castillo92** [comment]
> s. Do you have any other idea to solve the problem? Thank you very much for your help.

Sorry but I do not know that microcontroller. In what language do you make the program? 

I saw in internet that SIM800L works with AT commands... Could you search how to send data with it. I do not know nothing about it, sorry.

**Comment by ralight** [comment]
It seems like this is out of scope for the Paho Python client, so I'm going to close this issue. If you disagree, please reopen and add more details about your Python code.
