### ISSUE TITLE
Able to publish long payload with mqtt-spy but not with paho.mqtt.python 

### ISSUE THREAD

**Issue by graftedlife** [eclipse/paho.mqtt.python#490]
Hi All,

I need to regularly publish payloads with a string length of ca. 125500 (~70KB). While I successfully did so with mqtt-spy, I constantly found I couldn't make it in Python using paho.mqtt.python (version 1.3.1), for any payload of a length longer than 85395.

Did I miss any parameter setting for the max. length allowed in paho.mqtt.python? I'd appreciate any advice!

**Comment by MartinRiddar** [comment]
I'm guessing its a long shot but have you tried with version 1.4 or 1.5? 1.3.1 is getting close to 3 years old by now.

**Comment by graftedlife** [comment]
Yes I tried 1.5.0 but it doesn't work either... Does paho.mqtt.python come with any parameter setting for the max. length allowed in a message?

**Comment by ralight** [comment]
Are you definitely calling loop_start() or loop_forever()? If not, you'll have problems. Have you got some example code that exhibits this behaviour? I just tested with an 800kB message and had no problems.

**Comment by ralight** [comment]
I'm going to close this issue, if it's still a problem please reopen and add more details.
