### ISSUE TITLE
At reconnect, the client doesn't seem to take max_inflight_messages into account

### ISSUE THREAD

**Issue by LOorts-Aloxy** [eclipse/paho.mqtt.python#492]
Hi,
We've been using your service for some time now and are very happy about the results. Thanks for this! 

Our setup is the following:
Sensor - (Dash 7)-> gateway -(mqtt)-> server
On the server, we do authentication of the gateway but also the sensor sending the information. When an unauthenticated sensor sends a message through our gateway, the gateway gets disconnected from the broker as per the following documentation: http://docs.oasis-open.org/mqtt/mqtt/v3.1.1/os/mqtt-v3.1.1-os.html#_Toc39871804 . 

Now I've created some code to manually delete the last entry and this seems to work but when the service reconnects, it seems to publish all messages in the _out_messages queue while we've set the max_inflight_messages to 1. I've looked at the code and looks like there's no check for this (https://github.com/eclipse/paho.mqtt.python/blob/master/src/paho/mqtt/client.py#L3054). Shouldn't we check here if we're not publishing to many messages at once?

Thank you in advance!

Kind regards,
Liam

**Comment by MattBrittan** [comment]
Apologies for the huge delay in responding (we are working through old issues currently). 

Can you please confirm if this is still an issue for you with the current release? I would also appreciate it if you could update the question as the links are now outdated making the issue a little unclear. It would also be useful to see the code you created to "manually delete the last entry".

Note:; If we do not hear from you in a month we will assume this is no longer an issue (not ideal but the only option with issues as old as this).
