### ISSUE TITLE
loop_start() isssue

### ISSUE THREAD

**Issue by rmkdn** [eclipse/paho.mqtt.python#494]
I used loop_start() in my flask application with paho-mqtt protocol.  And the data is getting stored twice in the sqlite database. How to overcome this issue?
Can anyone help me resolving it?

**Comment by ralight** [comment]
You'll have to provide more details, like an example working program that demonstrates what you are seeing.

**Comment by ralight** [comment]
I'm going to close this, if it's still an issue please reopen and add more details.
