### ISSUE TITLE
PUBLISH is not sent to python subscriber after server SIGHUP.

### ISSUE THREAD

**Issue by jshep321** [eclipse/paho.mqtt.python#495]
I am running both bash (mosquitto_sub) and python subscribers.  Every morning when the cron.daily runs, the server mosquitto.log shows this:
_Wed Jun  3 06:25:02 2020: Error in poll: Interrupted system call.
Wed Jun  3 06:25:02 2020: Reloading config.
Wed Jun  3 06:25:02 2020: Client mqttpi_monitor disconnected.
Wed Jun  3 06:25:03 2020: New connection from 10.0.0.101 on port 8883.
Wed Jun  3 06:25:04 2020: New client connected from 10.0.0.101 as mqttpi_monitor (c1, k60).
Wed Jun  3 06:25:04 2020: Sending CONNACK to mqttpi_monitor (0, 0)_

However after the above occurs and any client publishes a message (on a topic that is subscribed to by my python subscriber), the server never sends the PUBLISH to that sub.  Works fine on the mosquitto_sub client.

I've tried both loop_forever and loop_start/stop in a while loop, as below.  Same result.

#forever loop:
    client.subscribe(topic+topic2)
    client.loop_forever()
#OR

#infinite loop:
client.subscribe(topic+topic2)
while (1):
    client.loop_start() 
    time.sleep(4) 
    client.loop_stop() 
`
Is this error due to my loop misconfiguration or a server bug?

**Comment by jshep321** [comment]
Also FYI.  On the client side I can see the "correct" log entries from my callbacks:
_2020-06-03 06:25:02,876 INFO     client disconnected OK
2020-06-03 06:25:04,035 INFO     client connected OK_

**Comment by ralight** [comment]
The broker shouldn't be kicking out your client on a HUP (what version of mosquitto are you using - this isn't something I've been able to reproduce)

However, your client should be able to handle reconnecting. What your code does it subscribe on the first connection only. Try putting your subscribe in the on_connect callback.

```
import paho.mqtt.client as mqtt

def on_connect(mqttc, obj, flags, rc):
    mqttc.subscribe("topic")

client = mqtt.Client()
client.on_connect = on_connect
client.connect("localhost", 1883, 60)
client.loop_forever()
```

**Comment by jshep321** [comment]
Ok, I'll try that thanks!  I'm using 1.4.10 on raspbian (stretch).
