### ISSUE TITLE
Websocket support for paho python

### ISSUE THREAD

**Issue by jpwsutton** [eclipse/paho.mqtt.python#5]
migrated from Bugzilla [#482282](https://bugs.eclipse.org/bugs/show_bug.cgi?id=482282)
status UNCONFIRMED severity *normal* in component *MQTT-Python* for *1.2*
Reported in version *1.1* on platform *All*
Assigned to: Roger Light

Original attachment names and IDs:
- _[paho_python_websocket_support.diff](https://bugs.eclipse.org/bugs//attachment.cgi?id=257966)_ (ID 257966)

On 2015-11-16 08:02:45 -0500, Milan Toth wrote:

> Created attachment 257966
> weboscket support git patch
> 
> Websocket support patch for paho python

**Comment by ralight** [comment]
Fixed in 1.2.
