### ISSUE TITLE
Is there any Mechanism to store messages in file system even if the client lose the connection?

### ISSUE THREAD

**Issue by malepurakesh** [eclipse/paho.mqtt.python#502]
hi, 
 I want to store the sensor data if the client connection lost. And even if the client lose the connection, it should keep on store the sensor data in the file system. And after re-establishing the connection. Client should publish the stored data to cloud. So, I had tried with client persistence. 
 I have used MQTTCLIENT_PERSISTENCE_DEFAULT, according to my understanding if I use this attribute, the inflight message will store in the file system(if connection lost). 
How can I store the messages in file system, even after client connection lose? Is there any mechanism to automatic publishing of stored messages from file system?
Thanks

**Comment by ralight** [comment]
I think you should be reporting this on the C client issue tracker: https://github.com/eclipse/paho.mqtt.c/issues
