### ISSUE TITLE
Remote procedure call/request-response messaging pattern

### ISSUE THREAD

**Issue by fkromer** [eclipse/paho.mqtt.python#508]
There is an [extension for MQTTnet](https://www.nuget.org/packages/MQTTnet.Extensions.Rpc/) to add support for [request-response style communication](https://en.wikipedia.org/wiki/Request%E2%80%93response) via MQTT. [Here](https://github.com/chkr1011/MQTTnet/wiki/Client#rpc-calls) is explained how it works. [MQTTnet](https://github.com/chkr1011/MQTTnet) is the probably most used .NET library for MQTT based communication out there. Are you guys interested in adding something like this to the Python Paho client and potentially other clients as well?

**Comment by briggySmalls** [comment]
I'd be really interested in this MQTTv5 feature.

The documentation for this library states that it supports v5, and this isn't mentioned in the [known limitations](https://pypi.org/project/paho-mqtt/#known-limitations).

**Comment by briggySmalls** [comment]
A bit more digging reveals that this does indeed seem to be implemented. There is a [unit test](https://github.com/eclipse/paho.mqtt.python/blob/28f669160d213cfdb30c8f62982b8a5443950eeb/tests/test_mqttv5.py#L926) demonstrating it

**Comment by ralight** [comment]
@briggySmalls You can do this already (as you've spotted), see https://github.com/eclipse/paho.mqtt.python/blob/master/examples/client_rpc_math.py and https://github.com/eclipse/paho.mqtt.python/blob/master/examples/server_rpc_math.py as examples. I image the point of what is done in MQTTnet is to wrap it up to make it easier.

**Comment by fkromer** [comment]
@ralight Great. I've just looked at the docs and did not browse the examples. Sorry for the spam.
