### ISSUE TITLE
Callbacks do not work properly (for example, on_connect)

### ISSUE THREAD

**Issue by mrdc** [eclipse/paho.mqtt.python#514]
Hello,

I'm experiencing some weird bugs with callbacks: sometimes they work, sometimes they don't.
For example, `on_connect` works in one script, then I copy paste it to another one and no result code is shown `on_connect`:

```python

import paho.mqtt.client as mqtt

def on_connect(client, userdata, flags, rc):
    print("Connected! Result code: " + str(rc))
    client.subscribe("$SYS/#")

client = mqtt.Client("client")
client.on_connect = on_connect
client.username_pw_set(username="admin", password="admin")
client.connect("192.168.1.35", 1883)
```

The same code shows me the connection result code in another script...

paho-mqtt 1.5.0
Python 3.8.5 
Win 10 x64, 1909
Atom 1.51 x64 with script 3.26.0 (to run Python code)

**Comment by ralight** [comment]
You need to use `loop_start()` or `loop_forever()` to process the network loop.

**Comment by mrdc** [comment]
> 
> 
> You need to use `loop_start()` or `loop_forever()` to process the network loop.

Isn't it more logical when `on_connect callback` is called each time we connect to a MQTT broker? In this case we always have the result code to check if connection is established.

**Comment by ralight** [comment]
The `on_connect` callback will only be called once network data has been processed. For that to happen, one of `loop_start()` or `loop_forever()` needs to be called. If you have other things to do in your main program like reading data from a sensor then using `loop_start()` lets you do that because it starts a separate thread in the background. If you only need to respond to incoming messages, e.g. subscribe to topics and print the messages, then `loop_forever()` will process the network traffic for you without a separate thread, and because it doesn't exit until you disconnect, it means you don't need some other way of stopping your program from quitting.

```python
import paho.mqtt.client as mqtt

def on_connect(client, userdata, flags, rc):
    print("Connected! Result code: " + str(rc))
    client.subscribe("$SYS/#")

client = mqtt.Client("client")
client.on_connect = on_connect
client.username_pw_set(username="admin", password="admin")
client.loop_start()
client.connect("192.168.1.35", 1883)

while True:
    data = read_sensor()
    client.publish("topic", data)
```

```python
import paho.mqtt.client as mqtt

def on_message(client, userdata, msg):
    print(msg.topic)

def on_connect(client, userdata, flags, rc):
    print("Connected! Result code: " + str(rc))
    client.subscribe("$SYS/#")

client = mqtt.Client("client")
client.on_connect = on_connect
client.on_message = on_message
client.username_pw_set(username="admin", password="admin")
client.connect("192.168.1.35", 1883)
client.loop_forever()
```

**Comment by mrdc** [comment]
Thanks it's clear. And when we have a regular script, for example, to publish some data not in loop - just once, how can we catch on_connect result code?

**Comment by ralight** [comment]
Something like one these should do the job. Note I've used qos=1 in the second example because `on_publish` will be called as soon as the data has left the client with qos=0, which could be before we've received the CONNACK.

```python
import paho.mqtt.client as mqtt

connack_rc = -1

def on_connect(mqttc, obj, flags, rc):
    global connack_rc
    connack_rc = rc
    mqttc.publish("topic", "1")

def on_publish(mqttc, obj, mid):
    mqttc.disconnect()

mqttc = mqtt.Client()
mqttc.on_connect = on_connect
mqttc.on_publish = on_publish
mqttc.connect("test.mosquitto.org", 1883, 60)
mqttc.loop_forever()
print("CONNACK reason code: %d" % (connack_rc))
```

```python
import paho.mqtt.client as mqtt
import time

connack_rc = -1

def on_connect(mqttc, obj, flags, rc):
    global connack_rc
    connack_rc = rc
    
def on_publish(mqttc, obj, mid):
    mqttc.disconnect()

mqttc = mqtt.Client()
mqttc.on_connect = on_connect
mqttc.on_publish = on_publish
mqttc.connect("test.mosquitto.org", 1883, 60)
mqttc.publish("topic", "1", qos=1)
mqttc.loop_start()
while connack_rc == -1:
    time.sleep(0.5)
print("CONNACK reason code: %d" % (connack_rc))
```

You could use `obj` to get your data to the on_connect

**Comment by mrdc** [comment]
Thank you! Now it's clear that I have to always use` loop_start` or` loop_forever` for `on_connect` callback to work properly.

**Comment by mrdc** [comment]
One more weird issue with callbacks.
The same code as above but with `on_message` callback :

```python
import paho.mqtt.client as mqtt

def on_connect(client, userdata, flags, rc):
    print("Connected! Result code: " + str(rc))
    client.subscribe("my_topic")

def on_message(client, userdata, message):
    print(datetime.datetime.now())
    print("Message received!")

client = mqtt.Client("client")
client.on_connect = on_connect
client.username_pw_set(username="admin", password="admin")
client.connect("192.168.1.35", 1883)

client.loop_forever()
```

Yes, I've not included `import datetime`, but Python is not complaining that `datetime ` is missing and ` print("Message received!")` is not executed. Is it somehow related to paho mqtt? Because normally it always causes an exception:

```python
# import datetime

def print_date_time():
    print(datetime.datetime.now())

print_date_time()
```

If I move `print(datetime.datetime.now())` outside `on_message ` function, Python complains as it should.
