### ISSUE TITLE
Release 1.5.1 on PyPi not in sync with github

### ISSUE THREAD

**Issue by emontnemery** [eclipse/paho.mqtt.python#516]
The latest Paho MQTT release on PyPi is 1.5.1, but github source is still marked as 1.5.0.dev0.

Based on comparing the PyPi package, the updated code string is the only code change, there are also some minor documentation changes.

Would it be possible to sync up the changes on PyPi with github? Would a PR doing that be accepted?

**Comment by ralight** [comment]
Thanks for the note, I did push the changes, but only to my other local copy, ahem... It is now updated with the commit and tag.
