### ISSUE TITLE
socks has no attribute HTTP, SOCKS4, SOCKS5 in check

### ISSUE THREAD

**Issue by kattstof** [eclipse/paho.mqtt.python#517]
not sure if its an issue with socks or not, as the Docs show that you're using it right, but i would continue getting no attribute for http, socks4 etc until i changed this line:

def check(t, a):
            return (socks is not None and
                    t in set([socks.HTTP, socks.SOCKS4, socks.SOCKS5]) and a)

to this:

def check(t, a):
            return (socks is not None)

**Comment by MattBrittan** [comment]
Please share your code so we can see how you are setting the proxy.

Closing due to age/inactivity/need for info.
