### ISSUE TITLE
on_publish called before on_connect

### ISSUE THREAD

**Issue by tompropst** [eclipse/paho.mqtt.python#521]
I am trying to detect when a connection fails by checking the `CONNACK` in the `on_connect` callback. In the case of a failure, I'm calling `disconnect` in the `on_connect` callback to break the network loop. In order to also break the network loop when a connection is successful (e.g. in a case where I just want to publish and exit), I also call `disconnect` in the `on_publish` callback.

When the connection fails (specifically, connection refused due to authentication failure), the `on_publish` callback executes first and I am unable to catch the connection failure so all indications are that everything worked.

```python
import logging
import paho.mqtt.client as mqtt

logger = logging.getLogger(__name__)

def on_connect(client, userdata, flags, rc):
    logger.info("Connection result: " + mqtt.connack_string(rc))
    if rc != mqtt.CONNACK_ACCEPTED:
        client.disconnect()

def on_disconnect(client, userdata, rc):
    logger.info("Disconnecting")

def on_publish(client, userdata, mid):
    logger.info("Published message: " + str(mid))
    client.disconnect()

mqtt_client = mqtt.Client()
mqtt_client.enable_logger(logger)
mqtt_client.on_connect = on_connect
mqtt_client.on_disconnect = on_disconnect
mqtt_client.on_publish = on_publish
mqtt_client.connect("some.broker.url", 1883)
mqtt_client.publish("mytopic", "hello")
mqtt_client.loop_forever()
```

As mentioned in issue #374, `on_publish` happens as soon as the packets are sent which here, appears to happen before the `CONNACK` is received. The lack of reliable connection status and error notification seems to be a common problem. A few options would be very helpful.

1. Allow connection attempts to cease on some errors like a connection refusal or authentication error. These are not likely to change with repeated attempts.
2. Make `connect` truly synchronous instead of [calling `connect_async` in all cases](https://github.com/eclipse/paho.mqtt.python/blob/42f0b13001cb39aee97c2b60a3b4807314dfcb4d/src/paho/mqtt/client.py#L939).
3. Maintain a connection status property to make detecting and correcting connection issues more straightforward.
    - Another approach would be to add an `on_connection_error` callback.

If any of this is amenable to the maintainers, I'm happy to go through the Eclipse registration and submit pull requests.

**Comment by MattBrittan** [comment]
Closing this because #615 has now been accepted which, hopefully, clarifies things a bit.  If you feel more is needed then please feel free to reopen it.

The MQTT protocol allows messages to be sent prior to a CONNACK being received; we could prevent that from happening but it's something that some users might want to do...
