### ISSUE TITLE
paho-mqtt 1.5.1: have to add 200ms delay between MQTT subscriptions

### ISSUE THREAD

**Issue by by5599** [eclipse/paho.mqtt.python#522]
We used to use the version 1.5.0. Everything seems working fine.
Recently we started using the version 1.5.1. We noticed one issue: we have to add at least 200ms delay between MQTT subscriptions when our application service is restarted. Otherwise, we can't receive any MQTT messages.
We have a service written in Python. Upon the system start-up, the service is started. This service is managed by systemd. In the service, we have about 80 MQTT messages to subscribe. The service subscribes the MQTT message one by one. 
In the version of 1.5.0, the messages can be subscribed and the messages can be received once the service is started. There was no delay among subscriptions.  It also works when the service is restarted by suing the systemctl command.
In the version of 1.5.1, the messages can be subscribed and the messages can be received once the service is started. However, no message can be received when the service is restarted. We found a work-around, which is to add 200ms delay between subscriptions. By the way, we tried 100ms delay which didn't work. It seems it has to be 200ms at least. As there are 80 MQTT messages, there will be a roughly 16 seconds delay for subscription. The question is, why is that? What is the problem? Is there a work-around other than adding delay?

**Comment by ralight** [comment]
The only thing that I can see that might be related to this is regarding a fix of first connection/subsequent connection behaviour for MQTT v5 clients.

Do you have a small example which shows exactly what you are doing?

**Comment by by5599** [comment]
Thanks ralight for your reply.
Here is some code:
`

EVENT1 = "config/event1"
EVENT2 = "config/event2"

def subscribeMqttMessages(mqttMgr):
    messageDict = {
        EVENT1: {
            'fct': event1Update(),
            'schema': schema["event1"]},
        EVENT2: {
            'fct': event2Update()
            'schema': schema["event2"]},
        ...
    }

    for event, handler in messageDict.items():
        mqttMgr.MqttSubscribe(event, handler['fct'], handler['schema'])
        # Have to delay 200ms since paho-mqtt v1.5.1
        time.sleep(0.2) 
`

**Comment by ralight** [comment]
Thank you, but I'm afraid that doesn't help much because I can't see any Paho code there.

This is my simple example of connecting and subscribing. It works just fine on the first connection and on subsequent connections. I realise that it is likely a lot different to what you have, but getting an idea of what Paho functions you are using is key to understanding the problem. If you can distill your code down to the essence of what it is doing we should be able to figure out the problem.

[sub.py](https://github.com/eclipse/paho.mqtt.python/files/5418969/sub.txt)

**Comment by by5599** [comment]
Thanks ralight.
We have a wrapper for the paho. Please see attached file.
[client.py.txt](https://github.com/eclipse/paho.mqtt.python/files/5419057/client.py.txt)

**Comment by by5599** [comment]
Here is a testing script and the systemd service file.

[mqtt_test.py.txt](https://github.com/eclipse/paho.mqtt.python/files/5699255/mqtt_test.py.txt)
[mqtt_test.service.txt](https://github.com/eclipse/paho.mqtt.python/files/5699256/mqtt_test.service.txt)

Here is how to test it:
- Rename the file to be mqtt_test.py and mqtt_test.service

**Comment by ralight** [comment]
I haven't been able to get your code to do what you describe. I can see all of the subscriptions are successfully created on the broker, but there isn't any code for publishing so I don't get the "Received:" messages. If I add in some publishing myself, I can see that works as well.

So I've not been able to get it to reproduce. If you can still help please let me know.

**Comment by MattBrittan** [comment]
I'm going to close this as we could not duplicate the problem and the issue has been inactive for a couple of years. If you are still able to reproduce this please feel free to reopen the issue (but it's likely that we will need further assistance - broker logs might be helpful too).
