### ISSUE TITLE
Publish on_disconnect is not working

### ISSUE THREAD

**Issue by mrdc** [eclipse/paho.mqtt.python#524]
Hello,

I'm experiencing an issue when publishing in `on_disconnect callback`: publish is executed after disconnect, so no data is actually published. Is it correct behavior?

```python
def on_disconnect(client, obj, rc):
    client.publish("Some_Topic", "Data", 1, True)

client.on_disconnect = on_disconnect

client.disconnect()
```

**In logs:**
```
Sending DISCONNECT
Sending PUBLISH (d0, q1, r1, m12), 'b'Some_Topic....'', ... (12 bytes)
```

**Comment by kpfleming** [comment]
If the client is disconnected, it can't publish messages.

**Comment by mrdc** [comment]
So, the only way to send something on disconnect is to use LWT? In this case LWT is static - we can't send something useful on disconnect event.

**Comment by kpfleming** [comment]
Yes. You are literally disconnected from the MQTT broker, it's impossible to send a message.

**Comment by mrdc** [comment]
Thanks, it's clear.

**Comment by garzj** [comment]
common layer 8 problem
