### ISSUE TITLE
client.publish() does not work in the on_message() callback

### ISSUE THREAD

**Issue by smilife-chocolat** [eclipse/paho.mqtt.python#527]
### Context

Hello everyone,

I develop a program that wait for a specific couple(topic, message), when the message is received, doing things then publish a result.

For that:

1. I initialize a client like:
```Python
def init_client(role, host, port, keepalive) -> mqtt.Client:
[...]
client = mqtt.Client(
    client_id='awesome_name',
        clean_session=True,
        userdata=None,
        protocol=mqtt.MQTTv311,
        transport="tcp"
)
[...]
```
2. I plugged callbacks (`on_connect`, `on_message`, `on_publish`, `on_log`...) on it.

3. I connect the client using `client.connect(host=host, port=port, keepalive=keepalive)`.

4. I run the client with a simple loop:
```Python
while True:
    client.loop()
```

### issue

Now, if I tried this:

```Python
def on_message(client, userdata, message) -> None:
    """The callback for when a message is received on subscribed topics"""
    logger.debug(f"Received {message.topic}, {str(message.qos)}, {str(message.payload.decode('utf-8'))}")
    pub_info = client.publish(topic='MYTOPIC', payload='mymessage', qos=0, retain=False)
    pub_info.wait_for_publish()
    logger.info(f'Published={pub_info.is_published()}')
```

- The `wait_for_publish()` is stuck for ever. 
- If I try without `wait_for_publish()`, message is published but `is_published()` tell me `False`.

### Expected

I would like to have a single client for subscribe, triggering callback on received messages and publish but it seems to not working.

### Workaround

I already go a workaround. I instantiate a second client and add it to the main client attributs like:

```Python
client = init_client(role='subscriber', host=host, port=port, keepalive=keepalive)

client_pub = init_client(role='publisher', host=host, port=port, keepalive=keepalive)

client.publisher = client_pub  # homemade attribut

while True:
    client.loop()
```

With this, I use `client.publisher.publish()` and it works as expected. **BUT**, I'm not sure it's the best way to use the library. 

### Questions

Why I got this behavior ? Is the main client stuck in this `on_message()` callback ?

What is the best practice to do that ?

Thank you for answer me.

**Comment by smilife-chocolat** [comment]
It seems to be a nice answer : https://stackoverflow.com/a/36964192

**Comment by sgbaird** [comment]
@smilife-chocolat still the way to go? Wondering if this is applicable to umqtt and other mqtt frameworks in general.

**Comment by thompcd** [comment]
@sgbaird This is still the way to handle this scenario. In any callback that can block your main thread, you want to have extremely light callbacks with minimal or no chance of failure inside of those callbacks. So yes, this will apply to other MQTT frameworks and even other languages as it is a general programming paradigm. 

If you need to perform work signaled by a callback, create a queue and push your action into a queue and let a separate, non-blocking thread service that queue. If you are in a single-threaded environment, you must intentionally dedicate time inside of your main loop to processing the queue periodically.
