### ISSUE TITLE
on_connect() different behaviour from version 1.5.0 to 1.5.1

### ISSUE THREAD

**Issue by CLDiego** [eclipse/paho.mqtt.python#528]
Hi,

I recently upgraded from version 1.5.0 to 1.5.1 and it introduced a bug on my code. 

My code for the callback was:

```
def on_connect(self, client, obj, flags, rc):

        if rc == 0:
            print(f'{rc} - {client.client_id} CONNECTED')
            client._mqtt_connected = True
            print(f'STATUS: {client.connack_string(rc)}')

        else:
            print('CONNECTION FAILED')
```

Now I get an error that client_id is not an attribute of the object client:
-  I changed that line to `client._client_id ` and it works

But then I received the error that `connack_string` is not an attribute.  I'm assuming that in the new version the client object paho is passing is different.

Was the change in behaviour of the on_connect callback intended?

**Comment by ralight** [comment]
`connack_string()` has never been an attribute of a paho mqtt client instance. It is a function that is contained in the `paho.mqtt.client` module. What changed in 1.5.1 is that exceptions are no longer suppressed by default in callbacks. This means that it has exposed a bug in your code. Change to `paho.mqtt.client.connack_string(rc)`, and you will be up and running again.

**Comment by CLDiego** [comment]
Thanks for the quick reply @ralight ! It was really helpful to get more clarity on this.
