### ISSUE TITLE
Callbacks definition and inheritance

### ISSUE THREAD

**Issue by AlexisBRENON** [eclipse/paho.mqtt.python#53]
Hi guys,

I'm using the Python implementation of MQTT through the paho-mqtt package. The documentation says that you can inherit from the Client class to create your own MQTT_client. Nevertheless, inheriting from the client doesn't allow you to define some on_* functions directly in the class because they are overridden by the __init__ call of the base class...

So, there is any particular reason the define Client.on_* to None in the __init__ instead of using classical member functions like this :

```python
class Client(object):
    def __init__(self, ...):
        ...
        # Nothing about self.on_*

    def on_*(self, ...):
        pass
```

An implementation like this would not break the actual behavior (you can redefine the functions, using mqttc.on_connect = my_new_connect_function), and it would be easier to inherit, defining overriding on_* functions in the sub-class.

If this seems a good idea, I propose myself to do the patch.

Kind regards,
Alexis BRENON

**Comment by AlexisBRENON** [comment]
Roger Light answers:

> Hi Alexis,
> 
> That sounds like a good idea. I confess that inheritance isn't
> something I really use so it may have been possible in the past and
> I've broken it.
> 
> I'd be happy to accept a patch for this, please base it on the fixes
> branch, add an entry to the changelog and make sure you have signed
> the Eclipse CLA.
> 
> Thanks,
> 
> Roger

**Comment by AlexisBRENON** [comment]
Jason Swails answers:

> Hi,
> 
> To be fair, the current class structure doesn't prevent inheritance -- just like the base class, you need to explicitly attach any callbacks as an attribute to the class.  Anything that's not the on_<action> callback is implemented directly as a method attribute, and can be overridden just fine in a subclass.
> 
> But this is definitely a strange pattern in my experience with Python.  Most instance attributes are assigned when the class definition is defined and is an unbound instance attribute on the class (rather than something that is bound at instance initialization).  A more natural API (to me, of course!) would be to either leave the on_* callbacks not implemented and rely on subclassing to implement it -or- have a function where you can register the callbacks.  The former would be a substantial break in the API.  The latter could be implemented in a fully backwards-compatible way by making the on_<action> callbacks descriptors (via the @property decorator)... but that's really the same thing that we already have from a functional perspective... it would just allow overriding to work in subclasses.
> 
> If it is decided that the callback registry approach is the one most liked, it will *allow* subclasses to override that behavior, but in such cases I would consider that approach to be a bit of an anti-pattern (why would a subclass swap out a flexible register service with a hard-coded function?  It changes the whole interface of the object...).
> 
> As an aside, one of the reasons to avoid doing fancy stuff like that in the initializer in my experience is that I don't think it plays nicely with serialization -- you'll need to do a bit of work to get pickling/unpickling to work correctly for these types, I think.
> 
> All the best,
> Jason
> 
> Jason Swails
> Project Software Engineer
> Ext. 1680

**Comment by AlexisBRENON** [comment]
Hi @swails.

Of course, the current structure doesn't prevent inheritance. Nevertheless, I think that explicitly attach callbacks is not a very straightforward method. Moreover, this implies that your callbacks are not named on_{connect,message,...} in which case they will be overridden by the initialization of the Client class.

I agree with your first proposal, but to prevent API break, you can define on_* callbacks as just empty functions in the base Client() class, for example :

```
class Client:
    ...

    def on_connect(self, client, userdata, flag, rc):
            """Called when the broker responds to our connection request.
            This function may be overridden by sub-classes.
    
            client:     the client instance for this callback
            userdata:   the private user data as set in Client() or userdata_set()
            flags:      response flags sent by the broker
            rc:         the connection result
            """
            pass

    ...
```

The second proposal seems more complicated, and as I understand it you will have to do a lot of self.register_callback('calback_name', self.callback_name_function) in your subclass initialization.

I started to implement the first proposal. I will open an Issue and PR on Github to follow the discussion.

Kind regards,
Alexis

**Comment by ralight** [comment]
This is fixed in the develop branch.
