### ISSUE TITLE
Protocol error: client resends messages after timeout, violating mqtt specification

### ISSUE THREAD

**Issue by kleunen** [eclipse/paho.mqtt.python#532]
Please see following issue:
https://github.com/redboltz/mqtt_cpp/issues/758

The paho python client attempts to resend publish/pubrec/pubcomp after timeout:
https://github.com/eclipse/paho.mqtt.python/blob/8945ee86f42effb305b52963396c51cbfd62bb39/src/paho/mqtt/client.py#L2810-L2829

But this is not according to MQTT specification:
https://docs.oasis-open.org/mqtt/mqtt/v5.0/os/mqtt-v5.0-os.html#_Toc3901238

_When a Client reconnects with Clean Start set to 0 and a session is present, both the Client and Server MUST resend any unacknowledged PUBLISH packets (where QoS > 0) and PUBREL packets using their original Packet Identifiers. This is the only circumstance where a Client or Server is REQUIRED to resend messages. Clients and Servers MUST NOT resend messages at any other time [MQTT-4.4.0-1]._

**Comment by ralight** [comment]
Yes, agreed. To be honest I thought this was already removed in 1.5. I removed it in the 1.6.x branch a little while ago, so I'm going to close this. Thanks for the report!

**Comment by BertKleewein** [comment]
For what it's worth, the phrase "Clients and Servers MUST NOT resend messages at any other time [MQTT-4.4.0-1]." was added to the MQTT 5.0 spec. If you look at the 3.1.1 spec, this sentence is missing. I read this as a clarification of an existing requirement rather than a new requirement.
