### ISSUE TITLE
Import paho fail

### ISSUE THREAD

**Issue by Valtent** [eclipse/paho.mqtt.python#545]
I have an issue with the autostart from an ubuntu machine:
My python with the paho works perfectly when I start it manually but when I do the autostart with the following code
#! /bin/sh
sleep 10
python3 /home/ubuntu/haccp-MQTTPG-client.py
it does not work.
the error is the following
File "/home/ubuntu/haccp-MQTTPG-client.py", line 6, in <module>
Jan 02 13:19:00 ip-172-31-25-143 mqttpostgresql[1691]:     import paho.mqtt.client as mqtt
Jan 02 13:19:00 ip-172-31-25-143 mqttpostgresql[1691]: ModuleNotFoundError: No module named 'paho'

sorry, this is my first post, I checked the previous one but I did not find anything similar

**Comment by ochabloz** [comment]
when you start a program in "autostart" it is usually ran as root or other admin account. check that you installed paho-mqtt system wide, not for a single user.  p.ex: `sudo pip show paho-mqtt`

**Comment by ralight** [comment]
I think ochabloz is correct, so this isn't an issue with the library and am going to close this. If you still need help, please reopen and provide some more details.
