### ISSUE TITLE
publish() never completes if done straight after connect_async()

### ISSUE THREAD

**Issue by jps-aldridge** [eclipse/paho.mqtt.python#550]
Using paho-pqtt 1.5.1, when the example

    import time
    import paho.mqtt.client

    print(paho.mqtt.__version__)
    client = paho.mqtt.client.Client()

    client.connect_async('keylimepi.lan')
    client.loop_start()

    # time.sleep(0.1)

    mi = client.publish('test', 'testing')
    mi.wait_for_publish()

    client.disconnect()
    client.loop_stop()

is run, the message never reaches the broker and the call to wait_for_publish() hangs indefinitely.

If the time.sleep() line is uncommented, then the code publishes the message and terminates as expected.

[ I'm using connect_async(), rather than connect(), because I want the message to reach the broker eventually, even if it cannot be reached when the program is started. ]

**Comment by BertKleewein** [comment]
By default, the `publish` method specifies `qos=0` which translates to "no delivery guarantee".  I recommend passing `qos=1` to the publish call, which translates to "guaranteed to be delivered at least once."

You may also want to check the value of `mi.rc`.  It might indicate an error that you need to handle.

**Comment by jps-aldridge** [comment]
Fair enough: it would be nice if this behaviour was documented, though.

I'd assumed that wait_for_publish() would complete immediately if the library had decided to discard the the message without sending it.

**Comment by ralight** [comment]
Thanks for the report. `wait_for_publish()` now throws an exception if the preceding publish call produced an error. That would have allowed you to find the problem. If you think that's enough, please reopen and explain.

**Comment by photron** [comment]
@ralight Did you miss to include the actual change to `wait_for_publish()` in the commit? c339cea2652a957d47de68eafb2a76736c1514e6 only updated the changelog. Also, the change to `wait_for_publish()` should be applied to `is_published` too.

**Comment by ralight** [comment]
@photron It looks like it. I've added the code back in.

**Comment by photron** [comment]
@ralight Thank you. I think the same change should be applied to `is_published()` too. Because as it is now, the error behavior between `wait_for_publish()` and `is_published()` is different.
