### ISSUE TITLE
Connecting to TLS1.2 server fails (on Python 3.5)

### ISSUE THREAD

**Issue by wiebeytec** [eclipse/paho.mqtt.python#551]
I'm getting a TLSV1_ALERT_PROTOCOL_VERSION error on a Ubuntu 16.04 machine. Python 3.5, and openssl 1.0.2 all support TLS 1.2, but using PAHO to connect to a server that only supports TLS 1.2 or TLS 1.3 (Mosquitto on Ubuntu 20.04 for instance) fails.

I tried the newest Paho, 1.5.1. 

Trace, although this trace is 1.3, the error is the same:

```
File "/bla/paho/mqtt/client.py", line 760, in connect
    return self.reconnect()
  File "/bla/paho/mqtt/client.py", line 919, in reconnect
    sock.do_handshake()
  File "/usr/lib/python3.5/ssl.py", line 988, in do_handshake
    self._sslobj.do_handshake()
  File "/usr/lib/python3.5/ssl.py", line 633, in do_handshake
    self._sslobj.do_handshake()
ssl.SSLError: [SSL: TLSV1_ALERT_PROTOCOL_VERSION] tlsv1 alert protocol version (_ssl.c:645)
```

The problem is in finding the supported version. I hack-patched it for a project of ours:

```
         # Create SSLContext object
         if tls_version is None:
-            tls_version = ssl.PROTOCOL_TLSv1
+            tls_version = ssl.PROTOCOL_TLSv1_2
             # If the python version supports it, use highest TLS version automatically
             if hasattr(ssl, "PROTOCOL_TLS"):
                 tls_version = ssl.PROTOCOL_TLS
```

I know this is not a graceful patch, but FYI.

**Comment by BertKleewein** [comment]
Maybe I misread something, but this seems like it's working correctly.  `ssl.PROTOCOL_TLSv1` means "use TLS v1.0".  If you pass this, it should fail if the server only supports TLS v1.2+

**Comment by wiebeytec** [comment]
The point is that 'If the python version supports it, use highest TLS version automatically' fails, so that it defaults to TLS1 and gives an incorrect error about TLS1.2 not being supported, while it actually is.

**Comment by ralight** [comment]
We should be defaulting to TLS 1.2 now anyway, so this is a fair change, thank you.
