### ISSUE TITLE
Does changing the system datetime affect or stop Paho MQTT Client in asynchronous mode?

### ISSUE THREAD

**Issue by KennPunt** [eclipse/paho.mqtt.python#56]
I am using the Paho MQTT Client in asynchronous mode on a raspberry pi. The program sometimes stops sending MQTT messages and it happens not very often. When looking in the syslog I noticed that when this happens there is also a bug that the system datetime flashed back one day or a few minutes. Can this affect or stop Paho MQTT Client in asynchronous mode?

**Comment by ralight** [comment]
Yes this would affect client regardless of how it is operating.

Using time.monotonic() would solve the problem, but it is only available on Python 3.3 and up. The patch [time.txt](https://github.com/eclipse/paho.mqtt.python/files/259346/time.txt) attempts to handle that situation. I've only tested it briefly, if you could provide feedback it would be very helpful.

**Comment by ralight** [comment]
This should now be fixed.
