### ISSUE TITLE
Can someone post an example of an unsubscribe callback?  I can't find an example that seems to work?

### ISSUE THREAD

**Issue by dachshund-digital** [eclipse/paho.mqtt.python#561]
Can someone post an example of an unsubscribe callback?  I can't find an example that seems to work?  I have even written python code to test this, and it appears that either my code is wrong, or the broker I am using just simply does not return back a UNSUBACK.  So, I am hoping someone can provide an example they know works 100%, that I can try against the broker I have to help isolate the issue to either my code, or the broker dropping the ball so to speak.  I am using the mosquitto broker that is installed via Raspberry Pi OS (latest), mosquitto version 2.0.9.

Thanks.

**Comment by BertKleewein** [comment]
One way to debug this issue is to turn on Paho logging.  If your broker is sending UNSUBACK, you should see a `Received UNSUBACK` in your log.

To enable this, you need to:
1. `import logging` and `logging.getLogger("paho").setLevel(level=logging.DEBUG)`
2. call `enable_logger` on your Client object

**Comment by ralight** [comment]
Here you go:

```
import paho.mqtt.client as mqtt

def on_connect(mqttc, obj, flags, rc):
    print("Connected")
    mqttc.subscribe("unsub-callback-demo", 0)

def on_subscribe(mqttc, obj, mid, granted_qos):
    print("Subscribed")
    mqttc.unsubscribe("unsub-callback-demo")

def on_unsubscribe(mqttc, obj, mid):
    print("Unsubscribed")

def on_log(mqttc, obj, level, string):
    print(string)

mqttc = mqtt.Client()
mqttc.on_connect = on_connect
mqttc.on_subscribe = on_subscribe
mqttc.on_unsubscribe = on_unsubscribe
mqttc.on_log = on_log
mqttc.connect("test.mosquitto.org", 1883, 60)
mqttc.loop_forever()
```

**Comment by dachshund-digital** [comment]
Thanks!  Your example works, so good news is my broker is sending UNSUBACK.  But my callback is not firing.  So I have a bug or something else going on.

`[2021-06-15 15:16:31 GMT]  Test * 0.0.1 * 06/13/2021
[2021-06-15 15:16:31 GMT]  Test...
[2021-06-15 15:16:31 GMT]  Wait!
[2021-06-15 15:16:32 GMT]  Wait!
[2021-06-15 15:16:32 GMT]  Wait!
[2021-06-15 15:16:32 GMT]  Log! Client 0xb4ba6df0, Data None, Level 16, Message Sending CONNECT (u0, p0, wr0, wq0, wf0, c1, k60) client_id=b''
[2021-06-15 15:16:32 GMT]  Log! Client 0xb4ba6df0, Data None, Level 16, Message Received CONNACK (0, 0)
[2021-06-15 15:16:32 GMT]  Connect! Client 0xb4ba6df0, Data None, Flags {'session present': 0}, Result: 0
[2021-06-15 15:16:32 GMT]  Subscribe 'command/irrigation/test'
[2021-06-15 15:16:32 GMT]  Wait!
[2021-06-15 15:16:32 GMT]  Log! Client 0xb4ba6df0, Data None, Level 16, Message Sending SUBSCRIBE (d0, m1) [(b'command/irrigation/test', 2)]
[2021-06-15 15:16:32 GMT]  Log! Client 0xb4ba6df0, Data None, Level 16, Message Received SUBACK
[2021-06-15 15:16:32 GMT]  Subscribe! Client 0xb4ba6df0, Data None, Topic 'command/irrigation/test', Quality (2,)
[2021-06-15 15:16:32 GMT]  Idle! Client 0xb4ba6df0
[2021-06-15 15:16:33 GMT]  Idle! Client 0xb4ba6df0
[2021-06-15 15:16:34 GMT]  Idle! Client 0xb4ba6df0
[2021-06-15 15:16:35 GMT]  Idle! Client 0xb4ba6df0
[2021-06-15 15:16:35 GMT]  Control Break (Control-C Interrupt)? SIGINT
[2021-06-15 15:16:35 GMT]  Interrupt (SIGINT)...
[2021-06-15 15:16:35 GMT]  ...Interrupt (SIGINT).
[2021-06-15 15:16:36 GMT]  Log! Client 0xb4ba6df0, Data None, Level 16, Message Sending DISCONNECT
[2021-06-15 15:16:36 GMT]  Log! Client 0xb4ba6df0, Data None, Level 16, Message Sending UNSUBSCRIBE (d0, m2) [b'command/irrigation/test']
[2021-06-15 15:16:36 GMT]  Unsubscribe 'command/irrigation/test'
[2021-06-15 15:16:36 GMT]  Disconnect! Client 0xb4ba6df0, Data None, Result 0
`

My code never seems to see the UNSUBACK.  I am using loop_start() and loop_stop, as well as connect_async().  But I can't see that as an issue per se?  I am definitely trying to hook the message.

`                theClient = mqtt.Client()

                if theClient is None:

                        #

                        raise Exception('No Client?')

                #

                theClient.on_connect = OnConnect
                theClient.on_subscribe = OnSubscribe
                theClient.on_message = OnMessage
                theClient.on_log = OnLog
                theClient.on_publish = OnPublish
                theClient.on_unsubscribe = OnUnSubscribe
                theClient.on_disconnect = OnDisconnect

                #

                theClient.connect_async(BROKER, PORT, ALIVE)
                theClient.loop_start()
`

So, time to do some debugging.

**Comment by dachshund-digital** [comment]
This is a bit weird... I changed connect_async() to just connect, and called loop_forever(), this got a bit more detail.  But the message logged does not make much sense... my OnUnSubscribe() just has a print in it.

> [2021-06-15 15:32:57 GMT]  Log! Client 0xb4c80d70, Data None, Level 16, Message Sending SUBSCRIBE (d0, m2) [(b'command/irrigation/test', 2)]
[2021-06-15 15:32:57 GMT]  Log! Client 0xb4c80d70, Data None, Level 16, Message Received SUBACK
[2021-06-15 15:32:57 GMT]  Log! Client 0xb4c80d70, Data None, Level 8, Message Caught exception in on_subscribe: list index out of range

**Comment by dachshund-digital** [comment]
Ok there is some code that consistently shows that unsubscribe message is just not being seen after loop_forever or loop_start has control.

`#!/usr/bin/python3

import time
import paho.mqtt.client as mqtt

#

def on_connect(mqttc, obj, flags, rc):
    print("CONNECTED")

def on_subscribe(mqttc, obj, mid, granted_qos):
    print("SUBSCRIBED")

def on_unsubscribe(mqttc, obj, mid):
    print("UNSUBSCRIBED")

def on_log(mqttc, obj, level, string):
    print(string)

def on_disconnect(mqttc, object, rc):
        print('DISCONNECTED')
#

try:

        mqttc = mqtt.Client()
        mqttc.on_connect = on_connect
        mqttc.on_subscribe = on_subscribe
        mqttc.on_unsubscribe = on_unsubscribe
        mqttc.on_disconnect = on_disconnect
        mqttc.on_log = on_log

        #mqttc.connect_async("broker.dachshund-digital.org", 1883, 60)
        mqttc.connect("broker.dachshund-digital.org", 1883, 60)

        print('subscribe topic-1')
        mqttc.subscribe('topic-1')

        print('subscribe topic-2')
        mqttc.subscribe('topic-2')

        print('unsubscribe topic-1')
        mqttc.unsubscribe('topic-1')

        #
        mqttc.loop_forever()

        #

        while True:

                print('never here')

except KeyboardInterrupt as theException:

        print('')
        print('interrupt')

except Exception as theException:

        print('catch anything')

finally:

        print('attempt unsubscribe')
        mqttc.unsubscribe('topic-2')

        print('wait')
        time.sleep(15)

        print('attempt disconnect')
        mqttc.disconnect()

        print('done')
`

Run results....  The first unsubscribe gets the UNSUBACK as expected, but the second unsubscribe never gets an UNSUBACK.  I can't figure out why this happens, my code?  A bug?  The main thread is waiting as well, before calling disconnect, so what is the deal?

~# python3 Test.py
Sending CONNECT (u0, p0, wr0, wq0, wf0, c1, k60) client_id=b''
subscribe topic-1
Sending SUBSCRIBE (d0, m1) [(b'topic-1', 0)]
subscribe topic-2
Sending SUBSCRIBE (d0, m2) [(b'topic-2', 0)]
unsubscribe topic-1
Sending UNSUBSCRIBE (d0, m3) [b'topic-1']
Received CONNACK (0, 0)
CONNECTED
Received SUBACK
SUBSCRIBED
Received SUBACK
SUBSCRIBED
Received UNSUBACK (Mid: 3)
UNSUBSCRIBED
^C
interrupt
attempt unsubscribe
Sending UNSUBSCRIBE (d0, m4) [b'topic-2']
wait
attempt disconnect
Sending DISCONNECT
DISCONNECTED
done

**Comment by dachshund-digital** [comment]
Ok, posting this because it may help someone else, the bottom line is that I established a type of race condition.  The example code @ralight provided was a definite help, it confirmed that the the UNSUBACK was enabled for my given broker.  So the issue had to be in my code, somehow, somewhere.  What was happening was that the disconnect was faster than the unsubscribe UNSUBACK because I happen to be calling the explicit unsubcribe for each topic as the disconnect was in progress, this blinded my script from receiving/seeing the UNSUBACK response.  So the botton-line is, if you want to do explicit un-subbing and see the results via the unsub callback, do it before any disconnect message is generated to the broker!
