### ISSUE TITLE
connect() and connect_async() is not having a proper difference as mentioned in the docs.

### ISSUE THREAD

**Issue by anirbanroydas** [eclipse/paho.mqtt.python#57]
From the docs, there are 3 methods to connect:
 1.  connect()
 2.  connect_async()
 3.  connect_srv()

It says the 

> Identical to `connect()`, but non-blocking. The connection will not complete until one of the `loop*()` functions is called.

But actually, `connect()` calls `connect_async()` first and then calls `reconnect()`. Thus saying `connect()` and `connect_async` working differently is not that proper. Moreover, `connect()` being blocking and `connect_async()` being non-blocking is not correct as both of them end up doing the same thing (just that with `connect_async()`, few things have to be taken care of).

Its been referred already in #4

**Comment by ralight** [comment]
#4 is a completely different (and invalid) bug report.

The documentation in the code (which is always the best place to look) correctly say that you should only use this with `loop_start()`. The description in README.rst was incorrect, thanks for the report. That's now fixed although I referenced the wrong bug.
