### ISSUE TITLE
Unable to receive large payload messages with TLS (80MB+)

### ISSUE THREAD

**Issue by umorelli** [eclipse/paho.mqtt.python#571]
Hello,

While investigating possible DoS attacks in the context of MQTT, I noticed that the Paho client is unable to receive large payload messages if adopting TLS (1.2 or 1.3, with MQTT v.3.1.1 or v.5): it will use 100% of one CPU core and keeps reconnecting (and attempting the receiving of the message in loop in case of a persistent session).

Using a Raspberry PI 3 model B+, I can only receive a message of ~80MB (~450s to receive it) if the broker is Mosquitto; ~70MB in the case of VerneMQ (~350s to receive it). If not using TLS or using _mosquitto_sub_, the Raspberry can receive a 255MB message without issues in ~24s.
On a regular PC (Intel E3-1240 @3.40GHz), the same behaviour happens if the payload is >=100MB.

I am using paho-mqtt 1.5.1. To reproduce:

Create a large file and publish it (createFile.py uploaded [here](https://github.com/eclipse/paho.mqtt.python/files/6481190/createFile.txt)) with:
```
python3 createFile.py -s 100
mosquitto_pub -h <host> -q 1 -p 1883 -t messages -f 100MB_file
```
Example Paho receiver uploaded [here](https://github.com/eclipse/paho.mqtt.python/files/6481242/Tester_receiver.txt). It uses port 8002 for unilateral TLS, 8003 for mutual; expects ca.crt, client.crt and client.key in a relative `cert/` folder;  and runs with:
```
python3 Tester_receiver.py -p 8002 
python3 Tester_receiver.py -p 8002 -v 5
```
_mosquitto_sub_ can be run with  `mosquitto_sub -h <host> -p 8002 -q 1 --cafile certs/ca.crt --cert certs/client.crt --key certs/client.key -t messages -F %t`

**Comment by ralight** [comment]
Thanks for the report. There are a couple of things in play here. The big one is that Python has a non-optimal way of working with reading SSL sockets as summarised in this issue: https://bugs.python.org/issue37355 It looks like this will be fixed for Python 3.11 in October 2022. 

That's a long time to wait, so I've also added a change that means the slow SSL reads won't cause anything to time out in the rest of the client. It doesn't help the speed, that'll have to wait for the above fix.

**Comment by ralight** [comment]
Ok, scrap that I've found the real answer. The incoming data was inadvertently being appended to a bytes() object, which is immutable and hence slooow. Changing to a bytearray() and it's much much faster. I just received a 1000MB file in about 4 seconds, over loopback.

If you'd like to give it a try, please check out the `1.6.x` branch.

**Comment by ralight** [comment]
Closing because I believe this is fixed and I'm trying hard to get on top of the backlog. If you don't think it's closed, please feel free to reopen.
