### ISSUE TITLE
connect_async() doesn't work with all the loop*() functions as mentioned in docs, it can only work with some. For me it didn't work with any.

### ISSUE THREAD

**Issue by anirbanroydas** [eclipse/paho.mqtt.python#58]
As mentioned in the docs:

> Identical to `connect()`, but non-blocking. The connection will not complete until one of the ` loop*() ` functions is called.

But it cannot work with simple `loop()`, because, calling `connect_async()` doesn't actually create the connection, rather it just initiates some private variables.

Unlike `connect()`, which calls `connect_async()` to initialise those private variable followed by `reconnect()` which actually creates the socket connection, thus by simply calling `connect_async()` it doesn't create the connection since its not calling `reconnect()` directly in its method.

Moreover, if you are calling just `connect_async()`, you can only call some selected `loop*()` functions, specifically those which in return go ahead and calls `reconnect()`, hence, those are `loop_forever()`  and  `loop_start()`.

Also, given these conditions, I did try `connect_async()` with both `loop_forever()` and `loop_start()` but both seemed to got stuck and not reply with any messages (even after subscribing to $SYS/# topics).

**Comment by ralight** [comment]
This works for me. I've attached my working example.

[sub.txt](https://github.com/eclipse/paho.mqtt.python/files/278356/sub.txt)

**Comment by anirbanroydas** [comment]
Okay, so I did try a lot of variations. I am submitting the variations, please tell me what am I missing, some of them work, some don't, and for the ones which work, the responses are not universal.

Please check them and tell me the catch for each one of them.

**Note:** the variations are done on one of the codes from the examples, sub-multiple-callback.py

[variation_1.txt](https://github.com/eclipse/paho.mqtt.python/files/278519/variation_1.txt)
Calling `connect()` with `loop()` for **1 time**. Doesn't work. Even when loop has been given `timeout=10.0` seconds. Also, I have tried without setting `timeout` in `loop()` but still doesn't work(whose reason is still obvious).

[variation_2.txt](https://github.com/eclipse/paho.mqtt.python/files/278525/variation_2.txt)
Calling `connect()` with `loop()` for **10 times** in while construct. Seems to work.

[variation_3.txt](https://github.com/eclipse/paho.mqtt.python/files/278528/variation_3.txt)
Calling `connect()` with `loop()` infinitely in **while True construct**. Seems to work. ( More like calling loop_forever())

[variation_4.txt](https://github.com/eclipse/paho.mqtt.python/files/278529/variation_4.txt)
Calling `connect()` with `loop_forever().` Seems to work.

[variation_5.txt](https://github.com/eclipse/paho.mqtt.python/files/278533/variation_5.txt)
Calling `connect()` with `loop_start()`. Seems to work.

[variation_async_1.txt](https://github.com/eclipse/paho.mqtt.python/files/278538/variation_async_1.txt)
Calling **`connect_async()`** with `**loop_forever()**` (Since only loop_forever() and loop_start() seems eligible to be called, rest do not call `reconnect()`, so will not form an actual connection to broker). Doesn't work. Remains blocked and stuck and occasionally sends the ping requests to keep connection open.
Now, if the argument is I should be calling `loop_start()` and not `loop_forever()`, I have few things to say about this:
1. I have done a variation with **loop_start()**, added it as variation_async_2.txt, follow that for its status.
2. Now if the argument is to call loop_start() and not loop_forever(), please tell me why, because from what I see, loop_start() calls reconnect() (if connect_async() is used, and in this case its true), and then loop_forever(), all of that in a separate thread in daemon mode, and if suppose we call loop_forever directly instead, it calls reconnect first (if connect_async() is use, and in this case its true), and calls loop infinitely. The only difference between calling loop_forever() and loop_start() in case of connect_async() is that one is using a separate thread, the other doesn't. So what's the catch in here?

Now lets see the last variation with loop_start()

[variation_async_2.txt](https://github.com/eclipse/paho.mqtt.python/files/278551/variation_async_2.txt)
Calling `connect_async()` using `loop_start()` with `while True loop` calling `time.sleep(1)` in the main thread so that it doesn't end the program which ends the connection and no work can be done by the extra thread. Doesn't work.


Also, please tell me cases when I would be be using `connect_async` over `connect` since both of then end up calling the same functions, with the former having less number of options as far as `loop*()` functions are concerned.

**Comment by anirbanroydas** [comment]
@ralight  Also Note that I have tried it both with `localhost` and `iot.eclipse.org`, also, its when I am saying it doesn't work for some of the variations, what I mean is sometimes even if the connection is created successfully but there is not messages being produced even after subscriptions, whereas for others which seem to work, I can see the message outputs from the subscribed topics.

**Comment by ralight** [comment]
Thanks for those, I'll take a look at them when I get chance.

**Comment by anirbanroydas** [comment]
Thanks. Please have a look at them and revert with your take on those as soon as possible. :)

**Comment by ralight** [comment]
Right, so variations 1-5 are working as expected.

The problem with the others is that you aren't checking the return code of `subscribe()` for failure.

The rules for when to use `loop_start()`, `loop_forever()` or `loop()` are:

* Use `loop_forever()` if your code only does things in callbacks and is best suited to a blocking call.
* Use `loop_start()` if your code does other things as part of its processing, e.g. dealing with a gui, reading data from a sensor and it shouldn't block on the client library code.
* Never use `loop()` unless you want to handle reconnecting and error handling yourself and you have an especially good reason for not using one of the previous options. Then make sure you are *really* sure.

**Comment by ralight** [comment]
It's generally a more robust method to call `subscribe()` from the `on_connect()` callback anyway, otherwise you lose subscriptions on a reconnection.

**Comment by anirbanroydas** [comment]
Thanks @ralight for looking at them. Yes, calling `subscribe()` from `on_connect()` is surely the better way to do things as we get the confirmation of the connection.

Also, few things that can be added to the docs to make it clearer to users without having doing a lot of research. Like the `on_connect()` method is not triggered if you just call `connect()`, it will be triggered if you run one of the `loop*()` functions and not otherwise, I think. **Please shed a light on this too.**

Also, what about if I want to user some other **`ioloop`**, like if I want to use **Tornado's ioloop**, which does all the work for me, what I am doing is adding a handler for the **mqtt client socket**, which I am accessing via `socket()` method, and in case of **Read** event, I am calling `loop_read()` and in case of **Write** event, I am calling `loop_write()`. Please tell me, whether this will suffice or do I have to take care of any edge cases, or any other special case?

**Comment by anirbanroydas** [comment]
**UPDATE:** 

Along with `loop_read()` and `loop_write()`, `loop_misc()` is to be called regularly, may be once every **10** seconds or more or less but less than `keepalive` value.

Can be done using **tornado's** `ioloop.IOLoop.PeriodicCallback`. 

Successful but not a very convenient flow.
