### ISSUE TITLE
Is there a way for the publish, subscribe or unsubscribe callbacks to know 'which' instance they are?

### ISSUE THREAD

**Issue by dachshund-digital** [eclipse/paho.mqtt.python#580]
Is there a way for the publish, subscribe or unsubscribe callbacks to know 'which' instance they are?

If I subscribe topic "1", can on_subscribe callback know they are processing "1" topic?
If I unsubscribe topic "1", can on_unsubscribe callback know they are processing "1" topic?
If I publish topic "1", can on_publish callback know they are processing "1" topic?

The given topic does not seem to be visible to the callbacks?  Can this be added?

**Comment by ralight** [comment]
They will be processed in exactly the order in which they are sent out, so if you need to know this you can keep track yourself. MQTT doesn't tell you what the subscription was when it acknowledges the subscription request.

**Comment by dachshund-digital** [comment]
So no 'native way' but if it is FIFO (First In, First Out) I can use a queue or array to track which is which via assignment of index on order received.
