### ISSUE TITLE
Subscription packet never acknowledged by broker if properties.SubscriptionIdentifier==[0]

### ISSUE THREAD

**Issue by sammck** [eclipse/paho.mqtt.python#586]
I'm using the 1.6.x branch, which fixes another data corruption bug in PUBLISH when total property length > 128 bytes. I have not verified that this problem is also present in 1.5 release.

I've noticed that if I attach a SubscriptionIdentifier property to my subscribe request, everything works fine unless the value of the identifier is 0. If it is zero, the client claims to have sent the subscribe request. The MQTT broker (mosquitto) logs that it received a SUBSCRIBE but seems to indicate there are no requested topics), and never sends any SUBACK.  The client never receives SUBACK, on_subscribe is never called, and messages in the topic are not received. The client then immediately (before subscribe timeout) claims to have received DISCONNECT, and ends the connection.

My suspicion is that the SUBSCRIBE packet is corrupted at the sending side. I wonder if it might be related to the fact that SubscriptionIdentifier is encoded with "Variable Byte Integer" scheme, in which one might expect the value 0 to be a special edge case?

The following will demonstrate the problem:

```#!/usr/bin/env python3

import logging

from typing import List

logging.basicConfig(level=logging.DEBUG)
logger = logging.getLogger(__name__)

import paho.mqtt.client as mqtt
from paho.mqtt.packettypes import PacketTypes
from paho.mqtt.properties import Properties

port = 1883

host = 'mqtt.eclipse.org'
username = None
password = None

def on_connect(client: mqtt.Client, userdata, flags, rc: mqtt.ReasonCodes, properties: mqtt.Properties):
    logger.debug("on_connect: Connected with result code %s" % rc.getName())
    props = Properties(PacketTypes.SUBSCRIBE)
    props.SubscriptionIdentifier=0
    # opts = SubscribeOptions(qos=2)
    client.subscribe("paho-mqtt-bad-subscription-test/topic", properties=props)

def on_subscribe(client: mqtt.Client, userdata, mid, rc: List[mqtt.ReasonCodes], properties: mqtt.Properties):
    logger.debug("on_subscribe: subcription acked with mid=%s, rc=%s, properties=%s" % (mid, [x.getName() for x in rc], str(properties)))
    client.disconnect()

client = mqtt.Client(protocol=mqtt.MQTTv5, client_id='paho-mqtt-bad-subscription-test')
client.on_connect = on_connect
client.on_subscribe = on_subscribe
client.enable_logger()
if not username is None:
  client.username_pw_set(username, password=password)

logger.info('Connecting to MQTT broker at %s:%d' % (host, port))

client.connect(host, port=port)

client.loop_forever()
```

**Comment by ralight** [comment]
Your suspicion is correct - it's a problem at the sending side. If you look at the disconnect packet coming back when running your example you should see that it has the reason code "malformed packet". A subscription identifier of 0 is forbidden.

I've pushed a change which raises an exception if you try to set a forbidden value for properties. Thanks for the report!

**Comment by ralight** [comment]
This will be part of 1.6.0, I'm closing now to help tidy up the issue list.
