### ISSUE TITLE
CA authentication

### ISSUE THREAD

**Issue by HDenied** [eclipse/paho.mqtt.python#588]
I am not sure if I understood this well,  when I read the docimentation related to "tls_set", for basic ca authentication it says:

"By default, on Python 2.7.9+ or 3.4+, the default certification authority of the system is used"

Does this mean that the client is picking up the certificates from the host machine communicating with the broker? I am asking this because I am running some tests with mosquitto running in a local docker container. The library doesn't seem to use the ca.crt file at all to verify the broker identity, I can just omit it and the client will be able to connect. Is this expected?

Thanks!

**Comment by ralight** [comment]
It doesn't sound expected .Could you please provide some example code that demonstrates what you are seeing?

**Comment by HDenied** [comment]
After further investigation I realised the certificate were generated without hostname, therefore the authentication needs to be insecure. I also tried to make broker authenitcation mandatory and use a wrong certificate and in that case it fails, when it is not mandatory even with the wrong certificate it works, which I guess is the correct behaviour. Sorry, false alarm, I apologise.

**Comment by ralight** [comment]
Ok! I'm glad you got it sorted.
