### ISSUE TITLE
Maybe feature request?  Implement __version__() method for Paho MQTT Python Client?

### ISSUE THREAD

**Issue by dachshund-digital** [eclipse/paho.mqtt.python#596]
Would be nice if client could be queried for version?  Or does such exist already?

I tried...

paho.mqtt.client.__version__, paho.mqtt.client.__version__()

And...
importlib.metadata import version
pkg_resources

Even pip show paho.mqtt.client did not show a version?  I did I miss something?

**Comment by ralight** [comment]
The versioning is done at the package level rather than the individual module level, so try

```
from paho.mqtt import __version__
```

**Comment by dachshund-digital** [comment]
Cool... that gets a version... but not the version I was expecting.  I pulled the 1.6x branch, ran the install script...

Installed /usr/local/lib/python3.7/dist-packages/paho_mqtt-1.6.0-py3.7.egg
Processing dependencies for paho-mqtt==1.6.0
Finished processing dependencies for paho-mqtt==1.6.0

That appears right to me.  However when I query the version... my script reports...

# python3 __Test.py
Version 1.5.0

So, I have something wrong somewhere?

**Comment by ralight** [comment]
Have you got 1.5.0 installed somewhere else?

**Comment by dachshund-digital** [comment]
I should not, I don't do any customization of the prefix or paths...  I just checked the default path list and 1.6 is there...

# python3
Python 3.7.3 (default, Jan 22 2021, 20:04:44)
[GCC 8.3.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import sys
>>> sys.prefix
'/usr'
>>> sys.path
['', '/usr/lib/python37.zip', '/usr/lib/python3.7', '/usr/lib/python3.7/lib-dynload', '/usr/local/lib/python3.7/dist-packages', '/usr/local/lib/python3.7/dist-packages/luma.led_matrix-1.5.0-py3.7.egg', '/usr/local/lib/python3.7/dist-packages/luma.core-2.3.1-py3.7.egg', '/usr/local/lib/python3.7/dist-packages/spidev-3.5-py3.7-linux-armv6l.egg', '/usr/local/lib/python3.7/dist-packages/Deprecated-1.2.12-py3.7.egg', '/usr/local/lib/python3.7/dist-packages/wrapt-1.12.1-py3.7-linux-armv6l.egg', '/usr/local/lib/python3.7/dist-packages/pcf8574_io-0.1.1-py3.7.egg', '/root/vcgencmd', '/usr/local/lib/python3.7/dist-packages/paho_mqtt-1.6.0-py3.7.egg', '/usr/lib/python3/dist-packages']
>>>

So not sure what to try next.

**Comment by dachshund-digital** [comment]
I reinstalled from my local git branch directory... capture the file list...

/usr/local/lib/python3.7/dist-packages/paho_mqtt-1.6.0-py3.7.egg/EGG-INFO/dependency_links.txt
/usr/local/lib/python3.7/dist-packages/paho_mqtt-1.6.0-py3.7.egg/EGG-INFO/requires.txt
/usr/local/lib/python3.7/dist-packages/paho_mqtt-1.6.0-py3.7.egg/EGG-INFO/SOURCES.txt
/usr/local/lib/python3.7/dist-packages/paho_mqtt-1.6.0-py3.7.egg/EGG-INFO/top_level.txt
/usr/local/lib/python3.7/dist-packages/paho_mqtt-1.6.0-py3.7.egg/EGG-INFO/not-zip-safe
/usr/local/lib/python3.7/dist-packages/paho_mqtt-1.6.0-py3.7.egg/EGG-INFO/PKG-INFO
/usr/local/lib/python3.7/dist-packages/paho_mqtt-1.6.0-py3.7.egg/paho/__init__.py
/usr/local/lib/python3.7/dist-packages/paho_mqtt-1.6.0-py3.7.egg/paho/__pycache__/__init__.cpython-37.pyc
/usr/local/lib/python3.7/dist-packages/paho_mqtt-1.6.0-py3.7.egg/paho/mqtt/reasoncodes.py
/usr/local/lib/python3.7/dist-packages/paho_mqtt-1.6.0-py3.7.egg/paho/mqtt/properties.py
/usr/local/lib/python3.7/dist-packages/paho_mqtt-1.6.0-py3.7.egg/paho/mqtt/publish.py
/usr/local/lib/python3.7/dist-packages/paho_mqtt-1.6.0-py3.7.egg/paho/mqtt/subscribeoptions.py
/usr/local/lib/python3.7/dist-packages/paho_mqtt-1.6.0-py3.7.egg/paho/mqtt/packettypes.py
/usr/local/lib/python3.7/dist-packages/paho_mqtt-1.6.0-py3.7.egg/paho/mqtt/subscribe.py
/usr/local/lib/python3.7/dist-packages/paho_mqtt-1.6.0-py3.7.egg/paho/mqtt/client.py
/usr/local/lib/python3.7/dist-packages/paho_mqtt-1.6.0-py3.7.egg/paho/mqtt/matcher.py
/usr/local/lib/python3.7/dist-packages/paho_mqtt-1.6.0-py3.7.egg/paho/mqtt/__init__.py
/usr/local/lib/python3.7/dist-packages/paho_mqtt-1.6.0-py3.7.egg/paho/mqtt/__pycache__/reasoncodes.cpython-37.pyc
/usr/local/lib/python3.7/dist-packages/paho_mqtt-1.6.0-py3.7.egg/paho/mqtt/__pycache__/packettypes.cpython-37.pyc
/usr/local/lib/python3.7/dist-packages/paho_mqtt-1.6.0-py3.7.egg/paho/mqtt/__pycache__/subscribeoptions.cpython-37.pyc
/usr/local/lib/python3.7/dist-packages/paho_mqtt-1.6.0-py3.7.egg/paho/mqtt/__pycache__/matcher.cpython-37.pyc
/usr/local/lib/python3.7/dist-packages/paho_mqtt-1.6.0-py3.7.egg/paho/mqtt/__pycache__/__init__.cpython-37.pyc
/usr/local/lib/python3.7/dist-packages/paho_mqtt-1.6.0-py3.7.egg/paho/mqtt/__pycache__/publish.cpython-37.pyc
/usr/local/lib/python3.7/dist-packages/paho_mqtt-1.6.0-py3.7.egg/paho/mqtt/__pycache__/subscribe.cpython-37.pyc
/usr/local/lib/python3.7/dist-packages/paho_mqtt-1.6.0-py3.7.egg/paho/mqtt/__pycache__/client.cpython-37.pyc
/usr/local/lib/python3.7/dist-packages/paho_mqtt-1.6.0-py3.7.egg/paho/mqtt/__pycache__/properties.cpython-37.pyc

**Comment by ralight** [comment]
It works just fine for me. The previous version was 1.5.1 so for it to be reporting 1.5.0 is extremely unlikely.

**Comment by ralight** [comment]
If 1.5.0 exists in an earlier path, it will be used by preference.

**Comment by dachshund-digital** [comment]
Well, the question is how to do fix this?  It was 1.5.1... 1.5.0 was a typo.  As you can see from the path and installation, 1.6. should be found, and should be replacing 1.5.1.

**Comment by ralight** [comment]
Try installing it in a virtualenv so you can be sure that you're installing the version you want only:

```
virtualenv <directory to store the virtualenv data>
source <directory to store the virtualenv data>/bin/activate
# Do installation and test now
```

**Comment by dachshund-digital** [comment]
Yeah, started doing that.  Loaded a new OS image (Raspberry Pi), and compiling Python 3.9.x, and will set up virtual environment then load only the modules needed for the given project.  This will include 1.6.x.  First time I have created a virtual environment for python.  But have 20+ years experience with VMware, KVM, Hyper-V, Docker, etc.  So should not be to crazy.

**Comment by dachshund-digital** [comment]
Ok, got virtual environment setup, all the project modules, include explicitly 1.6.x in place.  Now for some scripting and testing.
