### ISSUE TITLE
Reconnect failures when using TLS

### ISSUE THREAD

**Issue by jschlyter** [eclipse/paho.mqtt.python#599]
Using `paho-mqtt` version 1.5.1 as the MQTT client, it seems automatic reconnect does not work when using TLS. The broker (Mosquitto) logs the following on reconnect and the connection is never reestablished:

```
1630044195: New connection from 127.0.0.1:55873 on port 8883.
1630044195: OpenSSL Error[0]: error:14094418:SSL routines:ssl3_read_bytes:tlsv1 alert unknown ca
1630044195: Client <unknown> disconnected: Protocol error.
```

The very same setup without TLS work fine.

**Comment by ralight** [comment]
Glad you got it working :)
