### ISSUE TITLE
Deadlock when using an external mutex before calling subscribe and inside on_subscribe

### ISSUE THREAD

**Issue by rittneje** [eclipse/paho.mqtt.python#603]
This is basically the same as #226, but it applies to SUBSCRIBE/SUBACK instead of PUBLISH/PUBACK. I suspect the same underlying design flaw in the library is the root cause.

We have a dictionary mapping message ids to threading.Events. After `subscribe` is called, we insert an entry for that mid, and when `on_subscribe` is called, we look up the entry for that mid and call `set()`. In order to protect the process as a whole, we have a mutex protecting the operation of calling `subscribe` + inserting into the dictionary. That same mutex is also used in the callback for the lookup. This is because it is possible for the callback to be invoked between the call to `subscribe` and the dictionary insertion, and we don't want to lose that notification.

Here is the pseudo-code to illustrate this situation.
```
def subscribe(self):
    lock()
    mid := self._client.subscribe()
    subs[mid] = threading.Event()
    unlock()

# used as the on_subscribe callback for the paho client
def on_subscribe(self, mid):
    lock()
    subs[mid].set()
    unlock()
```

In particular, the deadlock is caused by the interleaving of our own lock, and (I believe) this library's internal `_callback_mutex`. Is there any way to avoid this? Otherwise it seems like a fundamental design flaw.

**Comment by ralight** [comment]
Could you try with the `1.6.x` branch please?

**Comment by rittneje** [comment]
@ralight After upgrading to 1.6.1 we have no observed any deadlocks, so it seems to be fixed. I will open another issue if it comes back.
