### ISSUE TITLE
subscribe() checking for isinstance(topic, str) may be not be sufficient.

### ISSUE THREAD

**Issue by anirbanroydas** [eclipse/paho.mqtt.python#61]
Suppose somebody sends a `json` encoded topic to be subscribed, in that case, if in **python 2.7**, the `isinstance()` function returns **false**, since the json encoded topic gets converted into `unicode`. 

So checking for both `str` and `unicode` will be a better and safer way. Even when the topic is sent in the `tuple` or `list` format, in both the cases, the **individual topic strings** may be `unicode`.

**Comment by ralight** [comment]
Duplicate of #16 - thanks for the nudge though.
