### ISSUE TITLE
Unhandled exception in version 1.6.1 after trying to reconnect to broker.

### ISSUE THREAD

**Issue by knvovk** [eclipse/paho.mqtt.python#618]
I tested the behavior of my program in case of disconnection from the MQTT broker, and noticed that after disconnection, the on_disconnect method is called as expected, then when trying to reconnect to the broker after the timeout expires, the program crashes due to an unhandled exception (see stack trace below). Testing was conducted with version 1.6.1.

```shell
ERROR:MqttClient:Disconnected with code: 16!
Exception in thread Thread-1:
Traceback (most recent call last):
  File "/usr/lib/python2.7/threading.py", line 801, in __bootstrap_inner
    self.run()
  File "/usr/lib/python2.7/threading.py", line 754, in run
    self.__target(*self.__args, **self.__kwargs)
  File "/home/pi/.local/lib/python2.7/site-packages/paho/mqtt/client.py", line 3591, in _thread_main
    self.loop_forever(retry_first_connection=True)
  File "/home/pi/.local/lib/python2.7/site-packages/paho/mqtt/client.py", line 1779, in loop_forever
    self.reconnect()
  File "/home/pi/.local/lib/python2.7/site-packages/paho/mqtt/client.py", line 1044, in reconnect
    sock = self._create_socket_connection()
  File "/home/pi/.local/lib/python2.7/site-packages/paho/mqtt/client.py", line 3685, in _create_socket_connection
    return socket.create_connection(addr, timeout=self._connect_timeout, source_address=source)
  File "/usr/lib/python2.7/socket.py", line 575, in create_connection
    raise err
timeout: timed out
```

However, I noticed that there was no such problem before. I compared the paho-mqtt version installed on my computer and the  paho-mqtt version installed on the computer where the tests were carried out. On my computer in version 1.5.1 this problem does not occur, one problem occurs in version 1.6.1, which is installed on the test computer. I installed  paho-mqtt 1.5.1 on a test computer and the problem went away.

Has anyone encountered a similar problem?

**Comment by ralight** [comment]
It's possible this could be down to using Python 2.7, which is much less well tested these days as you would expect. Are you tied to Python 2.7? We anticipate that any non-bugfix releases after January 2022 will not support it.

For now - do you have a minimal example that shows this behaviour that you could share with us?

**Comment by knvovk** [comment]
> It's possible this could be down to using Python 2.7, which is much less well tested these days as you would expect. Are you tied to Python 2.7? We anticipate that any non-bugfix releases after January 2022 will not support it.
> 
> For now - do you have a minimal example that shows this behaviour that you could share with us?

Here's a minimal code example. Here, as expected, `_on_disconnect` is called, then `paho.mqtt.client` tries to reconnect and an exception is thrown, the stack trace is provided in the issue description.

```python
#!/usr/bin/env python
# -*- coding: utf-8 -*-

import logging
import socket
import time
import paho.mqtt.client as mqtt
from pydispatch import Dispatcher

# ... other imports


class MqttClient(Dispatcher):
    __metaclass__ = Singleton
    _events_ = ['on_connect', 'on_disconnect', 'on_message',
                'on_publish', 'on_subscribe', 'on_unsubscribe']
    _RECONNECT_TIMEOUT = 10.0

    def __init__(self, host=None, port=1883, keepalive=60, *args, **kwargs):
        super(MqttClient, self).__init__(*args, **kwargs)
        if host is None:
            raise RuntimeError('MQTT host must be specified!')
        client_id = socket.gethostbyname(socket.gethostname())
        self._mqtt = mqtt.Client(client_id=client_id, clean_session=False,
                                 protocol=mqtt.MQTTv311, transport='tcp')
        self._mqtt.on_disconnect = self._on_disconnect
        self._log = logging.getLogger(self.__class__.__name__)
        self._topics = {}
        self._host = host
        self._port = port
        self._keepalive = keepalive
        Delay.once(0, self._connect)

    def _connect(self):
        if not self._mqtt.is_connected():
            self._log.info('Trying to connect...')
            connected = False
            while not connected:
                try:
                    self._mqtt.connect(host=self._host, port=self._port,
                                       keepalive=self._keepalive)
                except IOError as err:
                    self._log.error(err)
                    time.sleep(self._RECONNECT_TIMEOUT)
                else:
                    connected = True
                    self._mqtt.loop_start()

    def _on_disconnect(self, client, userdata, rc):
        self._log.error('Disconnected with code: {}'.format(rc))
        self.emit('on_disconnect', client=client, userdata=userdata, rc=rc)

    # ... other code
```

Accordingly, the error occurs inside the library itself, not the client code.

**Comment by harshag** [comment]
This saved ton of debugging time for us. Encountered same issue with version 1.6.1 for Python 2.7. Reverted to 1.5.1 and it works fine. Thanks.
