### ISSUE TITLE
subscribe.simple topic doesn't exist

### ISSUE THREAD

**Issue by canDry** [eclipse/paho.mqtt.python#619]
Further to this closed issue: https://github.com/eclipse/paho.mqtt.python/issues/262  
I wonder if it could be reconsidered ie. if using subscribe.simple (vs. call back) and the topic doesn't exist could it return a NULL payload??  
  
This would be useful for example an IoT device that connects periodically to check if a topic exists, and if so gets the last (retained) message and if not, goes on doing something else or goes back to sleep.
  
Or... perhaps there some other paho method to check whether a topic exists?

**Comment by MattBrittan** [comment]
> the topic doesn't exist

It's not really clear what "topic doesn't exist" means in this context. An MQTT server does not maintain a list of topics that "exist"; it will retain a list of topics that have subscribers and, potentially, have a store of retained messages, but the protocol does not make this info available.

As such I think you want to:
1. Connect
2. Retrieve all retained messages
3. Disconnect

Unfortunately, once more, the MQTT protocol does not provide a way to get a count of the retained messages that match a topic filter, or the option to only retrieve retained messages. When you subscribe the server will send any retained messages and then start a stream of new messages (v5 does allow some customisation of this). You would need to determine when all retained messages have been received and disconnect at that point. See [this](https://stackoverflow.com/a/77466608/11810946) on stackoverflow for a bit more info.

This really leaves a couple of options:
* Connect and wait for a fixed period before disconnecting
* Connect and wait until no retained messages are received within a set period
* Connect and wait until you receive a message that does not have the retain flag set (this is not guaranteed to work!)

Given that a timeout is the likely solution here and there is issue #655 focuses on that I'm going to close this issue (apologies that no one responded earlier!).
