### ISSUE TITLE
Missing epl-v20 in official 1.6.1 tarball

### ISSUE THREAD

**Issue by ffontaine** [eclipse/paho.mqtt.python#633]
The [official 1.6.1 tarball](https://files.pythonhosted.org/packages/f8/dd/4b75dcba025f8647bc9862ac17299e0d7d12d3beadbf026d8c8d74215c12/paho-mqtt-1.6.1.tar.gz) available on pypi is missing `epl-v20`. The tarball only contains `LICENSE.txt` and `edl-v10`.

**Comment by jamesmyatt** [comment]
Can you open a PR to fix MANIFEST.in?

**Comment by ffontaine** [comment]
I opened a PR as requested
