### ISSUE TITLE
MessageExpiryInterval MQTT v5 support

### ISSUE THREAD

**Issue by maximehyh** [eclipse/paho.mqtt.python#649]
Hello, 

I am currently using Paho MQTT in order to test some real time applications where data should (almost) not be stored within the broker (or at least no more than a few seconds). 

I have seen on MQTT's documentation that v5 could help me doing this through the usage of [Message Expiry Interval](https://docs.oasis-open.org/mqtt/mqtt/v5.0/os/mqtt-v5.0-os.html#_Toc3901064). 

I tried a few things based on the examples available in the tests section for [Session Expiry Interval](https://github.com/eclipse/paho.mqtt.python/blob/6dfdeba6ea6422d942f16e3b1f1bf4bd92dda480/tests/test_mqttv5.py#L377) and  [Publish Properties](https://github.com/eclipse/paho.mqtt.python/blob/6dfdeba6ea6422d942f16e3b1f1bf4bd92dda480/tests/test_mqttv5.py#L252). but did not manage to get the expected bahaviour. 

For example the below code does not seem to work:

```python
publish_properties = Properties(PacketTypes.PUBLISH)
publish_properties.MessageExpiryInterval = 1
client = mqtt.Client(protocol=mqtt.MQTTv5)
client.connect(IP, PORT, properties=publish_properties)
client.publish(
  topic,
  payload,
  retain=False,
  properties=publish_properties,
)
```
Is the `MessageExpiryInterval` feature implemented within Paho? 

Thanks!

**Comment by nealepetrillo** [comment]
Running into a similar problem trying to replicate the V311 clean session behavior. Using the `Properties.writeProperty()` function didn't get me anywhere.

**Comment by econeale** [comment]
I can also report that this doesn't work: 

```
properties = Properties(PacketTypes.CONNECT)
properties.UserProperty = ('Message Expiry Interval', 30)
```

```
  File "/usr/local/lib/python3.9/site-packages/paho/mqtt/client.py", line 1088, in reconnect
    return self._send_connect(self._keepalive)
  File "/usr/local/lib/python3.9/site-packages/paho/mqtt/client.py", line 2752, in _send_connect
    packed_connect_properties = self._connect_properties.pack()
  File "/usr/local/lib/python3.9/site-packages/paho/mqtt/properties.py", line 376, in pack
    buffer += self.writeProperty(identifier,
  File "/usr/local/lib/python3.9/site-packages/paho/mqtt/properties.py", line 363, in writeProperty
    buffer += writeUTF(value[0]) + writeUTF(value[1])
  File "/usr/local/lib/python3.9/site-packages/paho/mqtt/properties.py", line 58, in writeUTF
    data = data if type(data) == type(b"") else bytes(data, "utf-8")
TypeError: encoding without a string argument
```

**Comment by MattBrittan** [comment]
I'm going to close this based on the comment from @call-me-matt above (note that Message Expiry Interval only applies to PUBLISH and Will Properties). If users are still having issues then please feel free to reopen this issue.

Note: This is part of an exercise to clean up old issues so that the project can move forwards. Due to the number of issues being worked through mistakes will be made; please feel free to reopen this issue (or comment) if you believe it's been closed in error.
