### ISSUE TITLE
DeprecationWarning: ssl.PROTOCOL_TLS is deprecated

### ISSUE THREAD

**Issue by maranov** [eclipse/paho.mqtt.python#653]
Per [Python ssl docs](https://docs.python.org/3/library/ssl.html#ssl.PROTOCOL_TLS), the `PROTOCOL_TLS` has been deprecated, replaced with `PROTOCOL_TLS_CLIENT/SERVER`. This setting is used in the client at:
<https://github.com/eclipse/paho.mqtt.python/blob/9782ab81fe7ee3a05e74c7f3e1d03d5611ea4be4/src/paho/mqtt/client.py#L791>

From what I understood, the `PROTOCOL_TLS_CLIENT` should be the correct replacement (for client connections), but it has some side effects:
> The protocol enables [CERT_REQUIRED](https://docs.python.org/3/library/ssl.html#ssl.CERT_REQUIRED) and [check_hostname](https://docs.python.org/3/library/ssl.html#ssl.SSLContext.check_hostname) by default.

Looking at the client code, this seems to be the defaults for `tls_set` as well. Replacing the `PROTOCOL_TLS` with `PROTOCOL_TLS_CLIENT`, while using `PROTOCOL_TLS` as a fallback for Python 2.7 should remove the deprecation warning.

**Comment by maranov** [comment]
I could open a PR if the proposed solution sounds like a good idea.

**Comment by timhaines** [comment]
@maranov sounds good to me.  Would love to see this warning disappear. 👍

**Comment by MattBrittan** [comment]
As PR #665 has now been merged I believe this issue can be closed. Note that there are a few other related issues that will remain open (the documentation does not really match the code).

Note: This is part of an exercise to clean up old issues so that the project can move forwards. Due to the number of issues being worked through mistakes will be made; please feel free to reopen this issue (or comment) if you believe it's been closed in error.

**Comment by poonkothaip** [comment]
Hi
Using python 3.12 and using below code to connect -

def create_ftps_client(server_hostname, server_port, certfile, keyfile):
  
    context = ssl.SSLContext(ssl.PROTOCOL_TLS_CLIENT)
    context.load_cert_chain(certfile=certfile, password=keyfile)
    ftps = FTP_TLS(context=context)
    try:

        ftps.connect(server_hostname, server_port)
        ftps.auth()
        print("FTPS connection established successfully")
        return ftps
    except ssl.SSLError as e:
        print(f"Failed to connect to the server: {e}")
        return None


when using  context = ssl.SSLContext(ssl.PROTOCOL_TLS_CLIENT) - getting this error  Failed to connect to the server: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1000) 
when using context = ssl.SSLContext(ssl.PROTOCOL_TLSv1_2) connection is successful but get warnings DeprecationWarning: ssl.PROTOCOL_TLSv1_2 is deprecated

Can you please suggest how can warning be removed and make it work properly. 

Thanks
Poongkothai

**Comment by JamesParrott** [comment]
@poonkothaip This thread is closed.  Furthermore, it is about a specific issue relating to the Paho library for the MQTT protocol.  Not for general help questions about the FTP protocol, or anything else unrelated.  Try a general Python help forum.
