### ISSUE TITLE
topic_matches_sub() incorrectly filter some subscriptions

### ISSUE THREAD

**Issue by yoch** [eclipse/paho.mqtt.python#67]
`('sport/#', 'sport/')` -> `False` instead of `True`

Also, some invalid filters are accepted.

`('sport+', 'sport')` -> `True` which is incorrect. etc

Here my proposal, which is simpler than the previous code, can detect invalid subscriptions, and runs faster (by about 30%) :

``` python
def topic_matches_sub(sub, topic):
    "return None if the subscription is invalid (maybe raise an exception ?)"

    if not sub or not topic:
        # invalid (all topic names and topic filters MUST be at least one character long)
        return None

    if topic[0] == '$' and sub[0] != '$':
        return False

    sub_l, topic_l = sub.split('/'), topic.split('/')
    sub_sz, topic_sz = len(sub_l), len(topic_l)

    for i, level in enumerate(sub_l):

        if level == '#':
            if i + 1 < sub_sz:
                return None # invalid ('#' not at end)
            return True

        elif level == '+':
            if i >= topic_sz:
                return False

        else:
            if '#' in level or '+' in level:
                return None # invalid ('#' / '+' in level part)
            if i >= topic_sz or level != topic_l[i]:
                return False

    return sub_sz == topic_sz
```

On the other hand, it doesn't detect all inconsistencies in topic format.

**Comment by ralight** [comment]
> On the other hand, it doesn't detect all inconsistencies in topic format.

Could you explain the inconsistencies you are referring to?

**Comment by ralight** [comment]
Ah, you mean it detects invalid subscriptions but not invalid topics?

**Comment by yoch** [comment]
I mean MQTT **topics** constraints :

- The wildcard characters [...] MUST NOT be used within a Topic Name [MQTT-4.7.1-1].
- Topic Names and Topic Filters MUST NOT include the null character (Unicode U+0000) [MQTT-4.7.3-2]

It would be nice to have dedicated functions to validate inputs, but it's not the job for `topic_matches_sub()`.

**Comment by ralight** [comment]
Agreed on both counts. I'll merge this after 1.2 is released.

**Comment by yoch** [comment]
Here a check for subscriptions filters :

```python
    def _filter_wildcard_len_check(sub):
        if (len(sub) == 0 or len(sub) > 65535
            or any('+' in p or '#' in p for p in sub.split('/') if len(p) > 1)
            or '#/' in sub):
            return MQTT_ERR_INVAL
        else:
            return MQTT_ERR_SUCCESS
```

**Comment by PierreF** [comment]
I'm closing this issue as fixes are merged in develop branch.
