### ISSUE TITLE
Not able to send data through secure port 8883

### ISSUE THREAD

**Issue by Eldho1416** [eclipse/paho.mqtt.python#677]
Hi,

I'm trying to send data through secured connection where i'm using` tls_set_context(context=None)` to match with server side certificate, and i was able to send data previously when i checked today it is not working, i'm not able to figure out what the issue is.

**Comment by Sohaib90** [comment]
Hello, 

It will be nice if I can have some more information. Maybe the code snippet you use, the strategy, or the error log (if you get one). Moreover, the behavior you are expecting and the behavior you actually see.

**Comment by Eldho1416** [comment]
Hi Sohaib, 

This issue was resolved, the issue was in server side. Thank you for your reply.

**Comment by Eldho1416** [comment]
Server side issue
