### ISSUE TITLE
Safeguard for subscribing to empty list of topics.

### ISSUE THREAD

**Issue by peromvikgoodtech** [eclipse/paho.mqtt.python#690]
I had an issue where I mistakenly called `MqttClient.subscribe()` with an empty list inside the `on_connect()` callback, as recommended in the docs. Instead of raising an error, the client disconnects and enters an indefinite reconnect loop. 

Recommended fix: Assert non-emptiness of list passed to the subscribe method in MqttClient.

**Comment by ralight** [comment]
Thank you, I've fixed that.
