### ISSUE TITLE
Operation timed out if Internet connection is lost (TCP connection)

### ISSUE THREAD

**Issue by samson0v** [eclipse/paho.mqtt.python#709]
Hi everyone!
I am developing ThingsBoard IoT Gateway that uses as a dependency paho mqtt python library for data transition to ThingsBoard. 
Our clients and we encountered the following problem:
When you turn off your internet connection and still publish messages, after a timeout raises the following exception:
<img width="1500" alt="зображення" src="https://user-images.githubusercontent.com/43861229/225250801-8b417522-20d8-44c4-bba6-b8f192fc3d35.png">
After that, if you turn on the internet connection, new messages will not be published.

After some research in the issues tab, I saw that you fixed this issue but for the WebSocket connection type. Also, there is the same issue #694 

I created PR #710 that fixes this issue.

**Comment by MattBrittan** [comment]
Closing this as Pierre has merged your PR (well cherry-picked your first commit). Please reopen if this does not resolve the issue.
