### ISSUE TITLE
UserProperty method not available

### ISSUE THREAD

**Issue by BlackRose01** [eclipse/paho.mqtt.python#724]
Hello,

in my project I want to use the paho library to communicate with my MQTT Broker via MQTTv5. I also would like to use the UserProperties option from MQTTv5 but unfortunately it is not possible to create custom UserProperties as it mentioned here:

[https://github.com/eclipse/paho.mqtt.python/blob/a4cb435ca2864d073ea3e0e18b0407e4bbe85b16/src/paho/mqtt/properties.py#L142-L159](https://github.com/eclipse/paho.mqtt.python/blob/a4cb435ca2864d073ea3e0e18b0407e4bbe85b16/src/paho/mqtt/properties.py#L142-L159)

Am I missing something?

Thanks in advanced.

KR,
BlackRose01

**Comment by fpagliughi** [comment]
That works fine for me. What problem are you having with it?

**Comment by BlackRose01** [comment]
Sorry, I'm stupid -.- I always had a typo in it. I wrote UserPropety instead of UserProperty.
