### ISSUE TITLE
allow Client Identifier to be a nullstring

### ISSUE THREAD

**Issue by yoch** [eclipse/paho.mqtt.python#73]
Why using no client_id [isn't authorized](https://github.com/eclipse/paho.mqtt.python/blob/master/src/paho/mqtt/client.py#L499) ? It's sometime useful, and this is allowed by MQTT specifications : 

> A Server MAY allow a Client to supply a ClientId that has a length of zero bytes, however if it does so the Server MUST treat this as a special case and assign a unique ClientId to that Client. It MUST then process the CONNECT packet as if the Client had provided that unique ClientId [MQTT-3.1.3-6].
> 
> If the Client supplies a zero-byte ClientId, the Client MUST also set CleanSession to 1 [MQTT-3.1.3-7].

___

Also, current implementation of random ClientId is not very safe, because it can lead to subtle bugs. For instance, this script causes `mqtt.Client` chooses the same ClientId for clients, introducing competition between them to take over if we run several clients : 

```python
import random
import paho.mqtt.client as mqtt


def on_connect(client, userdata, flags, rc):
    print(client._client_id, "Connected with result code ", rc)

def on_disconnect(client, userdata, rc):
    print(client._client_id, "Disconnected with result code ", rc)


# suppose, for some reason, we make
random.seed(0)

# and just later start the client
client = mqtt.Client()
client.on_connect = on_connect
client.on_disconnect = on_disconnect

client.connect("iot.eclipse.org")
client.loop_forever()
```

**Comment by ralight** [comment]
It's largely historical, MQTT 3.1 didn't allow zero length client ids.

**Comment by ralight** [comment]
I'm treating this as a bug for zero length client ids, which is now fixed. Your pull request should then fix the randomness (please use separate bug reports for separate issues to make it easier to deal with).

Thanks for your work.
