### ISSUE TITLE
ssl tls protocol googler issue

### ISSUE THREAD

**Issue by anirbanchakrabarty** [eclipse/paho.mqtt.python#740]
hi am using googler but fetcing no results. heres the debug report. need help.highly appreciated. googler --debug [DEBUG] googler version 4.3.2 [DEBUG] Python version 3.11.2 [DEBUG] Platform: Linux-6.2.9-300.fc38.x86_64-x86_64-with-glibc2.37 /usr/bin/googler:3496: DeprecationWarning: distutils Version classes are deprecated. Use packaging.version instead. current_version = Version(VERSION) /usr/bin/googler:3497: DeprecationWarning: distutils Version classes are deprecated. Use packaging.version instead. latest_version = Version(latest_version_str) [DEBUG] Connecting to new host [www.google.com](http://www.google.com/) [DEBUG] Opened socket to 142.250.193.132:443 /usr/bin/googler:1611: DeprecationWarning: ssl.PROTOCOL_TLS is deprecated ssl_context = ssl.SSLContext(ssl.PROTOCOL_TLS) [DEBUG] new_connection completed in 0.164s Please initiate a query. googler (? for help)

while using googler results not displayed.here's the output:

[root@fedora googler-master]# googler [www.looklinux.xom](http://www.looklinux.xom/) /usr/bin/googler:1611: DeprecationWarning: ssl.PROTOCOL_TLS is deprecated ssl_context = ssl.SSLContext(ssl.PROTOCOL_TLS) No results. If you believe this is a bug, please review https://git.io/googler-no-results before submitting a bug report.

**Comment by gdt** [comment]
Looks like you filed a bug in the wrong repo.   I suggest closing and addressing this with googler, whatever that is.
