### ISSUE TITLE
Subscriber Identifier 

### ISSUE THREAD

**Issue by daniellelaforte** [eclipse/paho.mqtt.python#744]
Any plans to add the capability to set the subscriber identifier on subscribe like in MQTTX? 

My broker doesn't publish anything for it by default, and therefore the messages are not received with the error Subscriberidentifier must be between 1-26000

**Comment by petersilva** [comment]
Can you provide a pointer to the functionality you are referring to on MQTTX?
The string "Subscriberidentifier" is not present in the library. I don't think the message is being returned by paho-mqtt-python.

**Comment by MattBrittan** [comment]
Closing this as there has been no response from OP to a request for clarification (tidying up open issues).
