### ISSUE TITLE
Long Term Maintanability

### ISSUE THREAD

**Issue by r0kk** [eclipse/paho.mqtt.python#758]
Hi, we are choosing new mqtt library, and my question is what are long/mid term plans for active support/maintenance of the project? Thank you very much.

**Comment by petersilva** [comment]
I´m not on the paho team, but reflecting what I have gathered from lurking for a little while:

Issues are meant to address defects in the code, or suggestions for improvements.
They are not discussions.  It would likely be better to close this issue and ask on the mailing list.

The actual devs seem to be unhappy that people are opening issues to ask questions, and may not answer on principle, which might send you the wrong signal.

**Comment by r0kk** [comment]
Hi, I completely agree. Thanks for pointers.
