### ISSUE TITLE
Tests are flaky on `master`

### ISSUE THREAD

**Issue by akx** [eclipse/paho.mqtt.python#789]
Tests are currently flaky on `master`. These seem to be the newly re-enabled MQTTv5 tests.

@PierreF Instead of `paho.mqtt.testing`, would it make sense to just use Mosquitto here?

**Comment by PierreF** [comment]
MQTTv5 test aren't optimal in current form. They are very slow (I've quickly looked and didn't find a way to make them run faster easily).

Yes doing test using a real broker like mosquitto might be a good solution.

**Comment by PierreF** [comment]
Done some fix in e96ff7578f7f56a7f3068fbc3e7d0b48e1c64a97 which seems good enough. The last run on master worker without need to retry.
