### ISSUE TITLE
catch all except blocks KeyboardInterrupt

### ISSUE THREAD

**Issue by jpwsutton** [eclipse/paho.mqtt.python#8]
migrated from Bugzilla [#477353](https://bugs.eclipse.org/bugs/show_bug.cgi?id=477353)
status UNCONFIRMED severity *minor* in component *MQTT-Python* for *1.2*
Reported in version *1.1* on platform *PC*
Assigned to: Roger Light

Original attachment names and IDs:
- _[diff](https://bugs.eclipse.org/bugs//attachment.cgi?id=256550)_ (ID 256550)

On 2015-09-14 07:19:05 -0400, matt venn wrote:

> Created attachment 256550
> diff
> 
> something like this:
> 
> try:
>     client.loop_forever()
> except KeyboardInterrupt as e:
>     print("ending")
> 
> doesn't work properly because there is a bare except clause in loop():
> 
> except:
>             return MQTT_ERR_UNKNOWN
> 
> the diff below fixes that by handling KeyboardError with a raise

**Comment by mattvenn** [comment]
fixed in my pull request

**Comment by ralight** [comment]
Fixed in 1.2.
