### ISSUE TITLE
Error/status handling in publish.single method

### ISSUE THREAD

**Issue by buhln** [eclipse/paho.mqtt.python#807]
We are using the publish.single method for sending MQTT messages in a really low frequency and it works great as long the server is available. Unfortunatly we see no possibility at the moment to monitor the successfull sent of the message. Is there a possible solution for this? 

If the server is not available we catch this by try/except...

Thanks in advance!
nico

**Comment by PierreF** [comment]
That seems like the wanted behavior. If publish.single return (without exception) your message is published. If not not, it's not published. Having a function raise exception on error (like network error) is the right behavior IMO.

I'm not sure what behavior you are expecting. Do you want publish.single to retry connection by itself (e.g. can't fail, either return on success or hang - possibly forever) ?

**Comment by buhln** [comment]
Hi, Thank you for your answer.

I was looking for the best way to handle this. As I mention, we are catch errors at the moment by try/except. If this is the best way to do this for this function I am fine with it. Thanks!
