### ISSUE TITLE
New documentation is not available

### ISSUE THREAD

**Issue by flbraun** [eclipse/paho.mqtt.python#815]
The new documentation mentioned in the v2.0 release notes and README is not available. Opening the links returns HTTP 503.

https://eclipse.dev/paho/files/paho.mqtt.python/html/index.html
https://eclipse.dev/paho/files/paho.mqtt.python/html/migrations.html
https://eclipse.dev/paho/files/paho.mqtt.python/html/client.html

**Comment by PierreF** [comment]
All the links you provided are working from my laptop or my mobile. Maybe there had a temporary issue.

**Comment by flbraun** [comment]
Can confirm that it now works again. It wasn't available for at least 2 hours, so I thought it was something more serious. Thanks!
