### ISSUE TITLE
Client __init__  first arg is callback_api_version not client_id

### ISSUE THREAD

**Issue by showfuture** [eclipse/paho.mqtt.python#841]
![image](https://github.com/eclipse/paho.mqtt.python/assets/28568478/05205c76-ecb3-416f-9afb-40f38514d265)
![image](https://github.com/eclipse/paho.mqtt.python/assets/28568478/e734f818-b8a7-4b12-a8f1-ef848245fd2e)

paho-mqtt: 2.1.0

__init__  first arg is callback_api_version not client_id

**Comment by MattBrittan** [comment]
This duplicates #824 so I'm going to close it (as the other issue was raised earlier, and does not use screenshots so is easier to read).
