### ISSUE TITLE
mqtt client flash without network

### ISSUE THREAD

**Issue by jpwsutton** [eclipse/paho.mqtt.python#9]
migrated from Bugzilla [#476694](https://bugs.eclipse.org/bugs/show_bug.cgi?id=476694)
status UNCONFIRMED severity _critical_ in component _MQTT-Python_ for _1.2_
Reported in version _1.1_ on platform _PC_
Assigned to: Roger Light

On 2015-09-05 06:19:59 -0400, Paolo Patruno wrote:

> mqtt client stop for ever if only local interface is up in network configuration.
> 
> program stop inside sock1.connect(("127.0.0.1", port)) in _socketpair_compat

On 2015-09-07 10:01:07 -0400, Paolo Patruno wrote:

> Solved with:
> sock1.settimeout(10)
> 
> ....
> sock2.settimeout(10)

**Comment by PierreF** [comment]
I think this is already fixed. Current code include sock1.setblocking(0) which should avoid any hang.
